### ISSUE TITLE
🐛 BUG: Support proxies in `wrangler dev --remote`

### ISSUE THREAD

**Issue by ResetPower** [cloudflare/workers-sdk#1497]
### What version of `Wrangler` are you using?

2.0.22

### What operating system are you using?

macOS 12.3

### Describe the Bug

```
> wrangler dev

 ⛅️ wrangler 2.0.22 
--------------------
⬣ Listening at http://localhost:8787
TypeError: fetch failed
    at Object.processResponse (/path/to/my-project/node_modules/wrangler/wrangler-dist/cli.js:74624:34)
    at /path/to/my-project/node_modules/wrangler/wrangler-dist/cli.js:74946:42
    at node:internal/process/task_queues:141:7
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  cause: [Error: 4569945600:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:332:
  ] {
    library: 'SSL routines',
    function: 'ssl3_get_record',
    reason: 'wrong version number',
    code: 'ERR_SSL_WRONG_VERSION_NUMBER'
  }
}
Something went wrong:
TypeError: fetch failed
    at Object.processResponse (/path/to/my-project/node_modules/wrangler/wrangler-dist/cli.js:74624:34)
    at /path/to/my-project/node_modules/wrangler/wrangler-dist/cli.js:74946:42
    at node:internal/process/task_queues:141:7
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

✘ [ERROR] fetch failed
```

**Comment by petebacondarwin** [comment]
Hi @ResetPower - thanks for posting this issue. In order to help us resolve it, could you provide a runnable example of this problem that we could reproduce locally? Ideally a Wrangler project with appropriate wrangler.toml and source code, that we can run ourselves.

**Comment by ResetPower** [comment]
I just created a new project using `wrangler init` without any modification

wrangler.toml
```toml
name = "my-project"
main = "src/index.ts"
compatibility_date = "2022-07-19"
```

**Comment by ResetPower** [comment]
I unset environment variable $HTTP_PROXY $HTTPS_PROXY $http_proxy $https_proxy, and I met the problem below

```
✘ [ERROR] Error while creating remote dev session: TypeError: fetch failed

      at Object.processResponse
  (/path/to/my-project/node_modules/wrangler/wrangler-dist/cli.js:74624:34)
      at
  /path/to/my-project/node_modules/wrangler/wrangler-dist/cli.js:74946:42
      at node:internal/process/task_queues:141:7
      at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
      at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    cause: ConnectTimeoutError: Connect Timeout Error
        at Timeout.onConnectTimeout [as _onTimeout]
  (/path/to/my-project/node_modules/wrangler/wrangler-dist/cli.js:69093:28)
        at listOnTimeout (node:internal/timers:561:11)
        at processTimers (node:internal/timers:502:7) {
      code: 'UND_ERR_CONNECT_TIMEOUT'
    }
  }
```

**Comment by ResetPower** [comment]
Leaving just HTTP_PROXY and still have the problem.
`wrangler whoami` works normally.

**Comment by attraction11** [comment]
I had the same problem: [ERROR] Error while creating remote dev session: TypeError: fetch failed。
I use this template and add my own account_id. https://github.com/flareact/flareact-template

**Comment by attraction11** [comment]
> Leaving just HTTP_PROXY and still have the problem. `wrangler whoami` works normally.

Hi, is there any progress?

**Comment by rozenmd** [comment]
`wrangler dev` does not support proxies, `wrangler dev --local` should fix it temporarily. 

Adding this to the backlog.

**Comment by superorange** [comment]
> 

thank you!
