### ISSUE TITLE
🐛 BUG: Error: Maximum number of keys modified in a transaction is 128.

### ISSUE THREAD

**Issue by adcar** [cloudflare/workers-sdk#2399]
### What version of `Wrangler` are you using?

2.6.2

### What operating system are you using?

Windows 11

### Describe the Bug

When attempting to run `wrangler d1 execute products --file=./inserts.sql`, and have 35k rows in my DB which are indexed by a name (TEXT) column I'm greeted with this error:

```
🌀 Mapping SQL input into an array of statements
🌀 Parsing 5000 statements
🌀 Executing on products (<id>):

✘ [ERROR] A request to the Cloudflare API (/accounts/<id>/d1/database/<id>/query) failed.

  Error 9000: exception caught in D1 core. Maximum number of keys modified in a transaction is 128.
  Error: Maximum number of keys modified in a transaction is 128.
      at Object.m [as putPage] (worker.js:2595:29)
      at put_page (worker.js:2438:15)
      at worker.js:2267:15
      at wasm://wasm/00f4590e:wasm-function[49]:0x863a
      at wasm://wasm/00f4590e:wasm-function[3209]:0x1d220e
      at wasm://wasm/00f4590e:wasm-function[3186]:0x1cd0d2
      at wasm://wasm/00f4590e:wasm-function[3189]:0x1cdb39
      at wasm://wasm/00f4590e:wasm-function[3242]:0x1d7673
      at wasm://wasm/00f4590e:wasm-function[3300]:0x1eadf0
      at wasm://wasm/00f4590e:wasm-function[3297]:0x1dd6c9 [code: 7500]


  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose
```
This does *not* happen if I remove the index on my database.

My schema is as follows:
```
DROP TABLE IF EXISTS Products;
CREATE TABLE Products (id INT, name TEXT, PRIMARY KEY (`id`));

CREATE INDEX product_name_index ON Products (name);
```

And some examples of the inserts I'm trying to do are:
```
INSERT INTO Products(id,name) VALUES (29959,'Chicken Stuffing Mix');
INSERT INTO Products(id,name) VALUES (29960,'Acini di Pepe, No. 78');
INSERT INTO Products(id,name) VALUES (29961,'Seaweed Crisps Almond Sesame');
INSERT INTO Products(id,name) VALUES (29962,'Kettle Cooked Sweet Hawaiian Onion Potato Chips');
INSERT INTO Products(id,name) VALUES (29963,'Moroccan Argan Oil Renewing Shampoo');
INSERT INTO Products(id,name) VALUES (29964,'Organic Savory Spice Sweet Potato Fries');
INSERT INTO Products(id,name) VALUES (29965,'Star Fruit');
```

**Comment by rozenmd** [comment]
Hey @adcar,
We recently released a new D1 backend which fixes this issue, you can read more about it here: https://blog.cloudflare.com/d1-turning-it-up-to-11/
