### ISSUE TITLE
🐛 BUG: Pages dev throws error when _headers/_redirects is modified

### ISSUE THREAD

**Issue by WalshyDev** [cloudflare/workers-sdk#2638]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

2.8.1

### What operating system are you using?

Mac

### Describe the Bug

If you are running `wrangler pages dev` and `_headers` or `_redirects` is modified then we throw a lovely error. Looks like this comes from within Miniflare, are we missing some log option when starting the dev server?

Repro:
* `wrangler pages dev <dir>`
* Modify `_headers`
* See your error

```
_headers modified. Re-evaluating...
[pages:err] Unhandled Promise Rejection: TypeError: Cannot read properties of undefined (reading 'logWithLevel')
    at warn (/node_modules/@miniflare/shared/src/log.ts:90:10)
    at constructRedirects (file:///node_modules/wrangler/miniflare-dist/index.mjs:5654:3)
    at createMetadataObject (file:///node_modules/wrangler/miniflare-dist/index.mjs:5639:8)
    at FSWatcher.<anonymous> (file:///node_modules/wrangler/miniflare-dist/index.mjs:6112:18)
    at FSWatcher.emit (node:events:513:28)
    at FSWatcher.emit (node:domain:489:12)
    at FSWatcher.emitWithAll (/node_modules/chokidar/index.js:540:8)
    at FSWatcher._emit (/node_modules/chokidar/index.js:632:8)
    at FsEventsHandler.handleEvent (/node_modules/chokidar/lib/fsevents-handler.js:289:14)
    at FsEventsHandler.addOrChange (/node_modules/chokidar/lib/fsevents-handler.js:239:8)
_redirects modified. Re-evaluating...
[pages:err] Unhandled Promise Rejection: TypeError: Cannot read properties of undefined (reading 'logWithLevel')
    at warn (/node_modules/@miniflare/shared/src/log.ts:90:10)
    at constructRedirects (file:///node_modules/wrangler/miniflare-dist/index.mjs:5654:3)
    at createMetadataObject (file:///node_modules/wrangler/miniflare-dist/index.mjs:5639:8)
    at FSWatcher.<anonymous> (file:///node_modules/wrangler/miniflare-dist/index.mjs:6112:18)
    at FSWatcher.emit (node:events:513:28)
    at FSWatcher.emit (node:domain:489:12)
    at FSWatcher.emitWithAll (/node_modules/chokidar/index.js:540:8)
    at FSWatcher._emit (/node_modules/chokidar/index.js:632:8)
    at FsEventsHandler.handleEvent (/node_modules/chokidar/lib/fsevents-handler.js:289:14)
    at FsEventsHandler.addOrChange (/node_modules/chokidar/lib/fsevents-handler.js:239:8)
```

**Comment by WalshyDev** [comment]
This was fixed with 3.x. Confirmed works on 3.9.0
