### ISSUE TITLE
🐛 BUG: D1 import fails

### ISSUE THREAD

**Issue by bisgardo** [cloudflare/workers-sdk#2762]
### Which Cloudflare product(s) does this pertain to?

D1

### What version of `Wrangler` are you using?

2.10.0

### What operating system are you using?

Linux

### Describe the Bug

I generated a file `db.sql` to be imported. Running `wrangler d1 execute trashcal --file=db.sql` yields 20 batches to be sent individually (`[...]` is me hiding the real values):

```
Delegating to locally-installed wrangler@2.10.0 over global wrangler@2.10.0...
Run `npx wrangler d1 execute trashcal --file=db.sql` to use the local version directly.

▲ [WARNING] Processing wrangler.toml configuration:

    - D1 Bindings are currently in alpha to allow the API to evolve before general availability.
      Please report any issues to https://github.com/cloudflare/workers-sdk/issues/new/choose
      Note: Run this command with the environment variable NO_D1_WARNING=true to hide this message
  
      For example: `export NO_D1_WARNING=true && wrangler <YOUR COMMAND HERE>`


--------------------
🚧 D1 is currently in open alpha and is not recommended for production data and traffic
🚧 Please report any bugs to https://github.com/cloudflare/workers-sdk/issues/new/choose
🚧 To request features, visit https://community.cloudflare.com/c/developers/d1
🚧 To give feedback, visit https://discord.gg/cloudflaredev
--------------------

🌀 Mapping SQL input into an array of statements
🌀 Parsing 198132 statements
🌀 We are sending 20 batch(es) to D1 (limited to 10000 statements per batch)
✔ ⚠️  Too much SQL to send at once, this execution will be sent as 20 batches.
ℹ️  Each batch is sent individually and may leave your DB in an unexpected state if a later batch fails.
⚠️  Make sure you have a recent backup. Ok to proceed? … yes
🌀 Let's go
🌀 Executing on trashcal (0c17634f-d497-4a1e-88cc-563acf7a34d8):
  CREATE TABLE address (
	street_name INTEGER NOT NULL, 
	house_number I...
🚣 Executed 10000 commands in 1885.3227389156818ms
  INSERT INTO address VALUES([...]
🚣 Executed 10000 commands in 1060.8709761500359ms
  INSERT INTO address VALUES([...]
🚣 Executed 10000 commands in 1021.4313754439354ms
  INSERT INTO address VALUES([...]
🚣 Executed 10000 commands in 1048.2705081999302ms
  INSERT INTO address VALUES([...]
🚣 Executed 10000 commands in 1126.5700313448906ms
  INSERT INTO address VALUES([...]
🚣 Executed 10000 commands in 1056.0520080924034ms
  INSERT INTO address VALUES([...]
🚣 Executed 10000 commands in 1418.963006168604ms
  INSERT INTO address VALUES([...]
🚣 Executed 10000 commands in 1462.7105740606785ms
  INSERT INTO address VALUES([...]

✘ [ERROR] A request to the Cloudflare API (/accounts/92d3f47f91b3bf14a5d6ea94cfb523e1/d1/database/0c17634f-d497-4a1e-88cc-563acf7a34d8/query) failed.

  Internal error [code: 7501]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

```

I deleted the statements that had already been imported from `db.sql` and tried again with 12 batches left. Got a different error this time

```
...
🌀 Mapping SQL input into an array of statements
🌀 Parsing 118132 statements
🌀 We are sending 12 batch(es) to D1 (limited to 10000 statements per batch)
✔ ⚠️  Too much SQL to send at once, this execution will be sent as 12 batches.
ℹ️  Each batch is sent individually and may leave your DB in an unexpected state if a later batch fails.
⚠️  Make sure you have a recent backup. Ok to proceed? … yes
🌀 Let's go
🌀 Executing on trashcal (0c17634f-d497-4a1e-88cc-563acf7a34d8):
  INSERT INTO address VALUES([...]
🚣 Executed 10000 commands in 1785.7498703897ms
  INSERT INTO address VALUES([...]
🚣 Executed 10000 commands in 1620.7366434037685ms
  INSERT INTO address VALUES([...]
🚣 Executed 10000 commands in 1576.9211561381817ms
  INSERT INTO address VALUES([...]
🚣 Executed 10000 commands in 3764.0680629611015ms
  INSERT INTO calendar VALUES([...]

✘ [ERROR] A request to the Cloudflare API (/accounts/92d3f47f91b3bf14a5d6ea94cfb523e1/d1/database/0c17634f-d497-4a1e-88cc-563acf7a34d8/query) failed.

  Error 9000: exception caught in D1 core. failed to allocate for query Error: failed to allocate
  for query
      at Sqlite.query (index.js:2782:13)
      at async sqliteQuery (index.js:4675:29)
      at async index.js:4558:20 [code: 7500]

  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

Trimmed `db.sql` again. 8 batches left, none of them got applied before hitting this new and interesting error:

```
🌀 Mapping SQL input into an array of statements
🌀 Parsing 78132 statements
🌀 We are sending 8 batch(es) to D1 (limited to 10000 statements per batch)
✔ ⚠️  Too much SQL to send at once, this execution will be sent as 8 batches.
ℹ️  Each batch is sent individually and may leave your DB in an unexpected state if a later batch fails.
⚠️  Make sure you have a recent backup. Ok to proceed? … yes
🌀 Let's go
🌀 Executing on trashcal (0c17634f-d497-4a1e-88cc-563acf7a34d8):
  INSERT INTO calendar VALUES(X'dd1d490441a5438899b730117100df62',2023,'...

✘ [ERROR] A request to the Cloudflare API (/accounts/92d3f47f91b3bf14a5d6ea94cfb523e1/d1/database/0c17634f-d497-4a1e-88cc-563acf7a34d8/query) failed.

  Error 9000: exception caught in D1 core. unreachable RuntimeError: unreachable
      at wasm://wasm/00f5366a:wasm-function[4795]:0x31c500
      at wasm://wasm/00f5366a:wasm-function[4848]:0x323290
      at wasm://wasm/00f5366a:wasm-function[4889]:0x32ce82
      at wasm://wasm/00f5366a:wasm-function[215]:0x28644
      at wasm://wasm/00f5366a:wasm-function[4988]:0x3424e2
      at Object.s2 [as query] (index.js:2438:157)
      at async Sqlite.query (index.js:2786:23)
      at async sqliteQuery (index.js:4675:29)
      at async index.js:4558:20 [code: 7500]
```

It's not like this is a huge DB. It has two tables and according to the D1 dashboard they've got 112448 and 7550 rows imported and takes up a total of 16.2 MB.

**Comment by zackangelo** [comment]
I'm also experiencing this error. I'm trying to import a ~37MB dump from sqlite. The insert statements are pretty simple, just a primary key with a blob column. 

```
🌀 Mapping SQL input into an array of statements
🌀 Parsing 1270 statements
🌀 Executing on vsproducts (ca7ec339-ec70-4bea-a808-ebd971b183c1):

✘ [ERROR] A request to the Cloudflare API (/accounts/16bdd021cca4a4b6d689285ab5d44413/d1/database/ca7ec339-ec70-4bea-a808-ebd971b183c1/query) failed.

  Error 9000: exception caught in D1 core. failed to allocate for query Error: failed to allocate
  for query
      at Sqlite.query (index.js:2782:13)
      at async sqliteQuery (index.js:4675:29)
      at async index.js:4558:20 [code: 7500]
```

**Comment by missinglink** [comment]
I am also experiencing this error:

```bash
wrangler --version
 ⛅️ wrangler 2.13.0
```

I used the linux `split` command to break up the file into max 10k lines per file, the first succeeded and the second failed:

```bash
wrangler d1 execute wof --file=diff-part00
--------------------
🚧 D1 is currently in open alpha and is not recommended for production data and traffic
🚧 Please report any bugs to https://github.com/cloudflare/workers-sdk/issues/new/choose
🚧 To request features, visit https://community.cloudflare.com/c/developers/d1
🚧 To give feedback, visit https://discord.gg/cloudflaredev
--------------------

🌀 Mapping SQL input into an array of statements
🌀 Parsing 10000 statements
🌀 Executing on wof (1ec853fa-1f2f-4344-8f09-661e4b8259c5):
🚣 Executed 10000 commands in 1917.0552245676517ms
value of stdout.lastframe() is undefined
```

```bash
wrangler d1 execute wof --file=diff-part01
--------------------
🚧 D1 is currently in open alpha and is not recommended for production data and traffic
🚧 Please report any bugs to https://github.com/cloudflare/workers-sdk/issues/new/choose
🚧 To request features, visit https://community.cloudflare.com/c/developers/d1
🚧 To give feedback, visit https://discord.gg/cloudflaredev
--------------------

🌀 Mapping SQL input into an array of statements
🌀 Parsing 10000 statements
🌀 Executing on wof (1ec853fa-1f2f-4344-8f09-661e4b8259c5):

✘ [ERROR] A request to the Cloudflare API (/accounts/xxx/d1/database/yyy/query) failed.

  Error 9000: exception caught in D1 core. failed to allocate for query Error:
  failed to allocate for query
      at Sqlite.query (index.js:2782:13)
      at async sqliteQuery (index.js:4675:29)
      at async index.js:4558:20 [code: 7500]


  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```
 
 Also worth noting the odd error message `value of stdout.lastframe() is undefined` when it succeeds.

**Comment by missinglink** [comment]
Okay so after some digging through the code and trying different batch sizes I've had success with using batches of size 5000 (for my data), consistently.

Zak above mentioned he is seeing failures for batches of 1270 but also says his data is 'with a blob column' and that it is 37MB.

Looking at this code comment, which I thought was an error, actually provides some insight 💡 
https://github.com/cloudflare/workers-sdk/pull/2946

cc/ @ petebacondarwin is it possible that this `failed to allocate for query` error is due to the request payload being too many *bytes* rather than too many *lines*?

If so, it's a fairly easy fix in wrangler to ensure that the payload is split into equally sized chunks by byte count rather than total lines.

**Comment by petebacondarwin** [comment]
Yeah this sounds about right. @geelen do you have a sense of what the actual constraint is here?
If it is bytes then we could definitely implement that - as long as a single statement is not too large, which may be a concern with the large blob mentioned above?

**Comment by bangank36** [comment]
HI everybody, is there a way to display the complete error when pushing statements to production database?
My .SQL with 5000 statements works fine on local though

```
Mapping SQL input into an array of statements
🌀 Parsing 5000 statements
🌀 Executing on beyondspace_leads (d56d6439-0c74-4f28-8031-74bde0574a51):

✘ [ERROR] Received a malformed response from the API

  <!DOCTYPE html>
  <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
  <!--[if I... (length = 6541)

  POST
  /accounts/d043709fb431e57b9cf329b464bf0615/d1/database/d56d6439-0c74-4f28-8031-74bde0574a51/query
  -> 504 Gateway Time-out
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

```
