### ISSUE TITLE
🐛 BUG: Wrangler will incorrectly disregard `exports` if `browser`/`module`/`main` are defined.

### ISSUE THREAD

**Issue by balupton** [cloudflare/workers-sdk#2805]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.11.1

### What operating system are you using?

Mac

### Describe the Bug

Wrangler in practice ignores its documented behaviour at:

- https://developers.cloudflare.com/workers/wrangler/bundling/#conditional-exports
- https://runtime-keys.proposal.wintercg.org/#workerd

If the `module`, `browser`, or `main` fields are defined.

---

I've setup a proof of failure repo at:

https://github.com/balupton/astro-cfpages-esbuild-resolution-bug

```
> npm install
> npx wrangler pages dev public/
🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/workers-sdk/issues/new/choose
▲ [WARNING] No compatibility_date was specified. Using today's date: 2023-02-27.

  Pass it in your terminal:
  --compatibility-date=2023-02-27
  See https://developers.cloudflare.com/workers/platform/compatibility-dates/ for more information.


Compiling worker to "/var/folders/3v/fjmy4fyx1p9c28v31vzm8j9r0000gn/T/functionsWorker-0.773551694099083.mjs"...
✨ Compiled Worker successfully
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Debugger listening on ws://127.0.0.1:55956/5cee4c70-78a6-4b16-be7e-69b1d6b359fd
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[pages:wrn] Service bindings are experimental. There may be breaking changes in the future.
[pages:err] ReferenceError: window is not defined
    at browser (/private/Users/balupton/Projects/websites/astro-cfpages-esbuild-resolution-bug/conditional-resolution-package/browser.mjs:2:2)
    at /private/Users/balupton/Projects/websites/astro-cfpages-esbuild-resolution-bug/functions/[[catchall]].tsx:3:16
    at SourceTextModule.evaluate (node:internal/vm/module:225:23)
    at VMScriptRunner.runAsModule (/Users/balupton/Projects/websites/astro-cfpages-esbuild-resolution-bug/node_modules/@miniflare/runner-vm/src/index.ts:40:18)
    at VMScriptRunner.run (/Users/balupton/Projects/websites/astro-cfpages-esbuild-resolution-bug/node_modules/@miniflare/runner-vm/src/index.ts:86:17)
    at Miniflare.#reload (/Users/balupton/Projects/websites/astro-cfpages-esbuild-resolution-bug/node_modules/@miniflare/core/src/index.ts:790:13)
    at Miniflare.getPlugins (/Users/balupton/Projects/websites/astro-cfpages-esbuild-resolution-bug/node_modules/@miniflare/core/src/index.ts:1033:5)
    at createServer (/Users/balupton/Projects/websites/astro-cfpages-esbuild-resolution-bug/node_modules/@miniflare/http-server/src/index.ts:362:19)
    at startServer (/Users/balupton/Projects/websites/astro-cfpages-esbuild-resolution-bug/node_modules/@miniflare/http-server/src/index.ts:469:18)
    at main (file:///Users/balupton/Projects/websites/astro-cfpages-esbuild-resolution-bug/node_modules/wrangler/miniflare-dist/index.mjs:6300:22)

/private/Users/balupton/Projects/websites/astro-cfpages-esbuild-resolution-bug/conditional-resolution-package/browser.mjs:2
	if (
 ^
ReferenceError: window is not defined
    at browser (/private/Users/balupton/Projects/websites/astro-cfpages-esbuild-resolution-bug/conditional-resolution-package/browser.mjs:2:2)
    at /private/Users/balupton/Projects/websites/astro-cfpages-esbuild-resolution-bug/functions/[[catchall]].tsx:3:16
    at SourceTextModule.evaluate (node:internal/vm/module:225:23)
    at VMScriptRunner.runAsModule (/Users/balupton/Projects/websites/astro-cfpages-esbuild-resolution-bug/node_modules/@miniflare/runner-vm/src/index.ts:40:18)
    at VMScriptRunner.run (/Users/balupton/Projects/websites/astro-cfpages-esbuild-resolution-bug/node_modules/@miniflare/runner-vm/src/index.ts:86:17)
    at Miniflare.#reload (/Users/balupton/Projects/websites/astro-cfpages-esbuild-resolution-bug/node_modules/@miniflare/core/src/index.ts:790:13)
    at Miniflare.getPlugins (/Users/balupton/Projects/websites/astro-cfpages-esbuild-resolution-bug/node_modules/@miniflare/core/src/index.ts:1033:5)
    at createServer (/Users/balupton/Projects/websites/astro-cfpages-esbuild-resolution-bug/node_modules/@miniflare/http-server/src/index.ts:362:19)
    at startServer (/Users/balupton/Projects/websites/astro-cfpages-esbuild-resolution-bug/node_modules/@miniflare/http-server/src/index.ts:469:18)
    at main (file:///Users/balupton/Projects/websites/astro-cfpages-esbuild-resolution-bug/node_modules/wrangler/miniflare-dist/index.mjs:6300:22)
Waiting for the debugger to disconnect...                           
```

Which is using:

```
  "exports": {
    "workerd": {
      "import": "./workerd.mjs",
      "require": "./workerd.cjs"
    },
    "node": {
      "import": "./node.mjs",
      "require": "./node.cjs"
    },
    "browser": {
      "import": "./browser.mjs",
      "require": "./browser.cjs"
    },
    "default": {
      "import": "./default.mjs",
      "require": "./default.cjs"
    },
    "import": "./default.mjs",
    "require": "./default.cjs"
  },
  "type": "module",
  "module": "default.mjs",
  "browser": "browser.mjs",
  "main": "default.cjs",
```

The only way to get it to correctly use the `workerd` import is to change it to:

```
  "exports": {
    "workerd": {
      "import": "./workerd.mjs",
      "require": "./workerd.cjs"
    },
    "node": {
      "import": "./node.mjs",
      "require": "./node.cjs"
    },
    "browser": {
      "import": "./browser.mjs",
      "require": "./browser.cjs"
    },
    "default": {
      "import": "./default.mjs",
      "require": "./default.cjs"
    },
    "import": "./default.mjs",
    "require": "./default.cjs"
  },
  "type": "module",
```

Which is a removal of these:

```
  "module": "default.mjs",
  "browser": "browser.mjs",
  "main": "default.cjs",
```

Which would drop support for things like browserify and older node versions - which @bevry has been supporting successfully for hundreds of packages (half a billion installs a month) for a very long time, by using [boundation](https://github.com/bevry/boundation) and [editions](https://editions.bevry.me) to ensure the correct environment always loads the best edition for it.

The solution is to prefer `exports` over the legacy fields, which is [what Node.js does](https://nodejs.org/api/packages.html). The ideal would be to support [editions](https://editions.bevry.me), however since @bevry's proposal and successful implementation in 2016, the industry has continued doing its own thing, so my hopes for wider adoption of Editions has been wishful thinking. The current behaviour (preferring legacy fields over `exports`) means the @bevry suite of packages do not function as intended for esbuild users, which is a significant impact, and having @bevry conform to the esbuild behaviour would have a far more significant negative impact as it would break our seamless support for legacy node and other bundlers.

Cross-posted at https://github.com/evanw/esbuild/issues/2952

**Comment by balupton** [comment]
I've setup a proof of failure report at:

https://github.com/balupton/astro-cfpages-esbuild-resolution-bug

```
> npx wrangler pages dev public/
🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/workers-sdk/issues/new/choose
▲ [WARNING] No compatibility_date was specified. Using today's date: 2023-02-26.

  Pass it in your terminal:
  --compatibility-date=2023-02-26
  See https://developers.cloudflare.com/workers/platform/compatibility-dates/ for more information.


Compiling worker to "/var/folders/3v/fjmy4fyx1p9c28v31vzm8j9r0000gn/T/functionsWorker-0.9144048000835572.mjs"...
✨ Compiled Worker successfully
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit                                                                                                                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Debugger listening on ws://127.0.0.1:49630/0e52fc7d-346d-4609-86ac-b31b48837569
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[pages:wrn] Service bindings are experimental. There may be breaking changes in the future.
[pages:err] ReferenceError: window is not defined
    at getStartOfWeekBrowser (/private/Users/balupton/Projects/websites/billing-astro/node_modules/start-of-week/edition-browsers/browser.js:5:12)
    at ../node_modules/daet/edition-es2019-esm/index.js (/private/Users/balupton/Projects/websites/billing-astro/node_modules/daet/edition-es2019-esm/index.js:3:21)
    at __init (/private/var/folders/3v/fjmy4fyx1p9c28v31vzm8j9r0000gn/T/tmp-3473-UNbe246odK1x/functionsWorker-0.9144048000835572.js:9:56)
    at ../source/util.ts (/private/Users/balupton/Projects/websites/billing-astro/source/util.ts:2:1)
    at __init (/private/var/folders/3v/fjmy4fyx1p9c28v31vzm8j9r0000gn/T/tmp-3473-UNbe246odK1x/functionsWorker-0.9144048000835572.js:9:56)
    at ../source/layouts/Billing.tsx (/private/Users/balupton/Projects/websites/billing-astro/source/layouts/Billing.tsx:2:1)
    at __init (/private/var/folders/3v/fjmy4fyx1p9c28v31vzm8j9r0000gn/T/tmp-3473-UNbe246odK1x/functionsWorker-0.9144048000835572.js:9:56)
    at ../source/pages/Invoice.tsx (/private/Users/balupton/Projects/websites/billing-astro/source/pages/Invoice.tsx:1:1)
    at __init (/private/var/folders/3v/fjmy4fyx1p9c28v31vzm8j9r0000gn/T/tmp-3473-UNbe246odK1x/functionsWorker-0.9144048000835572.js:9:56)
    at entity/[entityId]/invoice/[invoiceId]/index.tsx (/private/Users/balupton/Projects/websites/billing-astro/functions/entity/[entityId]/invoice/[invoiceId]/index.tsx:2:1)

/private/Users/balupton/Projects/websites/billing-astro/node_modules/start-of-week/edition-browsers/browser.js:5
language = window.navigator.language || '') {
           ^
ReferenceError: window is not defined
    at getStartOfWeekBrowser (/private/Users/balupton/Projects/websites/billing-astro/node_modules/start-of-week/edition-browsers/browser.js:5:12)
    at ../node_modules/daet/edition-es2019-esm/index.js (/private/Users/balupton/Projects/websites/billing-astro/node_modules/daet/edition-es2019-esm/index.js:3:21)
    at __init (/private/var/folders/3v/fjmy4fyx1p9c28v31vzm8j9r0000gn/T/tmp-3473-UNbe246odK1x/functionsWorker-0.9144048000835572.js:9:56)
    at ../source/util.ts (/private/Users/balupton/Projects/websites/billing-astro/source/util.ts:2:1)
    at __init (/private/var/folders/3v/fjmy4fyx1p9c28v31vzm8j9r0000gn/T/tmp-3473-UNbe246odK1x/functionsWorker-0.9144048000835572.js:9:56)
    at ../source/layouts/Billing.tsx (/private/Users/balupton/Projects/websites/billing-astro/source/layouts/Billing.tsx:2:1)
    at __init (/private/var/folders/3v/fjmy4fyx1p9c28v31vzm8j9r0000gn/T/tmp-3473-UNbe246odK1x/functionsWorker-0.9144048000835572.js:9:56)
    at ../source/pages/Invoice.tsx (/private/Users/balupton/Projects/websites/billing-astro/source/pages/Invoice.tsx:1:1)
    at __init (/private/var/folders/3v/fjmy4fyx1p9c28v31vzm8j9r0000gn/T/tmp-3473-UNbe246odK1x/functionsWorker-0.9144048000835572.js:9:56)
    at entity/[entityId]/invoice/[invoiceId]/index.tsx (/private/Users/balupton/Projects/websites/billing-astro/functions/entity/[entityId]/invoice/[invoiceId]/index.tsx:2:1)
Waiting for the debugger to disconnect...
^C⏎      
```

**Comment by balupton** [comment]
So the only thing that made it behave as expected was defaulting all of the

**Comment by penalosa** [comment]
Thanks for reporting this! Since we rely on `esbuild` for bundling, we depend on `esbuild`'s behaviour here. It looks like you've opened an issue on `esbuild` as well—feel free to re-open this once it's fixed in `esbuild`, and we can update Wrangler. I'll close this for now, since there's nothing we can do at this stage.
