### ISSUE TITLE
🐛 BUG: Error ENOENT when importing HTML file in TypeScript

### ISSUE THREAD

**Issue by aliuq** [cloudflare/workers-sdk#2818]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

v2.12.0

### What operating system are you using?

WSL

### Describe the Bug

I am trying to import an HTML file in TypeScript using the import statement. However, when I make changes to the imported file, I get an error message:

```bash
[mf:err] Error: ENOENT: no such file or directory, open '/tmp/tmp-18843-PYtBc7iWEw9Q/e12c608a3d0454f344174382174cd2390c978541-home.html'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at linker (/node_modules/.pnpm/@miniflare+runner-vm@2.12.1/node_modules/@miniflare/runner-vm/src/linker.ts:108:18)
    at ModuleWrap.<anonymous> (node:internal/vm/module:312:30)
    at SourceTextModule.<computed> (node:internal/vm/module:311:36)
    at SourceTextModule.link (node:internal/vm/module:197:22)
    at VMScriptRunner.runAsModule (/node_modules/.pnpm/@miniflare+runner-vm@2.12.1/node_modules/@miniflare/runner-vm/src/index.ts:39:18)
    at VMScriptRunner.run (/node_modules/.pnpm/@miniflare+runner-vm@2.12.1/node_modules/@miniflare/runner-vm/src/index.ts:86:28)
    at EventTarget.#reload (/node_modules/.pnpm/@miniflare+core@2.12.1/node_modules/@miniflare/core/src/index.ts:790:42)
    at EventTarget.getPlugins (/node_modules/.pnpm/@miniflare+core@2.12.1/node_modules/@miniflare/core/src/index.ts:1033:5)
```

The error goes away when I undo the changes I made. This seems to be an issue with the file system not recognizing the modified file.

Can anyone help me understand what is causing this error and how to fix it? Thank you in advance for your help!

**Comment by penalosa** [comment]
Thanks for reporting this! Would you be able to setup a reproduction repo that demonstrates the issue?

**Comment by aliuq** [comment]
@penalosa Please see [reproduction](https://stackblitz.com/edit/node-4whfas?file=src/index.ts)

**Comment by penalosa** [comment]
@aliuq I'm having some trouble getting Stackblitz to boot up, but just to double check, does this issue occur outside of Stackblitz? i.e. when you run Wrangler locally can you reproduce it?

**Comment by aliuq** [comment]
@penalosa I wrote a [repo](https://github.com/aliuq/test-cf-workers-aasets-change), please check it

**Comment by penalosa** [comment]
@aliuq Apologies for the delay here. It looks like this is a bug in Miniflare 2, so I'll transfer it over to that repo. In the meantime, using `wrangler dev --experimental-local` seems to fix your issue in the reproduction repository.
