### ISSUE TITLE
🐛 BUG: Adding miniflare to package.json breaks yarn install in CI

### ISSUE THREAD

**Issue by BillBrower-Shopify** [cloudflare/workers-sdk#2891]
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

2.10.0

### What operating system are you using?

Ubuntu (latest)

### Describe the Bug

Adding `"@miniflare/tre": "3.0.0-next.8",` our package.json produces the following error in our buildkite CI when `yarn --cwd . install --frozen-lockfile` is run:

```
[5/5] Building fresh packages...
--
  | error /app/node_modules/workerd: Command failed.
  | Exit code: 1
  | Command: node install.js
  | Arguments:
  | Directory: /app/node_modules/workerd
  | Output:
  | node:internal/errors:863
  | const err = new Error(message);
  | ^
  |  
  | Error: Command failed: /usr/local/bin/node /app/node_modules/workerd/bin/workerd --version
  | /app/node_modules/@cloudflare/workerd-linux-64/bin/workerd: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
  | node:child_process:910
  | throw err;
  | ^
  |  
  | Error: Command failed: /app/node_modules/@cloudflare/workerd-linux-64/bin/workerd --version
  | at checkExecSyncError (node:child_process:871:11)
  | at Object.execFileSync (node:child_process:907:15)
  | at Object.<anonymous> (/app/node_modules/workerd/bin/workerd:139:26)
  | at Module._compile (node:internal/modules/cjs/loader:1159:14)
  | at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
  | at Module.load (node:internal/modules/cjs/loader:1037:32)
  | at Module._load (node:internal/modules/cjs/loader:878:12)
  | at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
  | at node:internal/main/run_main_module:23:47 {
  | status: 127,
  | signal: null,
  | output: [ null, null, null ],
  | pid: 139,
  | stdout: null,
  | stderr: null
  | }
  |  
  | Node.js v18.12.0
  |  
  | at checkExecSyncError (node:child_process:871:11)
  | at Object.execFileSync (node:child_process:907:15)
  | at validateBinaryVersion (/app/node_modules/workerd/install.js:61:47)
  | at /app/node_modules/workerd/install.js:229:7 {
  | status: 1,
  | signal: null,
  | output: [
  | null,
  | Buffer(0) [Uint8Array] [],
  | Buffer(1017) [Uint8Array] [
  | 47,  97, 112, 112,  47, 110, 111, 100, 101,  95, 109, 111,
  | 100, 117, 108, 101, 115,  47,  64,  99, 108, 111, 117, 100,
  | 102, 108,  97, 114, 101,  47, 119, 111, 114, 107, 101, 114,
  | 100,  45, 108, 105, 110, 117, 120,  45,  54,  52,  47,  98,
  | 105, 110,  47, 119, 111, 114, 107, 101, 114, 100,  58,  32,
  | 101, 114, 114, 111, 114,  32, 119, 104, 105, 108, 101,  32,
  | 108, 111,  97, 100, 105, 110, 103,  32, 115, 104,  97, 114,
  | 101, 100,  32, 108, 105,  98, 114,  97, 114, 105, 101, 115,
  | 58,  32, 108, 105,
  | ... 917 more items
  | ]
  | ],
  | pid: 132,
  | stdout: Buffer(0) [Uint8Array] [],
  | stderr: Buffer(1017) [Uint8Array] [
  | 47,  97, 112, 112,  47, 110, 111, 100, 101,  95, 109, 111,
  | 100, 117, 108, 101, 115,  47,  64,  99, 108, 111, 117, 100,
  | 102, 108,  97, 114, 101,  47, 119, 111, 114, 107, 101, 114,
  | 100,  45, 108, 105, 110, 117, 120,  45,  54,  52,  47,  98,
  | 105, 110,  47, 119, 111, 114, 107, 101, 114, 100,  58,  32,
  | 101, 114, 114, 111, 114,  32, 119, 104, 105, 108, 101,  32,
  | 108, 111,  97, 100, 105, 110, 103,  32, 115, 104,  97, 114,
  | 101, 100,  32, 108, 105,  98, 114,  97, 114, 105, 101, 115,
  | 58,  32, 108, 105,
  | ... 917 more items
  | ]
  | }
```

The exact versions of the Cloudflare, wrangler, and miniflare dependencies are:

```
"@cloudflare/workerd-darwin-64@1.20230307.0":
  version "1.20230307.0"
  resolved "https://registry.yarnpkg.com/@cloudflare/workerd-darwin-64/-/workerd-darwin-64-1.20230307.0.tgz#98e8cbd282156c3a739216e3833b14c9ce688ab2"
  integrity sha512-XwGnnsyjRHYvdBTwSXiclwqJ0pESbxNzsB9SwVdPK/QpwqqO+fXPW+ZQPfAnC0reCnYOJ46XtRwFi8LyfOXUPA==

"@cloudflare/workerd-darwin-arm64@1.20230307.0":
  version "1.20230307.0"
  resolved "https://registry.yarnpkg.com/@cloudflare/workerd-darwin-arm64/-/workerd-darwin-arm64-1.20230307.0.tgz#2066729e22e4f33fb62bdcdabf73be9b068a9a49"
  integrity sha512-5j/oYWBaLjTHLibg4wygK27XlGtOpJWTyXNn9lHDpzzX+eCsF/D0Qf+bdaxZjBUs+fJ8hMuXvh0x3oxEfxPG8Q==

"@cloudflare/workerd-linux-64@1.20230307.0":
  version "1.20230307.0"
  resolved "https://registry.yarnpkg.com/@cloudflare/workerd-linux-64/-/workerd-linux-64-1.20230307.0.tgz#b08bb67d76c43c8b3878f55a6eb05465ac1964bf"
  integrity sha512-EFzOvvfdttnW4Cln1IbQnjSuBh+B1rcgIQoReWMR37S5peXNaicSKtVc7ReJH166+AL9vlUgQUoRFhUNkwkzYg==

"@cloudflare/workerd-linux-arm64@1.20230307.0":
  version "1.20230307.0"
  resolved "https://registry.yarnpkg.com/@cloudflare/workerd-linux-arm64/-/workerd-linux-arm64-1.20230307.0.tgz#e0491c8277cf3302893d103b7d6dc1cc4855ff3f"
  integrity sha512-I/HElcl69H/BVJ6Ab4wXY/ESSq0g2motZEV6vqhp/GGxD2a3Pa04qFvVjNWpLTlx1lC/vUOdNNC4pcsLpY0B5g==
  
"@miniflare/tre@3.0.0-next.8":
  version "3.0.0-next.8"
  resolved "https://registry.yarnpkg.com/@miniflare/tre/-/tre-3.0.0-next.8.tgz#705e988699e06a644f052ce6237f302280802ded"
  integrity sha512-ISrxERQTTanh8Sp1yuJCN0k+nFmuu1sOweCpCfSLDQ3Te4yJdrr1fp+OFuKbgzLn5eXK2NjxcQxP/J1eJfBIOQ==
  dependencies:
    acorn "^8.8.0"
    acorn-walk "^8.2.0"
    better-sqlite3 "^7.6.2"
    capnp-ts "^0.7.0"
    exit-hook "^2.2.1"
    get-port "^5.1.1"
    glob-to-regexp "^0.4.1"
    http-cache-semantics "^4.1.0"
    kleur "^4.1.5"
    source-map "^0.7.4"
    stoppable "^1.1.0"
    undici "^5.12.0"
    workerd "^1.20221111.5"
    ws "^8.11.0"
    youch "^3.2.2"
    zod "^3.18.0"

wrangler@2.10.0:
  version "2.10.0"
  resolved "https://registry.yarnpkg.com/wrangler/-/wrangler-2.10.0.tgz#14f19e2bee12236ce0bdcd83308a21a8788c0150"
  integrity sha512-h/N7IN5R7P2xWMdUgLbgoWbfrTRVp2wXzT5HTXVg0DPufDY7X3Vf3xX2RW7pt+JTvbUdpOSD0dVyRR4Fxluzog==
  dependencies:
    "@cloudflare/kv-asset-handler" "^0.2.0"
    "@esbuild-plugins/node-globals-polyfill" "^0.1.1"
    "@esbuild-plugins/node-modules-polyfill" "^0.1.4"
    "@miniflare/core" "2.12.0"
    "@miniflare/d1" "2.12.0"
    "@miniflare/durable-objects" "2.12.0"
    blake3-wasm "^2.1.5"
    chokidar "^3.5.3"
    esbuild "0.16.3"
    miniflare "2.12.0"
    nanoid "^3.3.3"
    path-to-regexp "^6.2.0"
    selfsigned "^2.0.1"
    source-map "^0.7.4"
    xxhash-wasm "^1.0.1"
  optionalDependencies:
    fsevents "~2.3.2"
```

**Comment by aroman** [comment]
same issue here

**Comment by penalosa** [comment]
Apologies for the delay here! We've since added some clarifying details to the docs for Wrangler—see https://developers.cloudflare.com/workers/wrangler/commands/#dev:
> When using wrangler dev, you need to satisfy workerd’s libc++1 runtime dependencies:
> 
> On Linux: libc++ (for example, the package libc++1 on Debian Bullseye).
> On macOS: The XCode command line tools, which can be installed with xcode-select --install.

I'm going to close this issue for now. If you're still running into issues feel free to comment with more details and we can investigate further
