### ISSUE TITLE
🐛 BUG: Response.clone() fails in wrangler 2.12.2

### ISSUE THREAD

**Issue by klaemo** [cloudflare/workers-sdk#2895]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.12.2

### What operating system are you using?

Mac

### Describe the Bug

I'm running a pages setup locally with `wrangler pages dev` and have some functions that interact with my API. At some point I `clone()` the response of my API in order to inspect its body, but later pass it on to the actual response of the function. This all used to work nicely up until now.

I updated wrangler from `2.9.1` to `2.12.2` and now I get the following error:

```
[wrangler] TypeError: Found invalid object in transferList
[wrangler]     at structuredClone (node:internal/structured_clone:23:17)
[wrangler]     at cloneBody (/Users/clemens/Projects/webapp/node_modules/@miniflare/core/node_modules/undici/lib/fetch/body.js:273:21)
[wrangler]     at cloneResponse (/Users/clemens/Projects/webapp/node_modules/@miniflare/core/node_modules/undici/lib/fetch/response.js:318:24)
[wrangler]     at Response.clone (/Users/clemens/Projects/webapp/node_modules/@miniflare/core/node_modules/undici/lib/fetch/response.js:258:28)
[wrangler]     at Response.clone (/Users/clemens/Projects/webapp/node_modules/@miniflare/core/src/standards/http.ts:647:38)
[wrangler]     at onRequest2 (/private/Users/clemens/Projects/webapp/functions/api/[[api]].ts:77:41)
[wrangler]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[wrangler]     at next (/private/Users/clemens/Projects/webapp/node_modules/wrangler/templates/pages-template-worker.ts:152:22)
[wrangler]     at errorHandler (/private/Users/clemens/Projects/webapp/functions/api/_middleware.ts:153:12)
[wrangler]     at next (/private/Users/clemens/Projects/webapp/node_modules/wrangler/templates/pages-template-worker.ts:152:22) {
[wrangler]   code: 'ERR_INVALID_TRANSFER_OBJECT'
[wrangler] }
```

This happens both with node `18.14.2` and node `18.15.0`.

**Comment by ImAndromeda** [comment]
Based on the information provided, the error seems to be related to the update of Wrangler from version 2.9.1 to 2.12.2. The error message suggests that there is an issue with the `transferList` parameter in the `structuredClone` function. The error occurs when cloning the response object.

To troubleshoot and fix this issue, I suggest the following steps:

Revert to the older version of Wrangler to see if the issue persists. You can do this by running the following command:

`npm install -g wrangler@2.9.1`

If the issue does not occur in the older version, it may be a regression in the newer version of Wrangler. (Needs input from CF)

Inspect the response object and make sure there are no non-transferable objects (e.g., DOM elements, functions, etc.) in the object before cloning it. If you find any non-transferable objects, remove them or convert them to a transferable format before cloning the response object.

In the meantime, you can continue using the older version of Wrangler (2.9.1) if it works for your project without causing any issues and wait for them to resolve or direct.

**Comment by klaemo** [comment]
@penalosa this has indeed been fixed. Either by v3 or sometime before. In any case I can't reproduce it anymore! 🎉
