### ISSUE TITLE
🐛 BUG: can't publish - /routes API endpoint returns workers.api.error.unknown 10013 

### ISSUE THREAD

**Issue by piotrcichosz** [cloudflare/workers-sdk#2899]
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

2.7.1

### What operating system are you using?

Mac

### Describe the Bug

I'm trying to migrate from wrangler1 to wrangler2

- uinstalled wrangler1 and installed wrangler2
- removed following keys from wrangler.toml:
  - type="webpack"
  - webpack_config = "webpack.config.js"
- added to wrangler.toml:
  - main = "src/index.ts"
  - routes to separate env sections

when I try: wrangler publish --env qa:

✘ [ERROR] A request to the Cloudflare API (/accounts/8cbd0e9549ea0e7bccd9b9993f8e58b1/workers/scripts/bifrost-new-qa/routes) failed.

  workers.api.error.unknown [code: 10013]

**Comment by StickeyTape** [comment]
I also ran into this problem today.  When running with DEBUG, it appears that wrangler was not referencing the environment blocks in wrangler.toml  ie [env.prdmrp] but rather looking for a file on the filesystem (.env.prdmrp)

`wrangler publish --env prdmrp`

2023-04-05T07:06:45.6475049Z Failed to load .env file ".env.prdmrp": Error: ENOENT: no such file or directory, open '.env.prdmrp'
2023-04-05T07:06:45.6476108Z     at Object.openSync (node:fs:601:3)
2023-04-05T07:06:45.6477181Z     at Object.readFileSync (node:fs:469:35)
2023-04-05T07:06:45.6477813Z     at tryLoadDotEnv (/home/vsts/work/r1/a/_cf-worker-pwa/node_modules/wrangler/wrangler-dist/cli.js:126038:72)
2023-04-05T07:06:45.6478405Z     at loadDotEnv (/home/vsts/work/r1/a/_cf-worker-pwa/node_modules/wrangler/wrangler-dist/cli.js:126049:12)
2023-04-05T07:06:45.6478979Z     at /home/vsts/work/r1/a/_cf-worker-pwa/node_modules/wrangler/wrangler-dist/cli.js:148455:20
2023-04-05T07:06:45.6479455Z     at /home/vsts/work/r1/a/_cf-worker-pwa/node_modules/wrangler/wrangler-dist/cli.js:134845:16
2023-04-05T07:06:45.6480213Z     at maybeAsyncResult (/home/vsts/work/r1/a/_cf-worker-pwa/node_modules/wrangler/wrangler-dist/cli.js:133092:44)
2023-04-05T07:06:45.6480697Z     at /home/vsts/work/r1/a/_cf-worker-pwa/node_modules/wrangler/wrangler-dist/cli.js:134844:14
2023-04-05T07:06:45.6481218Z     at /home/vsts/work/r1/a/_cf-worker-pwa/node_modules/wrangler/wrangler-dist/cli.js:133079:22
2023-04-05T07:06:45.6481907Z     at Array.reduce (<anonymous>) {
2023-04-05T07:06:45.6482070Z   errno: -2,
2023-04-05T07:06:45.6482348Z   syscall: 'open',
2023-04-05T07:06:45.6482489Z   code: 'ENOENT',
2023-04-05T07:06:45.6482629Z   path: '.env.prdmrp'
2023-04-05T07:06:45.6482746Z }

This results in eventually the routes reflected in the environment not being updated, as that is what is referenced in the environment specific blocks in our implementation.

[env.prdmrp]
routes = [
  "site1.example.com/*",
  "site2.example.com/*"
]

**Wrangler Version**: wrangler@2.13.0

For now 'temporarily' ignoring the updating of the route - as they are existing and does not need changing.  But soon it is going to become a problem if we need to start updating the existing routes. So will need to figure this one out.

**Comment by zbauman3** [comment]
I'm also running into this problem. Any progress?

My output is (`****` is removed content): 
```
cache miss, executing 25144db384d78e91
⛅️ wrangler 2.12.0 (update available 2.17.0)
---------------------------------------------
Your worker has access to the following bindings:
- Vars:
 - ENVIRONMENT: "staging"
Total Upload: 18.67 KiB / gzip: 4.05 KiB
Uploaded origin-splitter-staging (0.82 sec)

✘ [ERROR] A request to the Cloudflare API (/accounts/****/workers/scripts/****/routes) failed.

 workers.api.error.unknown [code: 10013]
 
 If you think this is a bug, please open an issue at: https://github.com/cloudflare/workers-sdk/issues/new/choose


ERROR: command finished with error: command (/home/runner/work/****/****/cloudflare/workers/origin-splitter) yarn run publish --env=staging exited (1)

command (/home/runner/work/****/****/cloudflare/workers/origin-splitter) yarn run publish --env=staging exited (1)
```

**Comment by TastefulElk** [comment]
I had the same error, and it ended up being the same culprit as for @zbauman3, a duplicate entry in the routes table. It had been this way for months and worked in Wrangler v1, but gave the puzzling `workers.api.error.unknown 10013` error in v2.

**Comment by oldshensheep** [comment]
I had this issue when I changed service name in the manage settings

**Comment by oldshensheep** [comment]
I found the true issue, I remove the line in the `wrangler.toml` and the error disappeared.
```
[placement]
mode = "smart"
```

**Comment by piotrcichosz** [comment]
for me what fixed the problem was regenerating token. Previous token worked in previous wrangler version, so it's kind of weird, but hey, works. maybe error messages could be more precise.
