### ISSUE TITLE
🐛 BUG: Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by pdmshrestha** [cloudflare/workers-sdk#2948]
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

2.13.0

### What operating system are you using?

MacOs

### Describe the Bug

I am trying to use `node-jose` package in my typescript worker. Everything seems to work locally but when I try to publish the changes with wrangle it throws `Uncought ReferenceError: global is not defined`

```
> cloudflare-worker@0.0.0 deploy
> wrangler publish

 ⛅️ wrangler 2.13.0 
--------------------
Total Upload: 1557.05 KiB / gzip: 273.26 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/<id>/workers/scripts/<worker>) failed.

  Uncaught ReferenceError: global is not defined
    at index.js:39952:7 in node_modules/node-jose/lib/index.js
    at index.js:15:50 in __require2
    at index.js:48105:32
   [code: 10021]

  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

```
// packaget.json
{
  "name": "cloudflare-worker",
  "version": "0.0.0",
  "devDependencies": {
    "@cloudflare/workers-types": "^4.20230307.0",
    "@types/node-jose": "^1.1.10",
    "wrangler": "2.13.0"
  },
  "private": true,
  "scripts": {
    "start": "wrangler dev --local",
    "deploy": "wrangler publish"
  },
  "dependencies": {
    "fast-xml-parser": "^4.1.3",
    "itty-router": "^3.0.11",
    "moment": "^2.29.4",
    "node-jose": "^2.2.0"
  }
}
```

```
// index.ts
import { JWK, JWS } from "node-jose";
const handler: ExportedHandler<Env> = {
  fetch: async (req) => {
    const jwks = await fetch(
      "https://firebaseappcheck.googleapis.com/v1beta/jwks",
      {
        headers: {
          "content-type": "application/json;charset=UTF-8",
        },
      }
    );
      const keystore = await JWK.asKeyStore(awaitjwks.json());
      ...
  },
};

export default handler;
```

**Comment by JacobMGEvans** [comment]
Hello 👋 , 
I appreciate the report, as an alternative we do have WebCrypto support. I will also raise this internally to see if there is something that can be support in our Node compatibility work. 

@irvinebroque

**Comment by pdmshrestha** [comment]
> 

The package is listed as supported node modules https://workers.cloudflare.com/works.

**Comment by penalosa** [comment]
Thanks for raising that! We'll update that page. In the meantime, our up to date documentation for nodejs compatibility is at https://developers.cloudflare.com/workers/runtime-apis/nodejs/

**Comment by amiller68** [comment]
Is there an update on this? I'm running into the exact same issue, but I don't see the documentation change on the referenced at https://workers.cloudflare.com/works and I can't get my code to build when following the instructions here: https://developers.cloudflare.com/workers/runtime-apis/nodejs/
I did
- Set the correct compat flag in wrangler.toml
- Called wrangler dev --experimental-local

I still get the following error on startup:

```
Delegating to locally-installed wrangler@2.20.0 over global wrangler@2.20.0...
Run `npx wrangler dev --experimental-local` to use the local version directly.

 ⛅️ wrangler 2.20.0 
--------------------
Using vars defined in .dev.vars
Your worker has access to the following bindings:
- Vars:
  - FIREBASE_PROJECT_ID: "(hidden)"
  - FIREBASE_CLIENT_EMAIL: "(hidden)"
  - FIREBASE_PRIVATE_KEY_ID: "(hidden)"
  - FIREBASE_PRIVATE_KEY: "(hidden)"
  - FIRESTORE_API_URL: "(hidden)"
[NPXI] @miniflare/tre not available locally. Attempting to use npx to install temporarily.
[NPXI] Installing... (npx --prefer-offline -y -p @miniflare/tre@3.0.0-next.13)
[NPXI] Installed into /Users/alexmiller/.npm/_npx/cd4aba8655b5922f/node_modules.
[NPXI] To skip this step in future, run: npm install --save-dev @miniflare/tre@3.0.0-next.13
[mf:wrn] The latest compatibility date supported by the installed Cloudflare Workers Runtime is "2023-05-12",
but you've requested "2023-05-15". Falling back to "2023-05-12"...
service core:user:auth: Uncaught ReferenceError: global is not defined
  at index.js:34199:7 in node_modules/node-jose/lib/index.js
  at index.js:18:50 in __require2
  at index.js:34376:32
✘ [ERROR] The Workers runtime failed to start. There is likely additional logging output above.
```

**Comment by pixobe** [comment]
May I know if you are able to fix this? am facing same issue.

**Comment by jroyal** [comment]
fwiw I was able to get this working by doing https://github.com/cloudflare/workers-sdk/issues/4256#issuecomment-1774217573
