### ISSUE TITLE
🐛 BUG: ENOENT in watch mode after updating the code

### ISSUE THREAD

**Issue by Emm** [cloudflare/workers-sdk#3010]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

0.0.15

### What operating system are you using?

Linux

### Describe the Bug

I have setup an example repository at https://github.com/Emm/cloudflare-worker - this is simply an up to date version of https://github.com/cloudflare/rustwasm-worker-template, with the project name set and `watch_dir` set.

1. Checkout the repository
2. Run `wrangler dev --local` and wait for the build to be done
3. Update `lib.rs` by changing the string emitted by `console.log` (or any other harmless change).
4. Wait for the rebuild
5. Notice there is an `ENOENT` error :x:

The error follows:

```
[08:11:32] on  master rustwasm-worker-template $ wrangler dev --local
 ⛅️ wrangler 2.13.0 (update available 2.14.0)
-------------------------------------------------------
Want to try out the next version of local mode using the open-source Workers runtime?
Switch out --local for --experimental-local and let us know what you think at https://discord.gg/cloudflaredev !
Running custom build: cargo install -q worker-build && worker-build --release
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
    Finished release [optimized] target(s) in 0.07s
[INFO]: ⬇️  Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: ✨   Done in 6.71s
[INFO]: 📦   Your wasm pkg is ready to publish at /home/emm/projects/rustwasm-worker-template/build.

  shim.mjs  14.7kb

⚡ Done in 7ms
⎔ Starting a local server...
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Debugger listening on ws://127.0.0.1:44763/d9459785-8c67-4695-8b9f-60c9e510e412
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[mf:inf] Worker reloaded! (465.72KiB)
[mf:inf] Listening on 0.0.0.0:33967
The file src/lib.rs changed, restarting build...
Running custom build: cargo install -q worker-build && worker-build --release
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
   Compiling project v0.1.0 (/home/emm/projects/rustwasm-worker-template)
⎔ Shutting down local server.
⎔ Starting a local server...
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Debugger listening on ws://127.0.0.1:44763/3e7a808a-7cc2-44a1-8293-afd554e6e511
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[mf:inf] Worker reloaded! (465.72KiB)
[mf:inf] Listening on 0.0.0.0:33967
[mf:inf] - http://127.0.0.1:33967
[mf:inf] - http://192.168.1.109:33967
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: ✨   Done in 4.58s
[INFO]: 📦   Your wasm pkg is ready to publish at /home/emm/projects/rustwasm-worker-template/build.

⎔ Shutting down local server.
⎔ Starting a local server...
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Debugger listening on ws://127.0.0.1:44763/c4a3bb20-fcfb-4376-9696-db7acfbae0dc
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[mf:err] Error: ENOENT: no such file or directory, open '/tmp/tmp-311847-Ct0WCy5UcdBK/e4efb396fef4874e5daa3f0d0dbb0c34fe627fb3-index.wasm'
    at Object.openSync (node:fs:600:3)
    at readFileSync (node:fs:468:35)
    at linker (/usr/local/lib/node_modules/wrangler/node_modules/@miniflare/runner-vm/src/linker.ts:108:18)
    at ModuleWrap.<anonymous> (node:internal/vm/module:315:30)
    at SourceTextModule.<computed> (node:internal/vm/module:314:36)
    at SourceTextModule.link (node:internal/vm/module:199:22)
    at VMScriptRunner.runAsModule (/usr/local/lib/node_modules/wrangler/node_modules/@miniflare/runner-vm/src/index.ts:39:18)
    at VMScriptRunner.run (/usr/local/lib/node_modules/wrangler/node_modules/@miniflare/runner-vm/src/index.ts:86:28)
    at Miniflare.#reload (/usr/local/lib/node_modules/wrangler/node_modules/@miniflare/core/src/index.ts:790:42)
    at Miniflare.getPlugins (/usr/local/lib/node_modules/wrangler/node_modules/@miniflare/core/src/index.ts:1033:5)
Error: ENOENT: no such file or directory, open '/tmp/tmp-311847-Ct0WCy5UcdBK/e4efb396fef4874e5daa3f0d0dbb0c34fe627fb3-index.wasm'
    at Object.openSync (node:fs:600:3)
    at readFileSync (node:fs:468:35)
    at linker (/usr/local/lib/node_modules/wrangler/node_modules/@miniflare/runner-vm/src/linker.ts:108:18)
    at ModuleWrap.<anonymous> (node:internal/vm/module:315:30)
    at SourceTextModule.<computed> (node:internal/vm/module:314:36)
    at SourceTextModule.link (node:internal/vm/module:199:22)
    at VMScriptRunner.runAsModule (/usr/local/lib/node_modules/wrangler/node_modules/@miniflare/runner-vm/src/index.ts:39:18)
    at VMScriptRunner.run (/usr/local/lib/node_modules/wrangler/node_modules/@miniflare/runner-vm/src/index.ts:86:28)
    at Miniflare.#reload (/usr/local/lib/node_modules/wrangler/node_modules/@miniflare/core/src/index.ts:790:42)
    at Miniflare.getPlugins (/usr/local/lib/node_modules/wrangler/node_modules/@miniflare/core/src/index.ts:1033:5)
Waiting for the debugger to disconnect...
```

**Comment by lypanov** [comment]
Seeing the same here running in a Github Cloudspace. Only work around seems to be to quit with x after every test and restart wranger dev. Far from a nice first experience.

**Comment by penalosa** [comment]
This should be solved by https://github.com/cloudflare/workers-sdk/pull/3547
