### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by dja** [cloudflare/workers-sdk#3125]
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

2.18.0

### What operating system are you using?

Mac

### Describe the Bug

Attempting to upload a worker with Wrangler using `compatibility_flags = ['nodejs_compat']` or command line `--compatibility-flags="nodejs_compat"` fails with this error message:

```
  Uncaught Error: Dynamic require of "node:events" is not supported
    at worker.js:13:11
    at worker.js:13348:28
    at worker.js:13631:3
   [code: 10021]
```

The package using `node:events` is this LaunchDarkly SDK: https://github.com/launchdarkly/js-core/tree/main/packages/sdk/cloudflare

**Comment by ra-lfaro** [comment]
Same exact issue for me as well using same package

**Comment by dcrodman** [comment]
Having the same issue with trying to use `import { Buffer } from "node:buffer";` per the [docs](https://developers.cloudflare.com/workers/runtime-apis/nodejs/):
```
service core:user:muxworker: Uncaught Error: Dynamic require of "node:buffer" is not supported
  at core:user:muxworker:14:11
  at core:user:muxworker:1749:28
  at core:user:muxworker:2897:3
```

This was with Wrangler version v.2.20.0 as well as v3.0.0. Also encountering this error with `wrangler dev`.

**Comment by ra-lfaro** [comment]
Anyone have any luck resolving this?

**Comment by petebacondarwin** [comment]
Right now, the only way to access these compatible libraries is by a static `import {Buffer} from "node:buffer";` statement or a dynamic `await import("node:Buffer")` expression. Not a `require()` I believe.
