### ISSUE TITLE
🐛 BUG: Nuxt app fails to deploy (Uncaught TypeError: Cannot read properties of undefined (reading 'split'))

### ISSUE THREAD

**Issue by Skmt3P** [cloudflare/workers-sdk#3144]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.19.0 

### What operating system are you using?

Linux

## Details
- When Github Actions runs `wrangler publish`, then it raise a error like logs.
- If I run `wrangler publish` on local environment, the same error happens.
- If I run same job on Github Actions, ` Error: Script startup exceeded CPU time limit.` error happens.

## Logs
```
⛅️ wrangler 2.19.0 
--------------------
Fetching list of already uploaded assets...
Building list of assets to upload...
 = // lots of files...
 = _nuxt/index.933568a5.909a4b7720.css (already uploaded _nuxt/index.933568a5.css)
   (truncating changed assets log, set `WRANGLER_LOG=debug` environment variable to see full diff)
Skipped uploading 201 existing assets.
↗️  Done syncing assets
Total Upload: 3563.43 KiB / gzip: 751.72 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/<accoundId>/workers/scripts/<pjName>) failed.

  Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at worker.js:5439:416
    at worker.js:52758:4
    at worker.js:52759:3
   [code: 10021]
```

## Information

CI: Github Actions / cloudflare/wrangler-action/2.0.0
Deploy to: Cloudflare workers
FW: Nuxt3 (SSR preset: cloudflare)
deps: 
```
  "dependencies": {
    "@gtm-support/vue-gtm": "^2.0.0",
    "@vee-validate/zod": "4.8.6",
    "camelcase-keys": "^8.0.2",
    "dayjs": "^1.11.6",
    "markdown-it": "^13.0.1",
    "ohmyfetch": "^0.4.21",
    "ress": "^5.0.2",
    "snakecase-keys": "^5.4.4",
    "swiper": "^9.2.3",
    "universal-cookie": "^4.0.4",
    "uuid": "^9.0.0",
    "vee-validate": "^4.8.6",
    "vue-advanced-cropper": "^2.8.8",
    "vue-scrollto": "^2.20.0",
    "vue3-toastify": "^0.1.5"
  },
  "devDependencies": {
    "@headlessui/vue": "^1.7.4",
    "@inkline/inkline": "^3.2.2",
    "@inkline/nuxt": "^3.1.4",
    "@intlify/unplugin-vue-i18n": "^0.10.0",
    "@intlify/vite-plugin-vue-i18n": "^7.0.0",
    "@intlify/vue-i18n-loader": "^4.2.0",
    "@nuxt/test-utils": "^3.3.2",
    "@nuxtjs/eslint-config-typescript": "^12.0.0",
    "@nuxtjs/i18n": "^8.0.0-beta.7",
    "@nuxtjs/supabase": "^0.3.5",
    "@playwright/test": "^1.28.0",
    "@testing-library/dom": "^9.0.0",
    "@testing-library/user-event": "^14.4.3",
    "@testing-library/vue": "^7.0.0",
    "@toast-ui/editor": "^3.2.2",
    "@types/markdown-it": "^12.2.3",
    "@types/node": "^18.16.0",
    "@types/uuid": "^9.0.0",
    "@types/webpack-env": "^1.18.0",
    "@typescript-eslint/eslint-plugin": "^5.57.1",
    "@typescript-eslint/parser": "^5.59.1",
    "@vee-validate/i18n": "^4.8.6",
    "@vite-pwa/nuxt": "^0.0.7",
    "@vitejs/plugin-vue": "^4.1.0",
    "@vitest/coverage-c8": "^0.29.7",
    "@vitest/ui": "^0.30.0",
    "@vue/runtime-dom": "^3.2.45",
    "@vue/test-utils": "^2.2.3",
    "@vue/tsconfig": "^0.1.3",
    "@vueuse/core": "^10.1.0",
    "@vueuse/nuxt": "^10.0.2",
    "c8": "^7.12.0",
    "cross-env": "^7.0.3",
    "css-loader": "^6.7.2",
    "eslint": "^8.39.0",
    "eslint-config-google": "^0.14.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-import-resolver-typescript": "^3.5.2",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-n": "^15.7.0",
    "eslint-plugin-nuxt": "^4.0.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-unicorn": "^46.0.0",
    "eslint-plugin-vue": "^9.10.0",
    "fs": "^0.0.1-security",
    "husky": "^4.3.8",
    "imagemin-gifsicle": "^7.0.0",
    "imagemin-keep-folder": "^5.3.2",
    "imagemin-mozjpeg": "^10.0.0",
    "imagemin-pngquant": "^9.0.2",
    "imagemin-svgo": "^10.0.1",
    "jsdom": "^21.1.0",
    "lint-staged": "^13.0.3",
    "markdown-it": "^13.0.1",
    "msw": "^1.1.0",
    "npm-run-all": "^4.1.5",
    "nuxt": "^3.4.3",
    "postcss-html": "^1.5.0",
    "prettier": "^2.8.7",
    "sass": "^1.59.3",
    "sass-loader": "^13.2.1",
    "scaffdog": "^2.4.0",
    "stylelint": "^14.15.0",
    "stylelint-config-prettier": "^9.0.4",
    "stylelint-config-recommended": "^9.0.0",
    "stylelint-config-sass-guidelines": "^10.0.0",
    "stylelint-order": "^6.0.3",
    "stylelint-rscss": "^0.4.0",
    "swiper": "^9.2.3",
    "timers": "^0.1.1",
    "ts-loader": "^9.4.1",
    "ts-node": "^10.9.1",
    "typescript": "5.0.4",
    "unplugin-auto-import": "^0.15.1",
    "vite": "^4.3.4",
    "vite-plugin-checker": "^0.5.6",
    "vite-plugin-eslint": "^1.8.1",
    "vite-plugin-yaml": "^1.0.5",
    "vite-svg-loader": "^4.0.0",
    "vitest": "^0.30.1",
    "vue": "^3.2.45",
    "vue-advanced-cropper": "^2.8.8",
    "vue-i18n": "^9.3.0-beta.17",
    "vue-loader": "^17.1.0",
    "vue-meta": "^3.0.0-alpha.10",
    "vue-tsc": "^1.3.4",
    "wrangler": "^2.19.0",
    "yaml-loader": "^0.8.0",
    "yarn-upgrade-all": "^0.7.1",
    "zod": "^3.19.1"
  },
```

**Comment by kevinrombout** [comment]
I am also running into the same issue here on my local machine.  Happens on `npx wrangler dev .output/server/index.mjs --site .output/public --local`

**Logs**
```
 ⛅️ wrangler 2.20.0 
--------------------
Want to try out the next version of local mode using the open-source Workers runtime?
Switch out --local for --experimental-local and let us know what you think at https://discord.gg/cloudflaredev !
⎔ Starting a local server...
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Debugger listening on ws://127.0.0.1:55698/75a19c6f-94c1-466c-bf32-1beacb629a76
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[mf:err] /private/var/folders/b2/4c8sqqhj2qq_7821m00qlvfr0000gn/T/tmp-47540-V55HsMhlPBX3/index.js:5394
    const Hs = requireFs(), { Readable: zs } = requireStream(), Gs = ue, { promisify: Ks } = Hn, Ys = qs, Js = Ks(Hs.readdir), Xs = Ks(Hs.stat), Qs = Ks(Hs.lstat), Zs = Ks(Hs.realpath), ei = "READDIRP_RECURSIVE_ERROR", ti = /* @__PURE__ */ new Set(["ENOENT", "EPERM", "EACCES", "ELOOP", ei]), ri = "files", ni = "directories", si = "files_directories", ii = "all", oi = [ri, ni, si, ii], [ai, ui] = w.versions.node.split(".").slice(0, 2).map((e2) => Number.parseInt(e2, 10)), ci = "win32" === w.platform && (ai > 10 || 10 === ai && ui >= 5), normalizeFilter = (e2) => {

TypeError: Cannot read properties of undefined (reading 'split')


    at .nuxt/dist/server/client.manifest.mjs:3922:12
    at /private/var/folders/b2/4c8sqqhj2qq_7821m00qlvfr0000gn/T/tmp-47540-V55HsMhlPBX3/index.js:28435:3
    at Script.runInContext (node:vm:141:12)
    at VMScriptRunner.runAsScript (/usr/local/lib/node_modules/wrangler/node_modules/@miniflare/runner-vm/src/index.ts:26:12)
    at VMScriptRunner.run (/usr/local/lib/node_modules/wrangler/node_modules/@miniflare/runner-vm/src/index.ts:88:12)
    at Miniflare.#reload (/usr/local/lib/node_modules/wrangler/node_modules/@miniflare/core/src/index.ts:790:42)
    at Miniflare.getPlugins (/usr/local/lib/node_modules/wrangler/node_modules/@miniflare/core/src/index.ts:1033:5)
    at createServer (/usr/local/lib/node_modules/wrangler/node_modules/@miniflare/http-server/src/index.ts:362:19)
    at startServer (/usr/local/lib/node_modules/wrangler/node_modules/@miniflare/http-server/src/index.ts:469:18)

**Comment by fairok** [comment]
I have the same problem. Logs:

`PS D:\Work\Dev\mx-ys-clientweb> wrangler dev .output/server/index.mjs --site .output/public --local
 ⛅️ wrangler 3.0.0
------------------
wrangler dev now uses local mode by default, powered by 🔥 Miniflare and 👷 workerd.
To run an edge preview session for your Worker, use wrangler dev --remote
▲ [WARNING] --local is no longer required and will be removed in a future version.

  `wrangler dev` now uses the local Cloudflare Workers runtime by default. 🎉


⎔ Starting local server...
service core:user:hello-world-icy-art-695a: Uncaught TypeError: Cannot read properties of undefined (reading 'split')
  at core:user:hello-world-icy-art-695a:5706:416
  at core:user:hello-world-icy-art-695a:45366:4
  at core:user:hello-world-icy-art-695a:45367:3
✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.


╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit                       │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯⎔ Shutting down local server...
PS D:\Work\Dev\mx-ys-clientweb> wrangler dev
 ⛅️ wrangler 3.0.0
------------------
wrangler dev now uses local mode by default, powered by 🔥 Miniflare and 👷 workerd.
To run an edge preview session for your Worker, use wrangler dev --remote
⎔ Starting local server...
service core:user:hello-world-icy-art-695a: Uncaught TypeError: Cannot read properties of undefined (reading 'split')
  at core:user:hello-world-icy-art-695a:5706:416
  at core:user:hello-world-icy-art-695a:45366:4
  at core:user:hello-world-icy-art-695a:45367:3
✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.


╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit                       │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯`

**Comment by Skmt3P** [comment]
When this problem is solved...

```typescript
 ⛅️ wrangler 3.0.1
------------------
wrangler dev now uses local mode by default, powered by 🔥 Miniflare and 👷 workerd.
To run an edge preview session for your Worker, use wrangler dev --remote
⎔ Starting local server...
service core:user:worker: Uncaught TypeError: Cannot read properties of undefined (reading 'split')
  at ivsvnonyb4d.js:4962:32
✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
```

**Comment by LeonardoRick** [comment]
I'm facing the same error on `wrangler 3.1.0` it's actually being pretty hard to deploy my first nuxt application :(

**Comment by 1bye** [comment]
The same issue in nitro preset `netlify-edge`

Netlify build logs:
```
12:12:37 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
12:11:22 PM: Netlify Build                                                 
12:11:22 PM: ────────────────────────────────────────────────────────────────
12:11:22 PM: ​
12:11:22 PM: ❯ Version
12:11:22 PM:   @netlify/build 29.20.11
12:11:22 PM: ​
12:11:22 PM: ❯ Flags
12:11:22 PM:   baseRelDir: true
12:11:22 PM:   buildId: 64f3183cf0d5a7658090026f
12:11:22 PM:   deployId: 64f3183cf0d5a76580900271
12:11:22 PM: ​
12:11:22 PM: ❯ Current directory
12:11:22 PM:   /opt/build/repo
12:11:22 PM: ​
12:11:22 PM: ❯ Config file
12:11:22 PM:   /opt/build/repo/netlify.toml
12:11:22 PM: ​
12:11:22 PM: ❯ Context
12:11:22 PM:   production
12:11:22 PM: ​
12:11:22 PM: Build command from Netlify app                                
12:11:22 PM: ────────────────────────────────────────────────────────────────
12:11:22 PM: ​
12:11:22 PM: $ npm run build
12:11:23 PM: > build
12:11:23 PM: > prisma generate && nuxt build
12:11:23 PM: Prisma schema loaded from prisma/schema.prisma
12:11:23 PM: ✔ Generated Prisma Client (v5.2.0) to ./node_modules/@prisma/client in 226ms
12:11:23 PM: Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
12:11:23 PM: ```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
12:11:23 PM: or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
12:11:23 PM: ```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
```
12:11:23 PM: See other ways of importing Prisma Client: http://pris.ly/d/importing-client
12:11:24 PM: [log] Nuxi 3.5.3
12:11:24 PM: [log] Nuxt 3.5.3 with Nitro 2.6.2
12:11:34 PM: [info] [nuxt:tailwindcss] Using default Tailwind CSS file
12:11:34 PM: [warn] Slow module `@nuxtjs/tailwindcss` took `9566.3ms` to setup.
12:11:34 PM: [warn] Slow module `@nuxthq/ui` took `9637.62ms` to setup.
12:11:35 PM: [info] Building client...
12:11:35 PM: [info] vite v4.3.9 building for production...
12:11:35 PM: [info] transforming...
12:11:47 PM: [info] ✓ 1140 modules transformed.
12:11:47 PM: [info] rendering chunks...
12:11:48 PM: [info] computing gzip size...
12:11:48 PM: [info] .nuxt/dist/client/manifest.json                        7.94 kB │ gzip:   1.00 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/Icon.6f5d80f8.css              0.07 kB │ gzip:   0.09 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/IconCSS.fe0874d9.css           0.26 kB │ gzip:   0.17 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/error-500.e798523c.css         2.02 kB │ gzip:   0.75 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/error-404.95c28eb4.css         3.70 kB │ gzip:   1.14 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/_uuid_.fc1b7233.css            6.28 kB │ gzip:   1.33 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/entry.d89df690.css           272.48 kB │ gzip:  33.16 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/auth.2084e8a3.js               0.19 kB │ gzip:   0.17 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/flow.c30151a4.js               0.20 kB │ gzip:   0.18 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/test.e3414086.js               0.21 kB │ gzip:   0.19 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/index.78bad546.js              0.23 kB │ gzip:   0.19 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/confirm.b81f8490.js            0.34 kB │ gzip:   0.27 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/logout.b6a4c02b.js             0.36 kB │ gzip:   0.27 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/login.2d0e7d27.js              0.64 kB │ gzip:   0.45 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/IconCSS.074960c7.js            0.81 kB │ gzip:   0.52 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/calculator.6a2107fa.js         0.83 kB │ gzip:   0.47 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/output.2687a26b.js             0.88 kB │ gzip:   0.50 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/if.91de9021.js                 0.99 kB │ gzip:   0.51 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/controller.314aaccb.js         1.00 kB │ gzip:   0.54 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/testnode.322e17ea.js           1.06 kB │ gzip:   0.53 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/error-component.866d4481.js    1.12 kB │ gzip:   0.61 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/chatgpt.ab3aadf1.js            1.17 kB │ gzip:   0.60 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/error-500.b884f94a.js          1.88 kB │ gzip:   0.99 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/error-404.8ed0a7fd.js          2.22 kB │ gzip:   1.15 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/Icon.28234626.js              21.19 kB │ gzip:   8.06 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/defineShortcuts.85b2a034.js   41.90 kB │ gzip:  14.05 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/dashboard.bbe449dc.js         60.91 kB │ gzip:  15.78 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/entry.f2a54b6a.js            331.89 kB │ gzip: 107.53 kB
12:11:48 PM: [info] .nuxt/dist/client/_nuxt/_uuid_.398a96fe.js           387.61 kB │ gzip: 123.12 kB
12:11:48 PM: [info] ✓ built in 12.38s
12:11:48 PM: [success] Client built in 12390ms
12:11:48 PM: [info] Building server...
12:11:48 PM: [info] vite v4.3.9 building SSR bundle for production...
12:11:48 PM: [info] transforming...
12:12:00 PM: [info] ✓ 340 modules transformed.
12:12:00 PM: [info] rendering chunks...
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/Icon-styles.946700ba.mjs              0.08 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/IconCSS-styles.e02ff92e.mjs           0.08 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/error-404-styles.d2a508fc.mjs         0.08 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/error-500-styles.0aab1d62.mjs         0.08 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/FlowContainer.vue.87c7fb75.vue        0.14 kB
12:12:00 PM: [info] .nuxt/dist/server/styles.mjs                                  0.75 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/Icon-styles-1.mjs-a085ffd6.js         0.26 kB │ map:   0.11 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/IconCSS-styles-1.mjs-54a74734.js      0.46 kB │ map:   0.11 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/css-styles-2.mjs-638cff50.js          0.56 kB │ map:   0.11 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/test-4046bbef.js                      0.68 kB │ map:   0.11 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/auth-e9454824.js                      0.85 kB │ map:   0.55 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/island-renderer-f4974276.js           1.21 kB │ map:   1.39 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/flow-59da9310.js                      1.29 kB │ map:   0.14 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/confirm-062bada8.js                   1.36 kB │ map:   0.62 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/index-2554c85e.js                     1.42 kB │ map:   0.38 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/logout-cfbefd37.js                    1.74 kB │ map:   0.51 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/error-component-8c5c4687.js           2.04 kB │ map:   2.71 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/error-500-styles-1.mjs-56d472fe.js    2.23 kB │ map:   0.12 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/IconCSS-ece810b6.js                   2.46 kB │ map:   2.00 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/error-dev-styles-1.mjs-8822fa55.js    2.59 kB │ map:   0.12 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/login-e5fc0f68.js                     2.63 kB │ map:   1.29 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/FlowContainer.vue-3fe2e270.js         3.04 kB │ map:   0.11 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/error-500-ef392db2.js                 3.18 kB │ map:   3.78 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/FlowContainer.vue-1c97c92c.js         3.51 kB │ map:   0.11 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/error-404-styles-1.mjs-0f11a32d.js    3.93 kB │ map:   0.12 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/error-404-1bd4674a.js                 4.03 kB │ map:   5.82 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/Icon-8ae1c936.js                      4.60 kB │ map:   3.70 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/index-d97a345e.js                    21.45 kB │ map: 269.26 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/dashboard-04493a23.js                27.52 kB │ map:  18.07 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/defineShortcuts-8273beaa.js          66.63 kB │ map: 127.36 kB
12:12:00 PM: [info] .nuxt/dist/server/server.mjs                                118.35 kB │ map: 213.02 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/css-styles-1.mjs-faa78de0.js        257.52 kB │ map:   0.11 kB
12:12:00 PM: [info] .nuxt/dist/server/_nuxt/_uuid_-8e314ff7.js                  335.38 kB │ map: 379.46 kB
12:12:00 PM: [info] ✓ built in 12.47s
12:12:00 PM: [success] Server built in 12483ms
12:12:00 PM: [success] [nitro] Generated public dist
12:12:00 PM: [info] [nitro] Building Nitro Server (preset: `netlify-edge`)
12:12:04 PM: node_modules/openai/core.mjs (2:3) The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
12:12:04 PM: node_modules/openai/core.mjs (2:11) The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
12:12:04 PM: node_modules/openai/core.mjs (16:3) The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
12:12:04 PM: node_modules/openai/core.mjs (16:11) The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
12:12:32 PM: [success] [nitro] Nitro server built
12:12:32 PM:   └─ .netlify/edge-functions/server/server.js (2.74 MB) (717 kB gzip)
12:12:32 PM: Σ Total size: 2.74 MB (717 kB gzip)
12:12:32 PM: ​
12:12:32 PM: (build.command completed in 1m 9.4s)
12:12:32 PM: ​
12:12:32 PM: Edge Functions bundling                                       
12:12:32 PM: ────────────────────────────────────────────────────────────────
12:12:32 PM: ​
12:12:32 PM: Packaging Edge Functions from .netlify/edge-functions directory:
12:12:32 PM:  - server
12:12:37 PM: TypeError: Cannot read properties of undefined (reading 'split')
12:12:37 PM:     at file:///opt/build/repo/.netlify/edge-functions/server/server.js:1:194335
12:12:37 PM: ​
12:12:37 PM: Bundling of edge function failed                              
12:12:37 PM: ────────────────────────────────────────────────────────────────
12:12:37 PM: ​
12:12:37 PM:   Error message
12:12:37 PM:   Could not load edge function at '/opt/build/repo/.netlify/edge-functions/server/server.js'. More on the Edge Functions API at https://ntl.fyi/edge-api.
12:12:37 PM: ​
12:12:37 PM:   Error location
12:12:37 PM:   While bundling edge function
12:12:37 PM: ​
12:12:37 PM:   Resolved config
12:12:37 PM:   build:
12:12:37 PM:     command: npm run build
12:12:37 PM:     commandOrigin: ui
12:12:37 PM:     environment:
12:12:37 PM:       - DATABASE_URL
12:12:37 PM:       - NODE_OPTIONS
12:12:37 PM:       - NUXT_OPENAI_API_KEY
12:12:37 PM:       - SUPABASE_KEY
12:12:37 PM:       - SUPABASE_URL
12:12:37 PM:     publish: /opt/build/repo/.nuxt/dist
12:12:37 PM:     publishOrigin: ui
12:12:37 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
12:12:37 PM: Failing build: Failed to build site
12:12:38 PM: Finished processing build request in 1m43.913s
```

**Comment by penalosa** [comment]
Nuxt apps should work in Cloudflare Workers both locally and when deployed. The steps at https://nitro.unjs.io/deploy/providers/cloudflare or https://developers.cloudflare.com/pages/framework-guides/deploy-a-nuxt-site/ should work for either Cloudflare Workers or Cloudflare Pages.

If you're still running into issues, would you be able to open a new issue with a sample repo that shows the problem?
