### ISSUE TITLE
🐛 BUG: "TypeError: fetch failed" when trying to deploy

### ISSUE THREAD

**Issue by facu8990** [cloudflare/workers-sdk#3360]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.0.0

### What operating system are you using?

Debian

### Describe the Bug

Basically, I'm just trying to upload my recent changes on my worker. I have not done changes on my keys or development server certificates. Maybe I'm missing something out.
This is the complete output:
```
$ npm run deploy

> smiddleware@0.5.0 deploy
> wrangler deploy

 ⛅️ wrangler 3.0.0 (update available 3.0.1)
-----------------------------------------------------
✘ [ERROR] TypeError: fetch failed

      at fetch (/services/smiddleware/node_modules/wrangler/wrangler-dist/cli.js:16584:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async performApiFetch
  (/services/smiddleware/node_modules/wrangler/wrangler-dist/cli.js:120872:10)
      at async fetchInternal
  (/services/smiddleware/node_modules/wrangler/wrangler-dist/cli.js:120882:20)
      at async fetchResult
  (/services/smiddleware/node_modules/wrangler/wrangler-dist/cli.js:121025:16)
      at async deploy (/services/smiddleware/node_modules/wrangler/wrangler-dist/cli.js:147067:31)
      at async Object.deployHandler [as handler]
  (/services/smiddleware/node_modules/wrangler/wrangler-dist/cli.js:137713:3) {
    cause: Error: certificate is not yet valid
        at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34)
        at TLSSocket.emit (node:events:513:28)
        at TLSSocket._finishInit (node:_tls_wrap:959:8)
        at ssl.onhandshakedone (node:_tls_wrap:743:12) {
      code: 'CERT_NOT_YET_VALID'
    }
  }


Total Upload: 26.27 KiB / gzip: 5.23 KiB

✘ [ERROR] fetch failed


If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
```

"wrangler.toml":

```
name = "smiddleware"
main = "src/index.js"
compatibility_date = "2023-05-07"
account_id = "numbersnumbersnumbers"
workers_dev = true
```

**Comment by facu8990** [comment]
Date on my dev server was wrong. Pretty embarrassing. Closing issue.
