### ISSUE TITLE
🐛 BUG:　wrangler does not work on Debian 11 bullseye

### ISSUE THREAD

**Issue by gennai3** [cloudflare/workers-sdk#3429]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.1.0

### What operating system are you using?

Debian Linux 11 bullseye

### Describe the Bug

rpm run dev

 > hono-pages2@1.0.0 dev
> run-p dev:*

> hono-pages2@1.0.0 dev:esbuild
> rsync -avzh ./public ./dist --delete && esbuild --bundle src/server.ts --format=esm --watch --outfile=dist/_worker.js

sending incremental file list

> hono-pages2@1.0.0 dev:wrangler
> wrangler pages dev dist --live-reload

sent 361 bytes  received 20 bytes  762.00 bytes/sec
total size is 30.80K  speedup is 80.84
[watch] build finished, watching for changes...
🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/workers-sdk/issues/new/choose
▲ [WARNING] No compatibility_date was specified. Using today's date: 2023-06-11.

  Pass it in your terminal:
  ```
  --compatibility-date=2023-06-11
  ```
  See https://developers.cloudflare.com/workers/platform/compatibility-dates/ for more information.

✨ Compiled Worker successfully
 ⛅️ wrangler 3.1.0
------------------
wrangler dev now uses local mode by default, powered by 🔥 Miniflare and 👷 workerd.
To run an edge preview session for your Worker, use wrangler dev --remote
Your worker has access to the following bindings:
- KV Namespaces:
  - KVDATA: cb11f8f0XXXXXX
⎔ Starting local server...
[mf:wrn] The latest compatibility date supported by the installed Cloudflare Workers Runtime is "2023-05-18",
but you've requested "2023-06-11". Falling back to "2023-05-18"...
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [c] clear console, [x] to exit                                                                                           │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
/usr/lib/node_modules/wrangler/wrangler-dist/cli.js:30632
            throw a;
            ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:905:11)
    at Socket._write (node:net:917:8)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at Socket.Writable.write (node:internal/streams/writable:336:10)
    at Runtime.updateConfig (/usr/lib/node_modules/wrangler/node_modules/miniflare/dist/src/index.js:5121:26)
    at async Miniflare.#assembleAndUpdateConfig (/usr/lib/node_modules/wrangler/node_modules/miniflare/dist/src/index.js:9138:23)
    at async Miniflare.#init (/usr/lib/node_modules/wrangler/node_modules/miniflare/dist/src/index.js:8898:5)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
ERROR: "dev:wrangler" exited with 7.

**Comment by penalosa** [comment]
Closing in favour of https://github.com/cloudflare/workers-sdk/issues/3457
