### ISSUE TITLE
🐛 BUG: Wrangler install fails with missing Python error

### ISSUE THREAD

**Issue by Sammy-T** [cloudflare/workers-sdk#3449]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

n/a

### What operating system are you using?

Windows

### Describe the Bug

The [docs](https://developers.cloudflare.com/workers/wrangler/install-and-update/#install-wrangler) don't list python as a prerequisite for installing or using Wrangler. 

However, attempting to install via `npm install wrangler` fails with the following errors:
```
800 error code 1
801 error path C:\Users\Sammy\Desktop\alskdjf\node_modules\better-sqlite3
802 error command failed
803 error command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild --release
804 error prebuild-install warn install No prebuilt binaries found (target=19.4.0 runtime=node arch=x64 libc= platform=win32)
804 error gyp info it worked if it ends with ok
804 error gyp info using node-gyp@9.3.1
804 error gyp info using node@19.4.0 | win32 | x64
804 error gyp ERR! find Python 
804 error gyp ERR! find Python Python is not set from command line or npm configuration
804 error gyp ERR! find Python Python is not set from environment variable PYTHON
804 error gyp ERR! find Python checking if "python3" can be used
804 error gyp ERR! find Python - "python3" is not in PATH or produced an error
804 error gyp ERR! find Python checking if "python" can be used
804 error gyp ERR! find Python - "python" is not in PATH or produced an error
804 error gyp ERR! find Python checking if Python is C:\Users\Sammy\AppData\Local\Programs\Python\Python39\python.exe
804 error gyp ERR! find Python - "C:\Users\Sammy\AppData\Local\Programs\Python\Python39\python.exe" could not be run
804 error gyp ERR! find Python checking if Python is C:\Program Files\Python39\python.exe
804 error gyp ERR! find Python - "C:\Program Files\Python39\python.exe" could not be run
804 error gyp ERR! find Python checking if Python is C:\Users\Sammy\AppData\Local\Programs\Python\Python39-32\python.exe
804 error gyp ERR! find Python - "C:\Users\Sammy\AppData\Local\Programs\Python\Python39-32\python.exe" could not be run
804 error gyp ERR! find Python checking if Python is C:\Program Files\Python39-32\python.exe
804 error gyp ERR! find Python - "C:\Program Files\Python39-32\python.exe" could not be run
804 error gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python39-32\python.exe
804 error gyp ERR! find Python - "C:\Program Files (x86)\Python39-32\python.exe" could not be run
804 error gyp ERR! find Python checking if Python is C:\Users\Sammy\AppData\Local\Programs\Python\Python38\python.exe
804 error gyp ERR! find Python - "C:\Users\Sammy\AppData\Local\Programs\Python\Python38\python.exe" could not be run
804 error gyp ERR! find Python checking if Python is C:\Program Files\Python38\python.exe
804 error gyp ERR! find Python - "C:\Program Files\Python38\python.exe" could not be run
804 error gyp ERR! find Python checking if Python is C:\Users\Sammy\AppData\Local\Programs\Python\Python38-32\python.exe
804 error gyp ERR! find Python - "C:\Users\Sammy\AppData\Local\Programs\Python\Python38-32\python.exe" could not be run
804 error gyp ERR! find Python checking if Python is C:\Program Files\Python38-32\python.exe
804 error gyp ERR! find Python - "C:\Program Files\Python38-32\python.exe" could not be run
804 error gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python38-32\python.exe
804 error gyp ERR! find Python - "C:\Program Files (x86)\Python38-32\python.exe" could not be run
804 error gyp ERR! find Python checking if Python is C:\Users\Sammy\AppData\Local\Programs\Python\Python37\python.exe
804 error gyp ERR! find Python - "C:\Users\Sammy\AppData\Local\Programs\Python\Python37\python.exe" could not be run
804 error gyp ERR! find Python checking if Python is C:\Program Files\Python37\python.exe
804 error gyp ERR! find Python - "C:\Program Files\Python37\python.exe" could not be run
804 error gyp ERR! find Python checking if Python is C:\Users\Sammy\AppData\Local\Programs\Python\Python37-32\python.exe
804 error gyp ERR! find Python - "C:\Users\Sammy\AppData\Local\Programs\Python\Python37-32\python.exe" could not be run
804 error gyp ERR! find Python checking if Python is C:\Program Files\Python37-32\python.exe
804 error gyp ERR! find Python - "C:\Program Files\Python37-32\python.exe" could not be run
804 error gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python37-32\python.exe
804 error gyp ERR! find Python - "C:\Program Files (x86)\Python37-32\python.exe" could not be run
804 error gyp ERR! find Python checking if Python is C:\Users\Sammy\AppData\Local\Programs\Python\Python36\python.exe
804 error gyp ERR! find Python - "C:\Users\Sammy\AppData\Local\Programs\Python\Python36\python.exe" could not be run
804 error gyp ERR! find Python checking if Python is C:\Program Files\Python36\python.exe
804 error gyp ERR! find Python - "C:\Program Files\Python36\python.exe" could not be run
804 error gyp ERR! find Python checking if Python is C:\Users\Sammy\AppData\Local\Programs\Python\Python36-32\python.exe
804 error gyp ERR! find Python - "C:\Users\Sammy\AppData\Local\Programs\Python\Python36-32\python.exe" could not be run
804 error gyp ERR! find Python checking if Python is C:\Program Files\Python36-32\python.exe
804 error gyp ERR! find Python - "C:\Program Files\Python36-32\python.exe" could not be run
804 error gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python36-32\python.exe
804 error gyp ERR! find Python - "C:\Program Files (x86)\Python36-32\python.exe" could not be run
804 error gyp ERR! find Python checking if the py launcher can be used to find Python 3
804 error gyp ERR! find Python - "py.exe" is not in PATH or produced an error
804 error gyp ERR! find Python 
804 error gyp ERR! find Python **********************************************************
804 error gyp ERR! find Python You need to install the latest version of Python.
804 error gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
804 error gyp ERR! find Python you can try one of the following options:
804 error gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
804 error gyp ERR! find Python   (accepted by both node-gyp and npm)
804 error gyp ERR! find Python - Set the environment variable PYTHON
804 error gyp ERR! find Python - Set the npm configuration variable python:
804 error gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
804 error gyp ERR! find Python For more information consult the documentation at:
804 error gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
804 error gyp ERR! find Python **********************************************************
804 error gyp ERR! find Python 
804 error gyp ERR! configure error 
804 error gyp ERR! stack Error: Could not find any Python installation to use
804 error gyp ERR! stack     at PythonFinder.fail (C:\Users\Sammy\AppData\Roaming\nvm\v19.4.0\node_modules\npm\node_modules\node-gyp\lib\find-python.js:330:47)
804 error gyp ERR! stack     at PythonFinder.runChecks (C:\Users\Sammy\AppData\Roaming\nvm\v19.4.0\node_modules\npm\node_modules\node-gyp\lib\find-python.js:159:21)
804 error gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Sammy\AppData\Roaming\nvm\v19.4.0\node_modules\npm\node_modules\node-gyp\lib\find-python.js:228:18)
804 error gyp ERR! stack     at PythonFinder.execFileCallback (C:\Users\Sammy\AppData\Roaming\nvm\v19.4.0\node_modules\npm\node_modules\node-gyp\lib\find-python.js:294:16)
804 error gyp ERR! stack     at exithandler (node:child_process:427:5)
804 error gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)
804 error gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
804 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
804 error gyp ERR! stack     at onErrorNT (node:internal/child_process:483:16)
804 error gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
804 error gyp ERR! System Windows_NT 10.0.19045
804 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Sammy\\AppData\\Roaming\\nvm\\v19.4.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
804 error gyp ERR! cwd C:\Users\Sammy\Desktop\alskdjf\node_modules\better-sqlite3
804 error gyp ERR! node -v v19.4.0
804 error gyp ERR! node-gyp -v v9.3.1
804 error gyp ERR! not ok
```

If python is a requirement, the docs should be updated to reflect this.

**Comment by rozenmd** [comment]
Hey @Sammy-T, could you try with node 18? see https://github.com/cloudflare/workers-sdk/issues/3423

**Comment by Sammy-T** [comment]
Thanks for the suggestion. I switched to Node v18.16.0 and the install completed successfully.
