### ISSUE TITLE
🐛 BUG: wrangler deploy always fetch failed

### ISSUE THREAD

**Issue by mylovelycodes** [cloudflare/workers-sdk#3494]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.1.0

### What operating system are you using?

Mac

### Describe the Bug

wrangler seems down? can not run deploy and whoami command. always shows fetch failed.

# wrangler  whoami
 ⛅️ wrangler 3.1.0
------------------
Getting User settings...

✘ [ERROR] fetch failed

# wrangler deploy
 ⛅️ wrangler 3.1.0
------------------
✘ [ERROR] TypeError: fetch failed
```
      at fetch (/opt/homebrew/lib/node_modules/wrangler/wrangler-dist/cli.js:16584:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async performApiFetch
  (/opt/homebrew/lib/node_modules/wrangler/wrangler-dist/cli.js:120876:10)
      at async fetchInternal
  (/opt/homebrew/lib/node_modules/wrangler/wrangler-dist/cli.js:120886:20)
      at async fetchResult (/opt/homebrew/lib/node_modules/wrangler/wrangler-dist/cli.js:121029:16)
      at async deploy (/opt/homebrew/lib/node_modules/wrangler/wrangler-dist/cli.js:147215:31)
      at async Object.deployHandler [as handler]
  (/opt/homebrew/lib/node_modules/wrangler/wrangler-dist/cli.js:137798:3) {
    cause: ConnectTimeoutError: Connect Timeout Error
        at onConnectTimeout (/opt/homebrew/lib/node_modules/wrangler/wrangler-dist/cli.js:7185:29)
        at /opt/homebrew/lib/node_modules/wrangler/wrangler-dist/cli.js:7141:51
        at Immediate._onImmediate
  (/opt/homebrew/lib/node_modules/wrangler/wrangler-dist/cli.js:7173:13)
        at process.processImmediate (node:internal/timers:478:21) {
      code: 'UND_ERR_CONNECT_TIMEOUT'
    }
  }
```

**Comment by mylovelycodes** [comment]
it seems that https://api.cloudflare.com/ has been blocked in china.

**Comment by penalosa** [comment]
Unfortunately Wrangler requires access to the Cloudflare API, so if you're unable to access the Cloudflare API you won't be able to use Wrangler.
