### ISSUE TITLE
BUG:Svelte pages:dev don't work 

### ISSUE THREAD

**Issue by yzn-h** [cloudflare/workers-sdk#3510]
### Which Cloudflare product(s) does this pertain to?

C3

### What version of `Wrangler` are you using?

3.1.1

### What operating system are you using?

Linux

### Describe the Bug

when running pnpm run pages:dev I get this error
```bash
> wrangler pages dev --compatibility-date=6-22-2023 --proxy 5173 -- pnpm run dev

Running pnpm run dev...
No functions. Shimming...
 ⛅️ wrangler 3.1.1
------------------
wrangler dev now uses local mode by default, powered by 🔥 Miniflare and 👷 workerd.
To run an edge preview session for your Worker, use wrangler dev --remote
▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]

    tsconfig.json:2:12:
      2 │   "extends": "./.svelte-kit/tsconfig.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

⎔ Starting local server...
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [c] clear console, [x] to exit                                                 │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
/home/yzn/projects/SLDDS_template/node_modules/.pnpm/wrangler@3.1.1/node_modules/wrangler/wrangler-dist/cli.js:30632
            throw a;
            ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Runtime.updateConfig (/home/yzn/projects/SLDDS_template/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:5121:26)
    at async #assembleAndUpdateConfig (/home/yzn/projects/SLDDS_template/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:9138:23)
    at async #init (/home/yzn/projects/SLDDS_template/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:8898:5)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v18.16.0
 ELIFECYCLE  Command failed with exit code 7.

```

pnpm run dev works fine
pnpm run pages:deploy don't work the deployed site status is Failed

**Comment by yzn-h** [comment]
I tried npm it didn't work

**Comment by yzn-h** [comment]
oh when it is not just for svelte wrangler pages is broken :(
