### ISSUE TITLE
🐛 BUG: create cloudflare fails on better-sqlite3 (with python 3.12)

### ISSUE THREAD

**Issue by punkeel** [cloudflare/workers-sdk#3531]
### Which Cloudflare product(s) does this pertain to?

C3

### What version of `Wrangler` are you using?

latest, 2.0.10

### What operating system are you using?

Mac

### Describe the Bug

Creating a new project fails, see logs:

```
~/code/tmp ❯ npx create-cloudflare@latest

using create-cloudflare version 2.0.10

╭ Create an application with Cloudflare Step 1 of 3
│
╰ Where do you want to create your application? also used as application name
--quiet-snow-fc42
Directory `` already exists and is not empty. Please choose a new name.
~/code/tmp ❯ npx create-cloudflare@latest

using create-cloudflare version 2.0.10

╭ Create an application with Cloudflare Step 1 of 3
│
├ Where do you want to create your application?
│ dir aged-mountain-38c0
│
├ What type of application do you want to create?
│ type "Hello World" Worker
│
├ Do you want to use TypeScript?
│ typescript no
│
├ Copying files from "hello-world" template
│
├ Do you want to use git for version control?
│ git no
│
╰ Application created

╭ Installing dependencies Step 2 of 3
│
npm ERR! gyp info spawn args   '/Users/maxime/Library/Caches/node-gyp/20.0.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/maxime/Library/Caches/node-gyp/20.0.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/maxime/.nvm/versions/node/v20.0.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/maxime/Library/Caches/node-gyp/20.0.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/maxime/Code/tmp/aged-mountain-38c0/node_modules/better-sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/Users/maxime/.nvm/versions/node/v20.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E402
npm ERR!     ^^^^^^^^^^
npm ERR!   File "/Users/maxime/.nvm/versions/node/v20.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "/Users/maxime/.nvm/versions/node/v20.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/maxime/.nvm/versions/node/v20.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:511:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 22.5.0
npm ERR! gyp ERR! command "/Users/maxime/.nvm/versions/node/v20.0.0/bin/node" "/Users/maxime/.nvm/versions/node/v20.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.j
s" "rebuild" "--release"
npm ERR! gyp ERR! cwd /Users/maxime/Code/tmp/aged-mountain-38c0/node_modules/better-sqlite3
npm ERR! gyp ERR! node -v v20.0.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /Users/maxime/.npm/_logs/2023-06-27T22_11_05_665Z-debug-0.log

│
Error: npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm ERR! code 1
npm ERR! path /Users/maxime/Code/tmp/aged-mountain-38c0/node_modules/better-sqlite3
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild --release
npm ERR! prebuild-install warn install No prebuilt binaries found (target=20.0.0 runtime=node arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@20.0.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.12.0 found at "/Users/maxime/.nix-profile/bin/python3"
npm ERR! gyp info spawn /Users/maxime/.nix-profile/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/maxime/.nvm/versions/node/v20.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/maxime/Code/tmp/aged-mountain-38c0/node_modules/better-sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/maxime/.nvm/versions/node/v20.0.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/maxime/Library/Caches/node-gyp/20.0.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/maxime/Library/Caches/node-gyp/20.0.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/maxime/.nvm/versions/node/v20.0.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/maxime/Library/Caches/node-gyp/20.0.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/maxime/Code/tmp/aged-mountain-38c0/node_modules/better-sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/Users/maxime/.nvm/versions/node/v20.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E402
npm ERR!     ^^^^^^^^^^
npm ERR!   File "/Users/maxime/.nvm/versions/node/v20.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "/Users/maxime/.nvm/versions/node/v20.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/maxime/.nvm/versions/node/v20.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:511:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 22.5.0
npm ERR! gyp ERR! command "/Users/maxime/.nvm/versions/node/v20.0.0/bin/node" "/Users/maxime/.nvm/versions/node/v20.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd /Users/maxime/Code/tmp/aged-mountain-38c0/node_modules/better-sqlite3
npm ERR! gyp ERR! node -v v20.0.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /Users/maxime/.npm/_logs/2023-06-27T22_11_05_665Z-debug-0.log
```

This seems to be related to compiling better-sqlite3 (why do we compile sqlite to create a project 😬 )

**Comment by punkeel** [comment]
I suspect this is related: https://github.com/nodejs/node-gyp/issues/2869

**Comment by chrizy** [comment]
Hi getting  what I think is same error when creating a new project. npm install., wrangler  v3.2.0

```
npm ERR! path /Users/chris/Library/Mobile Documents/com~apple~CloudDocs/devunus/test/apis/node_modules/better-sqlite3
npm ERR! command failed
npm ERR! command sh -c -- prebuild-install || node-gyp rebuild --release
npm ERR! TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR!   ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR! rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR! prebuild-install warn install No prebuilt binaries found (target=18.12.1 runtime=node arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@18.12.1 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.9 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/chris/Library/Mobile Documents/com~apple~CloudDocs/devunus/test/apis/node_modules/better-sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/chris/Library/Caches/node-gyp/18.12.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/chris/Library/Caches/node-gyp/18.12.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/chris/Library/Caches/node-gyp/18.12.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/chris/Library/Mobile Documents/com~apple~CloudDocs/devunus/test/apis/node_modules/better-sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! /bin/sh: Documents/com~apple~CloudDocs/devunus/test/apis/node_modules/better-sqlite3/build/Release/lib.host:/Users/chris/Library/Mobile: No such file or directory
npm ERR! node:internal/fs/utils:348
npm ERR!     throw err;
npm ERR!     ^
npm ERR! 
npm ERR! Error: ENOENT: no such file or directory, copyfile '/Users/chris/Library/Mobile Documents/com~apple~CloudDocs/devunus/test/apis/node_modules/better-sqlite3/deps/sqlite3/sqlite3.c' -> '/Users/chris/Library/Mobile Documents/com~apple~CloudDocs/devunus/test/apis/node_modules/better-sqlite3/build/Release/obj/gen/sqlite3/sqlite3.c'
npm ERR!     at Object.copyFileSync (node:fs:2866:3)
npm ERR!     at Object.<anonymous> (/Users/chris/Library/Mobile Documents/com~apple~CloudDocs/devunus/test/apis/node_modules/better-sqlite3/deps/copy.js:25:5)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1159:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1037:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:878:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:23:47 {
npm ERR!   errno: -2,
npm ERR!   syscall: 'copyfile',
npm ERR!   code: 'ENOENT',
npm ERR!   path: '/Users/chris/Library/Mobile Documents/com~apple~CloudDocs/devunus/test/apis/node_modules/better-sqlite3/deps/sqlite3/sqlite3.c',
npm ERR!   dest: '/Users/chris/Library/Mobile Documents/com~apple~CloudDocs/devunus/test/apis/node_modules/better-sqlite3/build/Release/obj/gen/sqlite3/sqlite3.c'
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.12.1
npm ERR! make: *** [ba23eeee118cd63e16015df367567cb043fed872.intermediate] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 22.5.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd /Users/chris/Library/Mobile Documents/com~apple~CloudDocs/devunus/test/apis/node_modules/better-sqlite3
npm ERR! gyp ERR! node -v v18.12.1
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok
```

**Comment by admah** [comment]
I can't seem to replicate this with create-cloudflare's latest version (2.0.12) and node v18.12.1. 

@punkeel are you still running into this issue?

**Comment by punkeel** [comment]
The issue comes from Python 1.12 (beta 1), at least for me. Downgrading to Python 1.11 solved it 👍 

See https://github.com/cloudflare/workers-sdk/issues/3531#issuecomment-1610307712

**Comment by chrizy** [comment]
Hi, I don't have python installed. is it a requirement to install it in order to use Wranger v3.x?  v2 installs without issues.

**Comment by lrapoport-cf** [comment]
hi @chrizy ! we'll close this issue for now but please feel free to re-open if this is still an issue for you after installing python (see @mrbbot 's comment above).

**Comment by mrbm** [comment]
> Hi @lrapoport-cf Could we keep this open until Python 3.12 is supported (which requires updating gyp), or add pre built packages for better-sqlite3? That’s what this issue is originally about

Agreed, either this needs to stay open or documentation needs to change as environmental dependancies have changed.

**Comment by lrapoport-cf** [comment]
hi @punkeel and @mrbm , thanks for following up :) we are re-opening the ticket 👍 

the work that @mrbbot noted above i.e. to port Miniflare's simulators to run as Durable Objects in workerd, which would allow us to remove the better-sqlite3 dependency and thus Python as a requirement, is being tracked internally with ticket DEVX-779. 

documentation updates are in progress in https://github.com/cloudflare/cloudflare-docs/pull/10241.

**Comment by lrapoport-cf** [comment]
the dependency on better-sqlite3 has been removes as part of https://github.com/cloudflare/miniflare/pull/656, so this should now be resolved 👍

**Comment by punkeel** [comment]
Yay, thanks @mrbbot and @lrapoport-cf! c3 feels faster now, too! 🥳
