### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [cloudflare/workers-sdk#3533]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.1.1

### What operating system are you using?

manjaro linux

### Describe the Bug

If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
 ERROR  Command failed with exit code 1: wrangler pages publish ./dist

pnpm: Command failed with exit code 1: wrangler pages publish ./dist
    at makeError (/home/manjaro/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.5/node_modules/pnpm/dist/pnpm.cjs:24241:17)
    at handlePromise (/home/manjaro/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.5/node_modules/pnpm/dist/pnpm.cjs:24812:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/home/manjaro/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.5/node_modules/pnpm/dist/pnpm.cjs:220389:7)
    at async /home/manjaro/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.5/node_modules/pnpm/dist/pnpm.cjs:229795:21
    at async main (/home/manjaro/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.5/node_modules/pnpm/dist/pnpm.cjs:229762:34)
    at async runPnpm (/home/manjaro/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.5/node_modules/pnpm/dist/pnpm.cjs:230017:5)
    at async /home/manjaro/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.5/node_modules/pnpm/dist/pnpm.cjs:230009:7
❌ [wrangler] Failed with exit status 1

**Comment by JacobMGEvans** [comment]
Please provide more details of the issue you are running into, and a title. 

Any type of minimal reproduction can also allow us to help sooner and fix faster, thank you.

**Comment by penalosa** [comment]
We haven't heard from you in a while, so I'm going to close this issue for now. If you're still running into issues feel free to comment with more details and we can investigate further!
