### ISSUE TITLE
🐛 BUG: Wrangler - Failed to get worker definitions TypeError: fetch failed

### ISSUE THREAD

**Issue by jbmanning** [cloudflare/workers-sdk#3564]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.1.2

### What operating system are you using?

Mac

### Describe the Bug

Infrequently and inconsistently, when running `wrangler dev` I get spammed (hundreds of times) with this error. This seems to be the same issue which was resolved previously in #2959 . I was able to resolve the issue by killing all node processes on my machine, one of which seemed to be stuck and needed a force kill. 

```
[1] ▲ [WARNING] Failed to get worker definitions TypeError: fetch failed
[1] 
[1]       at fetch (/Users/josh/repos/projects/digester/node_modules/wrangler/wrangler-dist/cli.js:16584:17)
[1]       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]       at async getRegisteredWorkers (/Users/josh/repos/projects/digester/node_modules/wrangler/wrangler-dist/cli.js:126327:22)
[1]       at async getBoundRegisteredWorkers (/Users/josh/repos/projects/digester/node_modules/wrangler/wrangler-dist/cli.js:126346:29) {
[1]     cause: ConnectTimeoutError: Connect Timeout Error
[1]         at onConnectTimeout (/Users/josh/repos/projects/digester/node_modules/wrangler/wrangler-dist/cli.js:7185:29)
[1]         at /Users/josh/repos/projects/digester/node_modules/wrangler/wrangler-dist/cli.js:7141:51
[1]         at Immediate._onImmediate (/Users/josh/repos/projects/digester/node_modules/wrangler/wrangler-dist/cli.js:7173:13)
[1]         at process.processImmediate (node:internal/timers:476:21) {
[1]       code: 'UND_ERR_CONNECT_TIMEOUT'
[1]     }
[1]   }
```

**Comment by threepointone** [comment]
You should keep this open until the bug is actually fixed, unless it's being tracked elsewhere?
