### ISSUE TITLE
🐛 BUG: Fail early when env-wrapping middleware are used with service-worker syntax workers

### ISSUE THREAD

**Issue by geelen** [cloudflare/workers-sdk#3575]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.1.2

### What operating system are you using?

Mac

### Describe the Bug

Adding a D1 binding to a service-worker syntax Worker isn't supported, which I think is a general problem for all bindings involving middleware shims. I get the following error:

```
[mf:err] TypeError: head is not a function
    at __facade_invokeChain__ (/Users/glen/src/experiments/service-worker-syntax/node_modules/wrangler/templates/middleware/common.ts:53:9)
    at Object.next (/Users/glen/src/experiments/service-worker-syntax/node_modules/wrangler/templates/middleware/common.ts:50:11)
    at jsonError (/Users/glen/src/experiments/service-worker-syntax/node_modules/wrangler/templates/middleware/middleware-miniflare3-json-error.ts:22:30)
    at __facade_invokeChain__ (/Users/glen/src/experiments/service-worker-syntax/node_modules/wrangler/templates/middleware/common.ts:53:9)
    at __facade_invoke__ (/Users/glen/src/experiments/service-worker-syntax/node_modules/wrangler/templates/middleware/common.ts:63:9)
    at null.<anonymous> (/Users/glen/src/experiments/service-worker-syntax/node_modules/wrangler/templates/middleware/loader-sw.ts:209:3)
```

Although, saying that, this seems to be a service-worker-specific version of the middleware functionality?

The generated code's method looks like this, FYI:

```js
  function __facade_invokeChain__(request, env, ctx, dispatch, middlewareChain) {
    const [head, ...tail] = middlewareChain;
    const middlewareCtx = {
      dispatch,
      next(newRequest, newEnv) {
        return __facade_invokeChain__(newRequest, newEnv, ctx, dispatch, tail);
      }
    };
    return head(request, env, ctx, middlewareCtx);
  }
```

In any case, Wrangler should early-detect a service-worker syntax file and a D1 binding and explicitly reject them. Even if there's a way to fix the shim/middleware code and make it work, there's a new version of the binding coming that doesn't support service-worker syntax, so we may as well start explicitly rejecting it now.

**Comment by penalosa** [comment]
Service worker syntax workers don't support middleware that wrap the environment (like D1 and assets)—we should probably bail early in cases like that.

Separately, is D1 not going to support service worker syntax workers going forward?
