### ISSUE TITLE
🐛 BUG: Getting 1000 Auth error

### ISSUE THREAD

**Issue by amrita-pc** [cloudflare/workers-sdk#3605]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.2.0

### What operating system are you using?

Mac 13.4.1 (22F82)

### Describe the Bug

``` 
uname -a
Darwin CQGWXK77CN 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64
```

Hi,

Wrangler gives the following error when I try to push code to my account.
Additionally, wrangler whoami does not list my account. I have used wrangler whoami for two Super Admin emails, and neither of them show my account.
I also tried setting CLOUDFLARE_ACCOUNT_ID, there is no change in wrangler whoami / wrangler deploy.

```
% wrangler deploy index.mjs
 ⛅️ wrangler 3.2.0
------------------
✘ [ERROR] ParseError: A request to the Cloudflare API (/accounts/5b3d23f7aa124b3b0701c521a5ca9dc0/workers/services/turnstile-demo-workers) failed.
 
      at throwFetchError (/opt/homebrew/lib/node_modules/wrangler/wrangler-dist/cli.js:121134:17)
      at fetchResult (/opt/homebrew/lib/node_modules/wrangler/wrangler-dist/cli.js:121087:5)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async deploy (/opt/homebrew/lib/node_modules/wrangler/wrangler-dist/cli.js:147370:31)
      at async Object.deployHandler [as handler]
  (/opt/homebrew/lib/node_modules/wrangler/wrangler-dist/cli.js:137935:3) {
    text: 'A request to the Cloudflare API
  (/accounts/5b3d23f7aa124b3b0701c521a5ca9dc0/workers/services/turnstile-demo-workers) failed.',
    notes: [ { text: 'Authentication error [code: 10000]' } ],
    location: undefined,
    kind: 'error',
    code: 10000
  }
 
 
Total Upload: 6.49 KiB / gzip: 1.95 KiB
 
✘ [ERROR] A request to the Cloudflare API (/accounts/5b3d23f7aa124b3b0701c521a5ca9dc0/workers/scripts/turnstile-demo-workers) failed.
 
  Authentication error [code: 10000]
   
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

**Comment by amrita-pc** [comment]
The issue was that API Access was disabled globally for all members in the account.
https://developers.cloudflare.com/fundamentals/api/how-to/control-api-access/#:~:text=%E2%80%8B%E2%80%8B%20Account%2Dlevel%20access,and%20then%20update%20the%20setting.
