### ISSUE TITLE
🐛 BUG: repeatedly toggling local mode of wrangler dev leads to 'address in use' crash

### ISSUE THREAD

**Issue by mxschumacher** [cloudflare/workers-sdk#3640]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.3.0

### What version of Node are you using?

18.16.1

### What operating system are you using?

Linux (Fedora 38)

### Describe the Bug

When I launch a local dev server using "wrangler dev", I get the option to toggle the local mode on an off by hitting the 'l' (as in the first letter of the word "lion"). Doing so repeatedly crashes the dev server, probably because **going from remote to local mode does not properly shut down the previous instance of the dev server**. Using the wrangler version I have, the local mode is the default.

Steps to reproduce:
> npx wrangler dev src/index.js
hit the "l" (again, like the first letter of "lion") key three times in a row. 

Please see an example stack trace below

### Please provide any relevant error logs

```
/home/mxschumacher/code/cf-form/node_modules/wrangler/wrangler-dist/cli.js:30632
            throw a;
            ^

Error: listen EADDRINUSE: address already in use :::8976
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at Server.listen (node:net:1876:7)
    at /home/mxschumacher/code/cf-form/node_modules/wrangler/wrangler-dist/cli.js:120726:13
    at new Promise (<anonymous>)
    at login (/home/mxschumacher/code/cf-form/node_modules/wrangler/wrangler-dist/cli.js:120666:24)
    at async loginOrRefreshIfRequired (/home/mxschumacher/code/cf-form/node_modules/wrangler/wrangler-dist/cli.js:120638:43)
    at async requireLoggedIn (/home/mxschumacher/code/cf-form/node_modules/wrangler/wrangler-dist/cli.js:120982:20)
    at async performApiFetch (/home/mxschumacher/code/cf-form/node_modules/wrangler/wrangler-dist/cli.js:120908:3)
    at async fetchInternal (/home/mxschumacher/code/cf-form/node_modules/wrangler/wrangler-dist/cli.js:120935:20)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1767:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 8976
}

Node.js v18.16.1
```

**Comment by mxschumacher** [comment]
Hello @penalosa , no particular use case in mind, I simply think the tool should not crash within regular usage. I'm testing a few different edge cases to see how resilient the CLI is.

If repeated toggling is not intended behavior, then it should not be suggested by the permanent display explaining what the L button can be used for.

**Comment by RamIdeas** [comment]
I will ensure this is fixed with the current in-progress work to improve wrangler's dev servers

**Comment by penalosa** [comment]
This should have been fixed as a by-product of the `--x-dev-env` work. You should be able to run `wrangler dev --x-dev-env` (soon to be the default) and no longer run into this issue.
