### ISSUE TITLE
🐛 BUG:Wrangler SDK can't deploy workers

### ISSUE THREAD

**Issue by anyatibrian** [cloudflare/workers-sdk#3710]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.4.0

### What version of Node are you using?

v16.17.0

### What operating system are you using?

MacOS Ventura 

### Describe the Bug

Getting this error
````
Banyatis-MacBook-Pro:find-stream-chat-user banyati$ wrangler deploy
 ⛅️ wrangler 3.4.0
------------------
✘ [ERROR] ParseError: A request to the Cloudflare API (/accounts/96f8637892042b2b1c3cd1569ba7f2d9/workers/services/find-stream-chat-user) failed.

      at throwFetchError (/usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:121134:17)
      at fetchResult (/usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:121087:5)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async deploy (/usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:147720:31)
      at async Object.deployHandler [as handler]
  (/usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:138267:3) {
    text: 'A request to the Cloudflare API
  (/accounts/96f8637892042b2b1c3cd1569ba7f2d9/workers/services/find-stream-chat-user) failed.',
    notes: [ { text: 'Authentication error [code: 10000]' } ],
    location: undefined,
    kind: 'error',
    code: 10000
  }


Total Upload: 1.41 KiB / gzip: 0.62 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/96f8637892042b2b1c3cd1569ba7f2d9/workers/scripts/find-stream-chat-user) failed.

  Authentication error [code: 10000]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose`
```
whenever I deploy, tried setting up the CLOUDFLARE_API_TOKEN, CLOUDFLARE _API_KEY AND CLOUDFLARE API image. but still the above error

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

**Comment by 1000hz** [comment]
Try using the [`wrangler login`](https://developers.cloudflare.com/workers/wrangler/commands/#login) command if you're using wrangler on your local machine. The environment variable auth method is more useful when [running wrangler in CI/CD](https://developers.cloudflare.com/workers/wrangler/ci-cd/). Feel free to reopen if this doesn't solve your issue.
