### ISSUE TITLE
🐛 BUG: Local queue requests fail with Zod error

### ISSUE THREAD

**Issue by KrisBraun** [cloudflare/workers-sdk#3736]
### Which Cloudflare product(s) does this pertain to?

Queues, Wrangler core

### What version(s) of the tool(s) are you using?

3.5.0

### What version of Node are you using?

18.12.1

### What operating system are you using?

Mac

### Describe the Bug

Starting with wrangler 3.5.0, queue requests fail with this error:

```
ZodError: [
  {
    "received": "ok",
    "code": "invalid_enum_value",
    "options": [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8
    ],
    "path": [
      "outcome"
    ],
    "message": "Invalid enum value. Expected 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8, received 'ok'"
  }
]
    at get error [as error] (/Users/.../node_modules/.pnpm/zod@3.21.4/node_modules/zod/lib/types.js:43:31)
    at ZodObject.parse (/Users/.../node_modules/.pnpm/zod@3.21.4/node_modules/zod/lib/types.js:141:22)
    at #dispatchBatch (/Users/.../node_modules/.pnpm/miniflare@3.20230801.0/node_modules/miniflare/dist/src/index.js:7064:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async #flush [as _onTimeout] (/Users/.../node_modules/.pnpm/miniflare@3.20230801.0/node_modules/miniflare/dist/src/index.js:7073:18)
```

Looks like this was fixed in miniflare [v3.20230807.0](https://github.com/cloudflare/miniflare/releases/tag/v3.20230807.0).

**Comment by SupremeTechnopriest** [comment]
I'm hitting this as well.  Downgrading to `3.4.0` resolves it for now.

**Comment by colearendt** [comment]
Glad I'm not the only one. I was totally questioning my sanity here for a while.

**Comment by SupremeTechnopriest** [comment]
I think this is fixed on the latest.
