### ISSUE TITLE
🐛 BUG: `npm i -g wrangler` fail

### ISSUE THREAD

**Issue by kingsmanvn1112** [cloudflare/workers-sdk#3746]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

latest

### What version of Node are you using?

20.2.0

### What operating system are you using?

linux arm64

### Describe the Bug

I can't install wrangler cli on Termux (arm64, android 13)

### Please provide any relevant error logs

```
➜ npm i -g wrangler
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[##################] \ reify:@esbuild/android-arm64: ti
> better-sqlite3@8.5.0 install
> prebuild-install || node-gyp rebuild --release

prebuild-install warn install No prebuilt binaries found (target=20.2.0 runtime=node arch=arm64 libc= platform=android)
gyp info it worked if it ends with ok/android-arm64: ti
gyp info using node-gyp@9.3.1
gyp info using node@20.2.0 | android | arm64
gyp info find Python using Python version 3.11.4 found at "/data/data/com.termux/files/usr/bin/python3"
gyp info spawn /data/data/com.termux/files/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/wrangler/node_modules/better-sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/home/.cache/node-gyp/20.2.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/data/data/com.termux/files/home/.cache/node-gyp/20.2.0',
gyp info spawn args   '-Dnode_gyp_dir=/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/data/data/com.termux/files/home/.cache/node-gyp/20.2.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/data/data/com.termux/files/usr/lib/node_modules/wrangler/node_modules/better-sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make] - reify:@esbuild/android-arm64: ti
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/data/data/com.termux/files/usr/lib/node_modules/wrangler/node_modules/better-sqlite3/build'
  TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
  ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
  TOUCH Release/obj.target/deps/locate_sqlite3.stamp ti
  CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
rm -f Release/obj.target/deps/sqlite3.a Release/obj.target/deps/sqlite3.a.ar-file-list; mkdir -p `dirname Release/obj.target/deps/sqlite3.a`
ar crs Release/obj.target/deps/sqlite3.a @Release/obj.target/deps/sqlite3.a.ar-file-list
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
./src/objects/database.lzz:180:21: warning: variable 'status' set but not used [-Wunused-but-set-variable]
                int status = sqlite3_db_config(db_handle, SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION, 1, NULL);
                    ^
1 warning generated. - reify:@esbuild/android-arm64: ti
  SOLINK_MODULE(target) Release/obj.target/better_sqlite3.node
  COPY Release/better_sqlite3.nodeild/android-arm64: ti
  CC(target) Release/obj.target/test_extension/deps/test_extension.o
  SOLINK_MODULE(target) Release/obj.target/test_extension.node
  COPY Release/test_extension.nodeild/android-arm64: ti
rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
make: Leaving directory '/data/data/com.termux/files/usr/lib/node_modules/wrangler/node_modules/better-sqlite3/build'
gyp info ok
[##################] - reify:@esbuild/android-arm64: ti
> esbuild@0.16.3 postinstall
> node install.js

[##################] - reify:@esbuild/android-arm64: ti
> workerd@1.20230807.0 postinstall
> node install.js

/data/data/com.termux/files/usr/lib/node_modules/wrangler/node_modules/workerd/install.js:43
    throw new Error(`Unsupported platform: ${platformKey}`);
          ^

Error: Unsupported platform: android arm64 LE
    at pkgAndSubpathForCurrentPlatform (/data/data/com.termux/files/usr/lib/node_modules/wrangler/node_modules/workerd/install.js:43:11)
    at checkAndPreparePackage (/data/data/com.termux/files/usr/lib/node_modules/wrangler/node_modules/workerd/install.js:219:28)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/wrangler/node_modules/workerd/install.js:248:1)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.2.0
npm ERR! code 1
npm ERR! path /data/data/com.termux/files/usr/lib/node_modules/wrangler/node_modules/workerd
npm ERR! command failed
npm ERR! command sh -c node install.js

npm ERR! A complete log of this run can be found in: /data/data/com.termux/files/home/.npm/_logs/2023-08-12T11_06_04_667Z-debug-0.log
```

here is the full log file
[2023-08-12T11_06_04_667Z-debug-0.log](https://github.com/cloudflare/workers-sdk/files/12327250/2023-08-12T11_06_04_667Z-debug-0.log)

**Comment by monteeya** [comment]
Would it be possible to make workerd as an optional dependency for wrangler? That would make wrangler at least somewhat usable on Android until this is fixed.
