### ISSUE TITLE
🐛 BUG: `wrangler dev` fails with worker custom domain behind Access

### ISSUE THREAD

**Issue by kotx** [cloudflare/workers-sdk#3748]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.5.0

### What version of Node are you using?

18.17.1

### What operating system are you using?

Mac

### Describe the Bug

Put your workers custom domain behind cf access.

### Please provide any relevant error logs

/Users/kot/Code/aster/node_modules/.pnpm/wrangler@3.5.0/node_modules/wrangler/wrangler-dist/cli.js:30632
            throw a;
            ^

Error: WebSocket was closed before the connection was established
    at WebSocket2.close (/Users/kot/Code/aster/node_modules/.pnpm/wrangler@3.5.0/node_modules/wrangler/wrangler-dist/cli.js:108521:11)
    at close (/Users/kot/Code/aster/node_modules/.pnpm/wrangler@3.5.0/node_modules/wrangler/wrangler-dist/cli.js:127122:14)
    at /Users/kot/Code/aster/node_modules/.pnpm/wrangler@3.5.0/node_modules/wrangler/wrangler-dist/cli.js:127230:7
    at jh (/Users/kot/Code/aster/node_modules/.pnpm/wrangler@3.5.0/node_modules/wrangler/wrangler-dist/cli.js:29688:15)
    at exports2.unstable_runWithPriority (/Users/kot/Code/aster/node_modules/.pnpm/wrangler@3.5.0/node_modules/wrangler/wrangler-dist/cli.js:25660:16)
    at Pc (/Users/kot/Code/aster/node_modules/.pnpm/wrangler@3.5.0/node_modules/wrangler/wrangler-dist/cli.js:26308:16)
    at Qg (/Users/kot/Code/aster/node_modules/.pnpm/wrangler@3.5.0/node_modules/wrangler/wrangler-dist/cli.js:29651:18)
    at /Users/kot/Code/aster/node_modules/.pnpm/wrangler@3.5.0/node_modules/wrangler/wrangler-dist/cli.js:29640:13
    at V (/Users/kot/Code/aster/node_modules/.pnpm/wrangler@3.5.0/node_modules/wrangler/wrangler-dist/cli.js:25585:22)
    at Timeout.w [as _onTimeout] (/Users/kot/Code/aster/node_modules/.pnpm/wrangler@3.5.0/node_modules/wrangler/wrangler-dist/cli.js:25420:13)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/Users/kot/Code/aster/node_modules/.pnpm/wrangler@3.5.0/node_modules/wrangler/wrangler-dist/cli.js:108968:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.17.1
 ELIFECYCLE  Command failed with exit code 7.
 ELIFECYCLE  Command failed.
 ELIFECYCLE  Command failed.
ERROR: "worker:dev" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.

**Comment by lrapoport-cf** [comment]
hi @kotx ! thanks for flagging this. in an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last 6 months. if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include an updated summary and any additional context and we will review. thank you!
