### ISSUE TITLE
🐛 BUG: Expired JWT

### ISSUE THREAD

**Issue by PBhadoo** [cloudflare/workers-sdk#3773]
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler core

### What version(s) of the tool(s) are you using?

Wrangler 3.5.1

### What version of Node are you using?

18.16.0

### What operating system are you using?

Windows 10

### Describe the Bug

While uploading files, the JWT Token expires. Trying from last 6 months.

Similar to https://github.com/cloudflare/workers-sdk/issues/1194 but not same issue.

### Please provide any relevant error logs

`🌏  Uploading... (166/2249)

C:\Users\bhadoo\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:30632
            throw a;
            ^

FatalError: Failed to upload files. Please try again. Error: {"text":"Received a malformed response from the API","notes":[{"text":"Expired JWT"},{"text":"POST /pages/assets/upload -> 403 Forbidden"}],"kind":"error","name":"ParseError"})
    at C:\Users\bhadoo\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:141734:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (C:\Users\bhadoo\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:141340:26) {
  code: 1
}`

Wrangler 3.5.1

Can't refresh JWT Token. (happened after 10 minutes maybe?)

**Comment by PBhadoo** [comment]
https://github.com/cloudflare/workers-sdk/issues/1194#issuecomment-1680437968

will discuss here, hopefully some takes care of this.
