### ISSUE TITLE
🐛 BUG: Too many bulk operations already in progress. Please wait until one completes before retrying. [code: 10046]

### ISSUE THREAD

**Issue by PBhadoo** [cloudflare/workers-sdk#3789]
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler core

### What version(s) of the tool(s) are you using?

3.5.1

### What operating system are you using?

Windows

### Describe the Bug

Uploading 8000 files to Pages.

as 8000 fails in one shot.

so i am doing 100 files per deployment.

running a batch script.

after all done.

I run all 8000 at once, and it shows all uploaded already and publishes the site.

The problem happens this, there is no exception to retry in the code. it should auto retry and cloudflare should return flood wait time before retrying.
Too many bulk operations already in progress. Please wait until one completes before retrying.

### Please provide any relevant error logs

Too many bulk operations already in progress. Please wait until one completes before retrying. [code: 10046]

Happening again and again, while no other thing in progress.

**Comment by tao** [comment]
I have been running into the same issue and it happens randomly, but happening a lot more frequently at the moment.

```
2023-08-19T09:13:53.323049Z	Cloning repository...
...
2023-08-19T09:17:10.642583Z	▲  ○  (Static)     automatically rendered as static HTML (uses no initial props)
2023-08-19T09:17:15.266017Z	▲  Collected static files (public/, static/, .next/static): 22.502ms
2023-08-19T09:17:25.961951Z	▲  Build Completed in .vercel/output [3m]
2023-08-19T09:17:26.105751Z	⚡️ Completed `npx vercel build`.
2023-08-19T09:17:35.000559Z	
2023-08-19T09:17:35.001166Z	⚡️ Build Summary (@cloudflare/next-on-pages v1.5.0)
2023-08-19T09:17:35.001397Z	⚡️ 
2023-08-19T09:17:35.001561Z	⚡️ Edge Function Routes (22)
2023-08-19T09:17:35.001761Z	⚡️   ┌ /
2023-08-19T09:17:35.001959Z	⚡️   ├ /api/[locale]/[collection]/[year]/[slug]
...
2023-08-19T09:17:35.006015Z	⚡️   └ /translations
2023-08-19T09:17:35.006147Z	⚡️ 
2023-08-19T09:17:35.006275Z	⚡️ Other Static Assets (2477)
2023-08-19T09:17:35.006917Z	⚡️   └ ... 2473 more
2023-08-19T09:17:35.007053Z	
2023-08-19T09:17:35.007213Z	⚡️ Build log saved to '.vercel/output/static/_worker.js/nop-build-log.json'
2023-08-19T09:17:35.007352Z	⚡️ Generated '.vercel/output/static/_worker.js/index.js'.
2023-08-19T09:17:35.007481Z	⚡️ Build completed in 8.90s
2023-08-19T09:17:35.064327Z	Finished
2023-08-19T09:17:35.065038Z	Found _worker.js in output directory. Uploading.
2023-08-19T09:17:36.402671Z	Attaching additional modules:
...
2023-08-19T09:17:36.535325Z	✨ Compiled Worker successfully
2023-08-19T09:17:36.614224Z	Found _routes.json in output directory. Uploading.
2023-08-19T09:17:36.630441Z	Validating asset output directory
2023-08-19T09:17:37.800659Z	Deploying your site to Cloudflare's global network...
2023-08-19T09:17:40.346696Z	Parsed 1 valid header rule.
2023-08-19T09:17:59.894319Z	Uploading... (145/2477)
2023-08-19T09:18:10.213527Z	Uploading... (188/2477)
2023-08-19T09:18:12.553623Z	Uploading... (231/2477)
2023-08-19T09:18:14.771235Z	Uploading... (274/2477)
2023-08-19T09:18:21.458405Z	Uploading... (317/2477)
2023-08-19T09:18:22.963555Z	Uploading... (360/2477)
2023-08-19T09:18:26.031524Z	Uploading... (403/2477)
2023-08-19T09:18:32.786733Z	Uploading... (446/2477)
2023-08-19T09:18:33.957234Z	Uploading... (489/2477)
2023-08-19T09:18:37.025949Z	Uploading... (532/2477)
2023-08-19T09:18:44.161082Z	Uploading... (575/2477)
2023-08-19T09:18:45.157312Z	Uploading... (618/2477)
2023-08-19T09:18:51.910832Z	Uploading... (661/2477)
2023-08-19T09:18:56.84891Z	Uploading... (704/2477)
2023-08-19T09:18:58.908188Z	Uploading... (747/2477)
2023-08-19T09:19:03.365273Z	Uploading... (790/2477)
2023-08-19T09:19:05.933136Z	Uploading... (833/2477)
2023-08-19T09:19:09.547233Z	Uploading... (876/2477)
2023-08-19T09:19:13.612739Z	Uploading... (920/2477)
2023-08-19T09:19:14.600987Z	Uploading... (963/2477)
2023-08-19T09:19:16.407674Z	Uploading... (1007/2477)
2023-08-19T09:19:20.864926Z	Uploading... (1051/2477)
2023-08-19T09:19:21.821929Z	Uploading... (1095/2477)
2023-08-19T09:19:22.793301Z	Uploading... (1138/2477)
2023-08-19T09:19:26.980043Z	/opt/pages/build_tool/js/node_modules/wrangler/wrangler-dist/cli.js:30632
2023-08-19T09:19:26.980601Z	            throw a;
2023-08-19T09:19:26.980847Z	            ^
2023-08-19T09:19:26.981001Z	
2023-08-19T09:19:26.981516Z	FatalError: Failed to upload files. Please try again. Error: {"text":"A request to the Cloudflare API (/pages/assets/upload) failed.","notes":[{"text":"Too many bulk operations already in progress. Please wait until one completes before retrying. [code: 10046]"}],"kind":"error","name":"ParseError","code":10046})
2023-08-19T09:19:26.981859Z	    at /opt/pages/build_tool/js/node_modules/wrangler/wrangler-dist/cli.js:141298:13
2023-08-19T09:19:26.982078Z	    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-08-19T09:19:26.982283Z	    at async run (/opt/pages/build_tool/js/node_modules/wrangler/wrangler-dist/cli.js:140904:26) {
2023-08-19T09:19:26.982478Z	  code: 10046
2023-08-19T09:19:26.982684Z	}
2023-08-19T09:19:27.041817Z	Failed: upload process exited with code: 7
2023-08-19T09:19:28.057211Z	Failed: an internal error occurred
2023-08-19T09:19:28.057211Z	Error: Failed to publish assets. For support, join our Discord (https://discord.gg/cloudflaredev) or create a ticket and reference the deployment ID: 8e4075fb-2284-4bdc-a41c-53bcaf9bb818
```

In this example it failed after uploading 1138/2477 but it's totally random, the build before that was 240/2477. The one before that was 446/2477. Hitting the retry button usually works and it uploads correctly... but seems to fail when you push to git and it auto deploys.

**Comment by PBhadoo** [comment]
@nevikashah Any update. This happening too frequently. for alot of files, we can't just sit and retry again and again, it should retry itself.

**Comment by msbtrends** [comment]
happening me 3

**Comment by cmsparks** [comment]
We made a ratelimiting change on our side that should resolve this. Closing this out.
