### ISSUE TITLE
Can't get repo up and running

### ISSUE THREAD

**Issue by MichaelDeBoey** [cloudflare/workers-sdk#3831]
When cloning the repo locally and running `npm install`, I get the following error:

```sh
npm ERR! code 1
npm ERR! path [REDACTED]/workers-sdk/node_modules/turbo
npm ERR! command failed
npm ERR! command sh /var/folders/4y/732jyff15tx0j2g6vdczkdpm0000gn/T/postinstall-9d7fcb6a.sh
npm ERR! node:internal/errors:856
npm ERR!   const err = new Error(message);
npm ERR!               ^
npm ERR! 
npm ERR! Error: Command failed: node [REDACTED]/workers-sdk/node_modules/turbo/bin/turbo --version --skip-infer
npm ERR! [REDACTED]/workers-sdk/node_modules/turbo/bin/turbo:13
npm ERR!     throw e;
npm ERR!     ^
npm ERR! 
npm ERR! Error: Command failed: [REDACTED]/workers-sdk/node_modules/turbo-darwin-64/bin/turbo --version --skip-infer
npm ERR!     at checkExecSyncError (node:child_process:841:11)
npm ERR!     at Object.execFileSync (node:child_process:876:15)
npm ERR!     at Object.<anonymous> ([REDACTED]/workers-sdk/node_modules/turbo/bin/turbo:6:28)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1126:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1004:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:17:47 {
npm ERR!   status: null,
npm ERR!   signal: 'SIGKILL',
npm ERR!   output: [ null, null, null ],
npm ERR!   pid: 7144,
npm ERR!   stdout: null,
npm ERR!   stderr: null
npm ERR! }
npm ERR! 
npm ERR!     at checkExecSyncError (node:child_process:841:11)
npm ERR!     at Object.execFileSync (node:child_process:876:15)
npm ERR!     at validateBinaryVersion ([REDACTED]/workers-sdk/node_modules/turbo/install.js:26:6)
npm ERR!     at [REDACTED]/workers-sdk/node_modules/turbo/install.js:242:7 {
npm ERR!   status: 1,
npm ERR!   signal: null,
npm ERR!   output: [
npm ERR!     null,
npm ERR!     Buffer(0) [Uint8Array] [],
npm ERR!     Buffer(971) [Uint8Array] [
npm ERR!        47,  85, 115, 101, 114, 115,  47, 109, 105,  99, 104,  97,
npm ERR!       101, 108, 100, 101,  98, 111, 101, 121,  47,  68, 101, 118,
npm ERR!       101, 108, 111, 112, 101, 114,  47, 119, 111, 114, 107, 101,
npm ERR!       114, 115,  45, 115, 100, 107,  47, 110, 111, 100, 101,  95,
npm ERR!       109, 111, 100, 117, 108, 101, 115,  47, 116, 117, 114,  98,
npm ERR!       111,  47,  98, 105, 110,  47, 116, 117, 114,  98, 111,  58,
npm ERR!        49,  51,  10,  32,  32,  32,  32, 116, 104, 114, 111, 119,
npm ERR!        32, 101,  59,  10,  32,  32,  32,  32,  94,  10,  10,  69,
npm ERR!       114, 114, 111, 114,
npm ERR!       ... 871 more items
npm ERR!     ]
npm ERR!   ],
npm ERR!   pid: 7137,
npm ERR!   stdout: Buffer(0) [Uint8Array] [],
npm ERR!   stderr: Buffer(971) [Uint8Array] [
npm ERR!      47,  85, 115, 101, 114, 115,  47, 109, 105,  99, 104,  97,
npm ERR!     101, 108, 100, 101,  98, 111, 101, 121,  47,  68, 101, 118,
npm ERR!     101, 108, 111, 112, 101, 114,  47, 119, 111, 114, 107, 101,
npm ERR!     114, 115,  45, 115, 100, 107,  47, 110, 111, 100, 101,  95,
npm ERR!     109, 111, 100, 117, 108, 101, 115,  47, 116, 117, 114,  98,
npm ERR!     111,  47,  98, 105, 110,  47, 116, 117, 114,  98, 111,  58,
npm ERR!      49,  51,  10,  32,  32,  32,  32, 116, 104, 114, 111, 119,
npm ERR!      32, 101,  59,  10,  32,  32,  32,  32,  94,  10,  10,  69,
npm ERR!     114, 114, 111, 114,
npm ERR!     ... 871 more items
npm ERR!   ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2023-08-24T16_13_52_004Z-debug-0.log
```

**Comment by penalosa** [comment]
Couple questions to help with debugging here:
- What's your `node` version and `npm` version? 
- What OS and system architecture are you on? (looks like potentially macOS? Are you running npm in Rosetta?)

**Comment by MichaelDeBoey** [comment]
@penalosa
- macOS Ventura (Intel)
- Node v18.16.0
- npm v9.5.1

**Comment by MichaelDeBoey** [comment]
Just tried again with a clean install and everything just works now, so must be something temporarily on the Turbo side I guess 🤷‍♂️

**Comment by penalosa** [comment]
Glad it's working now!
