### ISSUE TITLE
🐛 BUG: websocket connection closed before connection established

### ISSUE THREAD

**Issue by mulchy** [cloudflare/workers-sdk#4229]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.13.2 [wrangler]

### What version of Node are you using?

v20.8.0

### What operating system are you using?

Mac

### Describe the Bug
1. Initialize project with create-cloudflare
2. Run `wrangler dev`

Expected: Dev server does not crash

Actual: 
```
❯ npx wrangler dev
 ⛅️ wrangler 3.13.2
-------------------
⎔ Starting local server...
[mf:inf] Ready on http://0.0.0.0:62093
[mf:inf] - http://127.0.0.1:62093
[mf:inf] - http://10.10.4.163:62093
Waiting for connection...
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit                                                                                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:29374
            throw a;
            ^

Error: WebSocket was closed before the connection was established
    at WebSocket2.close (/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:107657:18)
    at close (/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:127798:14)
    at /Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:127859:7
    at jh (/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:28430:15)
    at exports2.unstable_runWithPriority (/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:24402:16)
    at Pc (/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:25050:16)
    at Qg (/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:28393:18)
    at /Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:28382:13
    at V (/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:24327:22)
    at Timeout.w [as _onTimeout] (/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:24162:13)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:108144:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.8.0
```

**Comment by mulchy** [comment]
I had a space in my worker name.

```
name = "hello world"
main = "src/index.ts"
compatibility_date = "2023-10-16"
```
^ fails


```
name = "hello world"
main = "src/index.ts"
compatibility_date = "2023-10-16"
```

^ works

**Comment by mulchy** [comment]
Looks like this should be caught by the config validation based on this test https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/__tests__/configuration.test.ts#L1119, but it wasn't in my case.

**Comment by petebacondarwin** [comment]
We're adding better config validation to catch this user error.
