### ISSUE TITLE
🐛 BUG: R2 bindings fail with 500 in local unit tests

### ISSUE THREAD

**Issue by ianduvall** [cloudflare/workers-sdk#4247]
### Which Cloudflare product(s) does this pertain to?

R2

### What version(s) of the tool(s) are you using?

3.14.0 [Wrangler]

### What version of Node are you using?

18.17.1

### What operating system are you using?

Mac

### Describe the Bug

`env.MY_BUCKET.put` fails with 500 error in Jest tests when using `unstable_dev` but works if run locally with `wrangler dev`. The issue might be related to passing `request.body`'s `ReadableStream` to `put` but the types for `put` seem to accept `ReadableStream` so I'm not sure why that would be an issue.

Worker code:
```ts
export interface Env {
	MY_BUCKET: R2Bucket;
}

export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		const key = 'key';
		if (request.method === 'GET') {
			const result = await env.MY_BUCKET.get(key);
			if (!result) {
				return new Response('Not found', { status: 404 });
			}
			return new Response(result?.body, { status: 200 });
		} else if (request.method === 'PUT') {
			const value = request.body;
			const result = await env.MY_BUCKET.put(key, value);
			return new Response('Created', { status: 201 });
		}

		return new Response('Not found', { status: 404 });
	},
};
```

Test code:
```ts
import { type UnstableDevWorker, unstable_dev } from 'wrangler';

describe('worker', () => {
	let worker: UnstableDevWorker;
	beforeAll(async () => {
		worker = await unstable_dev('src/index.ts', {
			logLevel: 'debug',
			experimental: { disableExperimentalWarning: true },
		});
	});
	afterAll(async () => {
		await worker.stop();
	});

	const value = { foo: 'bar' };

	test('PUT request', async () => {
		const url = `http://${worker.address}:${worker.port}`;

		const response = await worker.fetch(url, {
			method: 'PUT',
			headers: {
				'Content-Type': 'application/json',
			},
			body: JSON.stringify(value),
		});

		expect(response.status).toBe(201);
	});
});
```

### Please provide a link to a minimal reproduction

https://github.com/ianduvall/summer-night-0356

### Please provide any relevant error logs

Jest test logs:
```
% npm run test       

> summer-night-0356@0.0.0 test
> jest

  console.debug
    Metrics dispatcher: Dispatching disabled - would have sent {"type":"event","name":"run dev (api)","properties":{"local":true}}.

      at Logger.doLog (node_modules/wrangler/wrangler-dist/cli.js:118590:28)

  console.debug
    Failed to load .env file "/Users/ianduvall/p/summer-night-0356/.dev.vars": Error: ENOENT: no such file or directory, open '/Users/ianduvall/p/summer-night-0356/.dev.vars'
        at Object.openSync (node:fs:603:3)
        at Object.readFileSync (node:fs:471:35)
        at tryLoadDotEnv (/Users/ianduvall/p/summer-night-0356/node_modules/wrangler/wrangler-dist/cli.js:124351:72)
        at loadDotEnv (/Users/ianduvall/p/summer-night-0356/node_modules/wrangler/wrangler-dist/cli.js:124360:12)
        at getVarsForDev (/Users/ianduvall/p/summer-night-0356/node_modules/wrangler/wrangler-dist/cli.js:151822:18)
        at getBindings (/Users/ianduvall/p/summer-night-0356/node_modules/wrangler/wrangler-dist/cli.js:152741:10)
        at getBindingsAndAssetPaths (/Users/ianduvall/p/summer-night-0356/node_modules/wrangler/wrangler-dist/cli.js:152698:20)
        at getDevServer (/Users/ianduvall/p/summer-night-0356/node_modules/wrangler/wrangler-dist/cli.js:152478:38)
        at startApiDev (/Users/ianduvall/p/summer-night-0356/node_modules/wrangler/wrangler-dist/cli.js:152542:27)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at unstable_dev (/Users/ianduvall/p/summer-night-0356/node_modules/wrangler/wrangler-dist/cli.js:152924:23)
        at Object.<anonymous> (/Users/ianduvall/p/summer-night-0356/tests/index.test.ts:6:12) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/Users/ianduvall/p/summer-night-0356/.dev.vars'
    }

      at Logger.doLog (node_modules/wrangler/wrangler-dist/cli.js:118590:28)

  console.log
    Your worker has access to the following bindings:
    - R2 Buckets:
      - MY_BUCKET: my-bucket

      at Logger.doLog (node_modules/wrangler/wrangler-dist/cli.js:118590:28)

  console.log
    disableDevRegistry:  false

      at Logger.doLog (node_modules/wrangler/wrangler-dist/cli.js:118590:28)

  console.log
    ⎔ Starting local server...

      at Logger.doLog (node_modules/wrangler/wrangler-dist/cli.js:118590:28)

  console.log
    [mf:inf] Ready on http://0.0.0.0:50774

      at WranglerLog.log (node_modules/miniflare/src/shared/log.ts:66:13)

  console.log
    [mf:inf] - http://127.0.0.1:50774

      at WranglerLog.log (node_modules/miniflare/src/shared/log.ts:66:13)

  console.log
    [mf:inf] - http://192.168.1.34:50774

      at WranglerLog.log (node_modules/miniflare/src/shared/log.ts:66:13)

  console.log
    [mf:inf] - http://192.168.227.2:50774

      at WranglerLog.log (node_modules/miniflare/src/shared/log.ts:66:13)

  console.log
    ⎔ Shutting down local server...

      at Logger.doLog (node_modules/wrangler/wrangler-dist/cli.js:118590:28)

 FAIL  tests/index.test.ts
  worker
    ✕ PUT request (38 ms)

  ● worker › PUT request

    expect(received).toBe(expected) // Object.is equality

    Expected: 201
    Received: 500

      26 |              });
      27 |
    > 28 |              expect(response.status).toBe(201);
         |                                      ^
      29 |      });
      30 | });
      31 |

      at Object.toBe (tests/index.test.ts:28:27)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.996 s, estimated 3 s
Ran all test suites.
  console.error
    workerd/util/symbolizer.c++:98: warning: Not symbolizing stack traces because $LLVM_SYMBOLIZER is not set. To symbolize stack traces, set $LLVM_SYMBOLIZER to the location of the llvm-symbolizer binary. When running tests under bazel, use `--test_env=LLVM_SYMBOLIZER=<path>`.

      at Interface.<anonymous> (node_modules/miniflare/src/runtime/index.ts:88:39)

  console.error
    workerd/io/io-context.c++:394: info: uncaught exception; exception = workerd/api/global-scope.c++:39: failed: jsg.TypeError: Can't read from request stream after response has been sent.

      at Interface.<anonymous> (node_modules/miniflare/src/runtime/index.ts:88:39)

  console.error
    stack: 10d5b8740 10dd31928

      at Interface.<anonymous> (node_modules/miniflare/src/runtime/index.ts:88:39)


  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "[mf:inf] PUT / 500 Internal Server Error (20ms)".

      at console.log (node_modules/@jest/console/build/CustomConsole.js:141:10)
      at WranglerLog.log (node_modules/miniflare/src/shared/log.ts:66:13)
      at WranglerLog.logWithLevel (node_modules/miniflare/src/shared/log.ts:72:12)
      at Server.#handleLoopback (node_modules/miniflare/src/index.ts:766:19)
```

**Comment by penalosa** [comment]
This looks like a duplicate of #6425, which I've passed on to the R2 team
