### ISSUE TITLE
🐛 BUG: MiniflareServer listen EACCES: permission denied 0.0.0.0:6284

### ISSUE THREAD

**Issue by simonsmh** [cloudflare/workers-sdk#4255]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.14.0 [Wrangler]

### What version of Node are you using?

20.8.0

### What operating system are you using?

Windows 11 23H2 22631.2428

### Describe the Bug

wrangler dev command crashing

### Please provide any relevant error logs

```
C:\Users\simon\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:29374
            throw a;
            ^

Error: listen EACCES: permission denied 0.0.0.0:6284
    at Server.setupListenHandle [as _listen2] (node:net:1855:21)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at C:\Users\simon\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:126866:15
    at new Promise (<anonymous>)
    at isPortAvailable (C:\Users\simon\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:126854:10)
    at startWorkerRegistry (C:\Users\simon\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:126872:13)
    at registerWorker (C:\Users\simon\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:126907:9)
    at maybeRegisterLocalWorker (C:\Users\simon\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:128664:10)
    at MiniflareServer.<anonymous> (C:\Users\simon\AppData\Roaming\npm\node_modules\wrangler\wrangler-dist\cli.js:128720:15) {
  code: 'EACCES',
  errno: -4092,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 6284
}
```

**Comment by penalosa** [comment]
Thanks for reporting this! This looks like Wrangler is failing to start up it's local dev registry. A couple of questions:
- Do you have another process listening on port `6284`?
- What's the output of running the following node script?
```js
const http = require('http');
 
const hostname = '0.0.0.0';
const port = 6284;
 
const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World');
});
 
server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```

**Comment by simonsmh** [comment]
> Thanks for reporting this! This looks like Wrangler is failing to start up it's local dev registry. A couple of questions:
> 
> * Do you have another process listening on port `6284`?
Nope.

> * What's the output of running the following node script?
```
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:6284
    at Server.setupListenHandle [as _listen2] (node:net:1855:21)
    at listenInCluster (node:net:1920:12)
    at doListen (node:net:2069:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1899:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EACCES',
  errno: -4092,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 6284
}
```

It seems like it's not a wrangler's bug though.
