### ISSUE TITLE
🐛 BUG: Undefined bug

### ISSUE THREAD

**Issue by creikey** [cloudflare/workers-sdk#4444]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

3.15.0

### What version of Node are you using?

v18.17.0

### What operating system are you using?

Windows 11

### Describe the Bug

Got this error:
```
C:\Users\camer\Documents\rpgpt>wrangler pages deployment list
Select a project:
C:\Users\camer\AppData\Roaming\nvm\v18.17.0\node_modules\wrangler\wrangler-dist\cli.js:29374
            throw a;
            ^

TypeError: Cannot read properties of undefined (reading 'value')
    at onSelect (C:\Users\camer\AppData\Roaming\nvm\v18.17.0\node_modules\wrangler\wrangler-dist\cli.js:140924:32)
    at C:\Users\camer\AppData\Roaming\nvm\v18.17.0\node_modules\wrangler\wrangler-dist\cli.js:109615:13
    at ReadStream.handleData (C:\Users\camer\AppData\Roaming\nvm\v18.17.0\node_modules\wrangler\wrangler-dist\cli.js:53843:13)
    at ReadStream.emit (node:events:526:35)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:293:11)
    at Readable.push (node:internal/streams/readable:234:10)
    at TTY.onStreamRead (node:internal/stream_base_commons:190:23)

Node.js v18.17.0
```

**Comment by penalosa** [comment]
Thanks for reporting this! Does this happen every time you run `wrangler pages deployment list`? Are you able to provide a reproduction repo?

**Comment by creikey** [comment]
> Thanks for reporting this! Does this happen every time you run `wrangler pages deployment list`? Are you able to provide a reproduction repo?

No it doesn't happen now that I have a page deployed. It's just a null reference bug for when you don't have any pages and you run this.

**Comment by lrapoport-cf** [comment]
hi @creikey , apologies for the delayed response on this. i've just run `wrangler pages deployment list` with wrangler v4.23.0 on a pages project that has not yet been deployed and i don't receive an error, so this appears to have been fixed. we will close this issue, but please feel free to open a new issue if this is still a problem for you.
