### ISSUE TITLE
🐛 BUG: `wrangler dev` errors requiring `.env` and `.dev.vars` files then just errors

### ISSUE THREAD

**Issue by xav-ie** [cloudflare/workers-sdk#4483]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

3.17.0

### What version of Node are you using?

18.18.0

### What operating system are you using?

Linux

### Describe the Bug

1. Create new worker "hello-world" project with `npm create cloudflare@latest`
2. Try to start it with `npm run dev` => It errors, but not clear 
3. Try again with `npx wranger --log-level debug dev` => now asking for .env => add it
4. Try to start again => now asking for `.dev.vars` => add it
5. Try to start again => Just errors, no message and nothing helpful in the log. (Could this be related to https://github.com/cloudflare/workers-sdk/issues/3447 ?)

I am on NixOS, so I think there is high chance it could be #3447 but idk. I am not sure what else to do at this point. Maybe this series of errors is recognizable?

Here is my shell session: 

```sh
~/Projects
❯ npm create cloudflare@latest

using create-cloudflare version 2.7.1

╭ Create an application with Cloudflare Step 1 of 3
│
├ In which directory do you want to create your application?
│ dir ./workertest
│
├ What type of application do you want to create?
│ type "Hello World" Worker
│
├ Do you want to use TypeScript?
│ yes typescript
│
├ Copying files from "hello-world" template
│
├ Retrieving current workerd compatibility date
│ compatibility date 2023-11-21
│
├ Do you want to use git for version control?
│ yes git
│
╰ Application created

╭ Installing dependencies Step 2 of 3
│
├ Installing dependencies
│ installed via `npm install`
│
├ Committing new files
│ git commit
│
╰ Dependencies Installed

╭ Deploy with Cloudflare Step 3 of 3
│
├ Do you want to deploy your application?
│ no deploy via `npm run deploy`
│
├  APPLICATION CREATED  Deploy your application with npm run deploy
│
│ Navigate to the new directory cd workertest
│ Run the development server npm run start
│ Deploy your application npm run deploy
│ Read the documentation https://developers.cloudflare.com/workers
│ Stuck? Join us at https://discord.gg/cloudflaredev
│
╰ See you again soon!

~/Projects took 36s
❯ cd workertest/
workertest on  master via  v18.18.0
❯ npm run dev

> workertest@0.0.0 dev
> wrangler dev

 ⛅ wrangler 3.17.0
-------------------
⎔ Starting local server...
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit                                                                                                                    │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
/home/x/Projects/workertest/node_modules/wrangler/wrangler-dist/cli.js:29374
            throw a;
            ^

Error: spawn /home/x/Projects/workertest/node_modules/@cloudflare/workerd-linux-64/bin/workerd ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/x/Projects/workertest/node_modules/@cloudflare/workerd-linux-64/bin/workerd',
  path: '/home/x/Projects/workertest/node_modules/@cloudflare/workerd-linux-64/bin/workerd',
  spawnargs: [
    'serve',
    '--binary',
    '--experimental',
    '--socket-addr=entry=*:8787',
    '--external-addr=loopback=localhost:34885',
    '--control-fd=3',
    '-',
    '--inspector-addr=localhost:40137'
  ]
}

Node.js v18.18.0
[ble: exit 7]
workertest on  master via  v18.18.0
❯ npx wrangler --log-level debug dev
 ⛅ wrangler 3.17.0
-------------------
Metrics dispatcher: Dispatching disabled - would have sent {"type":"event","name":"run dev","properties":{"local":true,"usesTypeScript":true}}.
Failed to load .env file "/home/x/Projects/workertest/.dev.vars": Error: ENOENT: no such file or directory, open '/home/x/Projects/workertest/.dev.vars'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at tryLoadDotEnv (/home/x/Projects/workertest/node_modules/wrangler/wrangler-dist/cli.js:122671:72)
    at loadDotEnv (/home/x/Projects/workertest/node_modules/wrangler/wrangler-dist/cli.js:122680:12)
    at getVarsForDev (/home/x/Projects/workertest/node_modules/wrangler/wrangler-dist/cli.js:150297:18)
    at getBindings (/home/x/Projects/workertest/node_modules/wrangler/wrangler-dist/cli.js:151219:10)
    at getBindingsAndAssetPaths (/home/x/Projects/workertest/node_modules/wrangler/wrangler-dist/cli.js:151176:20)
    at getDevReactElement (/home/x/Projects/workertest/node_modules/wrangler/wrangler-dist/cli.js:150840:40)
    at startDev (/home/x/Projects/workertest/node_modules/wrangler/wrangler-dist/cli.js:150903:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/x/Projects/workertest/.dev.vars'
}
⎔ Starting local server...
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit                                                                                                                    │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
/home/x/Projects/workertest/node_modules/wrangler/wrangler-dist/cli.js:29374
            throw a;
            ^

Error: spawn /home/x/Projects/workertest/node_modules/@cloudflare/workerd-linux-64/bin/workerd ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/x/Projects/workertest/node_modules/@cloudflare/workerd-linux-64/bin/workerd',
  path: '/home/x/Projects/workertest/node_modules/@cloudflare/workerd-linux-64/bin/workerd',
  spawnargs: [
    'serve',
    '--binary',
    '--experimental',
    '--socket-addr=entry=*:8787',
    '--external-addr=loopback=localhost:33953',
    '--control-fd=3',
    '-',
    '--inspector-addr=localhost:35229',
    '--verbose'
  ]
}

Node.js v18.18.0
[ble: exit 7]
workertest on  master via  v18.18.0
❯ touch .env
workertest on  master via  v18.18.0
❯ npx wrangler --log-level debug dev
🐛 Writing logs to ".wrangler/logs/wrangler-2023-11-22_07-46-44_159.log"
 ⛅ wrangler 3.17.0
-------------------
Metrics dispatcher: Dispatching disabled - would have sent {"type":"event","name":"run dev","properties":{"local":true,"usesTypeScript":true}}.
Failed to load .env file "/home/x/Projects/workertest/.dev.vars": Error: ENOENT: no such file or directory, open '/home/x/Projects/workertest/.dev.vars'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at tryLoadDotEnv (/home/x/Projects/workertest/node_modules/wrangler/wrangler-dist/cli.js:122671:72)
    at loadDotEnv (/home/x/Projects/workertest/node_modules/wrangler/wrangler-dist/cli.js:122680:12)
    at getVarsForDev (/home/x/Projects/workertest/node_modules/wrangler/wrangler-dist/cli.js:150297:18)
    at getBindings (/home/x/Projects/workertest/node_modules/wrangler/wrangler-dist/cli.js:151219:10)
    at getBindingsAndAssetPaths (/home/x/Projects/workertest/node_modules/wrangler/wrangler-dist/cli.js:151176:20)
    at getDevReactElement (/home/x/Projects/workertest/node_modules/wrangler/wrangler-dist/cli.js:150840:40)
    at startDev (/home/x/Projects/workertest/node_modules/wrangler/wrangler-dist/cli.js:150903:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/x/Projects/workertest/.dev.vars'
}
⎔ Starting local server...
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit                                                                                                                    │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
/home/x/Projects/workertest/node_modules/wrangler/wrangler-dist/cli.js:29374
            throw a;
            ^

Error: spawn /home/x/Projects/workertest/node_modules/@cloudflare/workerd-linux-64/bin/workerd ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/x/Projects/workertest/node_modules/@cloudflare/workerd-linux-64/bin/workerd',
  path: '/home/x/Projects/workertest/node_modules/@cloudflare/workerd-linux-64/bin/workerd',
  spawnargs: [
    'serve',
    '--binary',
    '--experimental',
    '--socket-addr=entry=*:8787',
    '--external-addr=loopback=localhost:37003',
    '--control-fd=3',
    '-',
    '--inspector-addr=localhost:42441',
    '--verbose'
  ]
}

Node.js v18.18.0
[ble: exit 7]
workertest on  master via  v18.18.0
❯ touch .dev.vars
workertest on  master via  v18.18.0
❯ npx wrangler --log-level debug dev
🐛 Writing logs to ".wrangler/logs/wrangler-2023-11-22_07-47-02_380.log"
 ⛅ wrangler 3.17.0
-------------------
Metrics dispatcher: Dispatching disabled - would have sent {"type":"event","name":"run dev","properties":{"local":true,"usesTypeScript":true}}.
Using vars defined in .dev.vars
⎔ Starting local server...
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit                                                                                                                    │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
/home/x/Projects/workertest/node_modules/wrangler/wrangler-dist/cli.js:29374
            throw a;
            ^

Error: spawn /home/x/Projects/workertest/node_modules/@cloudflare/workerd-linux-64/bin/workerd ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/x/Projects/workertest/node_modules/@cloudflare/workerd-linux-64/bin/workerd',
  path: '/home/x/Projects/workertest/node_modules/@cloudflare/workerd-linux-64/bin/workerd',
  spawnargs: [
    'serve',
    '--binary',
    '--experimental',
    '--socket-addr=entry=*:8787',
    '--external-addr=loopback=localhost:34265',
    '--control-fd=3',
    '-',
    '--inspector-addr=localhost:46561',
    '--verbose'
  ]
}

Node.js v18.18.0
[ble: exit 7]
workertest on  master via  v18.18.0
❯
```

### Please provide any relevant error logs

File: `.wrangler/logs/wrangler-2023-11-22_07-47-02_380.log`
```

--- 2023-11-22T07:47:02.469Z debug
🐛 Writing logs to ".wrangler/logs/wrangler-2023-11-22_07-47-02_380.log"
---

--- 2023-11-22T07:47:02.469Z log
 ⛅️ wrangler 3.17.0
[38;2;255;136;0m-------------------[39m
---

--- 2023-11-22T07:47:02.484Z debug
Metrics dispatcher: Dispatching disabled - would have sent {"type":"event","name":"run dev","properties":{"local":true,"usesTypeScript":true}}.
---

--- 2023-11-22T07:47:02.485Z log
Using vars defined in .dev.vars
---

--- 2023-11-22T07:47:02.523Z log
[2m⎔ Starting local server...[22m
---
```

**Comment by jonahbron** [comment]
I'm encountering this issue as well, also on NixOS (in my case, under WSL).  bin/workerd can't be executed even directly, it seems like maybe it's assuming some kind of global dependency is present.

**Comment by xav-ie** [comment]
So, it looks like this is a known issue for nix-os binaries from outside source like npm and others.  I am not 100% sure but some smarties on https://github.com/cloudflare/workerd/issues/1482, found some great workarounds:
1. `patchelf` the binary with a better loader. the lib64 loader makes nixos very unhappy. and results in the file not found error (in recent versions of NixOS the error is clearer and  says that it is not a FHS compliant binary)
See https://github.com/cloudflare/workerd/issues/1482#issuecomment-1868407587 for how to do patchelf method. This disadvantages of this are:
  -  you need a flake.nix if you don't happen to have `lib` version of the `lib64` library 
  - this needs to be patched for every update/npm install, which is slightly annoying
  
2. You can install through nixpkgs, which includes the patchelf in the install hook. Disadvantages:
- workerd now system-wide
- what if you want specific version? overlays are possible, but likely annoying.
- I think you also need to remove it from your package.json dependencies, which is just not desirable. 

3. -- I found this amazing SE post by "tobiasBora" explaining all the different ways you can overcome this:
https://unix.stackexchange.com/questions/522822/different-methods-to-run-a-non-nixos-executable-on-nixos
which includes good info on nix-ld/nix-alien, which I think is the method I want to try and use.
Also see these two:
- https://github.com/Mic92/nix-ld
- https://blog.thalheim.io/2022/12/31/nix-ld-a-clean-solution-for-issues-with-pre-compiled-executables-on-nixos/

If you would like to discuss more, please keep it in https://github.com/cloudflare/workerd/discussions/1515, this issue is now closed.

I am closing this issue as a duplicate of https://github.com/cloudflare/workers-sdk/issues/3447 , as getting that error is sufficient for nixos users to find out they need to patch the binary somehow. There is not much cloudflare can do for packaging here, I think. If they can, they say PR's/discussion is welcome :).

**Comment by benithors** [comment]
same thing as OP is describing is happening on windows :<

**Comment by d33p-dev** [comment]
> same thing as OP is describing is happening on windows :<

and is happening to me on mac M1

**Comment by xav-ie** [comment]
I see. Well if you are up for it, you can try this:
```sh
export LLV_SYMBOLIZER=$(command -v llvm-symbolizer)
```
This will give you far better traces and might give you an idea as to was is actually happening.

You do need to install llvm-symbolizer, first!

I found that doing this helped me fix another issue I was having where it was not resolving certificates correctly, but that's just a "nix thing" and probably not your issue.

`workerd/cloudflared` also sometimes does not say where the log is for some reason, so I recommend:
```sh
rm -rf ~/.wrangler/logs/*
```
Then checking there after you have set `LLV_SYMBOLIZER` and running your failing command for new logs. It should be far more detailed about what exactly is happening.


I would also try updating to latest packages if possible. You can check with `npm outdated`.
