### ISSUE TITLE
How to use `nodejs_compat` but still polyfill node internals that are not supported yet?

### ISSUE THREAD

**Issue by schettn** [cloudflare/workers-sdk#4489]
I'm running into a very similar issue, my workers depend on `async_hooks` for logging / instrumentation. I was experimenting with getting a direct PostgreSQL connection to work, instead of using a 'proxy' like Hasura, but indeed pg needs `node_compat` while asyncvery_hooks need `nodejs_compat`, and the project won't build. Are here any work arounds for this?

_Edit:_
@Cherry if your current use-case is using `pg`, an alternative that I found https://github.com/porsager/postgres, seems to be working just fine in `nodejs_compat` mode!

_Originally posted by @ItsWendell in https://github.com/cloudflare/workerd/issues/1856

**Comment by petebacondarwin** [comment]
We're working on a new way of getting Node.js compatibility which uses a combination of compile-time polyfills and runtime built-ins. With the latest Wrangler you could try this out by adding the `experimental:nodejs_compat_v2` and leave feedback for us to stabilize this.

**Comment by schettn** [comment]
@petebacondarwin 


When I use `experimental:nodejs_compat_v2` I cannot deploy when using `graphql-yoga`. `wrangler dev` works fine.

```ts
import {createYoga} from 'graphql-yoga'
console.log(createYoga)
```

Error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'getBuiltinModule')
    at null.<anonymous>
  (file:///Users/schettn/Documents/pylon/pylon-template/wrangler/node_modules/unenv/runtime/node/process/$cloudflare.mjs:168:60)
    at init_cloudflare (index.js:1:303)
    at null.<anonymous>
  (file:///Users/schettn/Documents/pylon/pylon-template/wrangler/node_modules/wrangler/_virtual_unenv_global_polyfill-process.js:2:9)
    at init_virtual_unenv_global_polyfill_process (index.js:1:303)
    at null.<anonymous>
  (file:///Users/schettn/Documents/pylon/pylon-template/wrangler/src/index.ts:1:1)
   [code: 10021]
```

**Comment by penalosa** [comment]
See https://developers.cloudflare.com/workers/runtime-apis/nodejs/, which should address this use case
