### ISSUE TITLE
🐛 BUG: Wrangler requests login on dry run due to `standardPricingWarning`

### ISSUE THREAD

**Issue by roshanr95** [cloudflare/workers-sdk#4723]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.22.3 [Wrangler]

### What version of Node are you using?

v18.16.0

### What operating system are you using?

Linux

### Describe the Bug

Wrangler asks for a login even when dry-run is specified. I traced the call to the `standardPricingWarning` function call here - https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/deploy/index.ts#L293

Commenting out the call fixes it (as a hack), ignoring it on dry runs would be helpful.

### Please provide any relevant error logs

Output from `console.trace()` inside the `login` method:
```
Trace
    at login (/node_modules/wrangler/wrangler-dist/cli.js:119073:11)
    at loginOrRefreshIfRequired (/node_modules/wrangler/wrangler-dist/cli.js:119058:49)
    at requireLoggedIn (/node_modules/wrangler/wrangler-dist/cli.js:119406:26)
    at performApiFetch (/node_modules/wrangler/wrangler-dist/cli.js:119331:9)
    at fetchInternal (/node_modules/wrangler/wrangler-dist/cli.js:119355:26)
    at fetchResult (/node_modules/wrangler/wrangler-dist/cli.js:119507:22)
    at standardPricingWarning (/node_modules/wrangler/wrangler-dist/cli.js:136869:40)
    at Object.deployHandler [as handler] (/node_modules/wrangler/wrangler-dist/cli.js:137073:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by petero-dk** [comment]
This is crazy annoying since we use the dryRun to do builds in a non authenticated environment, and such an easy fix! I just added a PR
