### ISSUE TITLE
🐛 BUG: Wrangler crashing when fetching an invalid DO instance by bad ID

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/workers-sdk#4745]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.22.4

### What version of Node are you using?

v18.13.0

### What operating system are you using?

macOS

### Describe the Bug

Not sure if relevant, but I'm using the `experimental` and `js_rpc` compat flags.

```ts
let formData: FormData;
try {
	formData = await request.formData();
} catch {
	return new Response(null, { status: 415 });
}
const email = formData.get("email");
console.log(email);
if (typeof email !== "string") {
	return new Response(null, { status: 400 });
}
const userId = env.USERS.idFromString(email);
const user = env.USERS.get(userId) as DurableObjectStub & User;
```

### Please provide any relevant error logs

```
[wrangler:err] TypeError: Invalid Durable Object ID: must be 64 hex digits
    at Object.fetch (file:///my-proj/example/src/index.ts:27:29)
    at async jsonError (file:///my-proj/node_modules/wrangler/templates/middleware/middleware-miniflare3-json-error.ts:22:10)

AssertionError [ERR_ASSERTION]: false == true
    at getSourceMappingPrepareStackTrace (/my-proj/node_modules/wrangler/wrangler-dist/cli.js:125558:35)
    at getSourceMappedString (/my-proj/node_modules/wrangler/wrangler-dist/cli.js:125592:24)
    at Socket.<anonymous> (/my-proj/node_modules/wrangler/wrangler-dist/cli.js:126415:19)
```

```
// cli.js#L125530-125561
function getSourceMappingPrepareStackTrace(retrieveSourceMap) {
  retrieveSourceMapOverride = retrieveSourceMap;
  if (sourceMappingPrepareStackTrace !== void 0) {
    return sourceMappingPrepareStackTrace;
  }
  const originalSupport = require.cache["@cspotcode/source-map-support"];
  delete require.cache["@cspotcode/source-map-support"];
  const support = require("@cspotcode/source-map-support");
  require.cache["@cspotcode/source-map-support"] = originalSupport;
  const originalPrepareStackTrace = Error.prepareStackTrace;
  support.install({
    environment: "node",
    // Don't add Node `uncaughtException` handler
    handleUncaughtExceptions: false,
    // Don't hook Node `require` function
    hookRequire: false,
    redirectConflictingLibrary: false,
    // Make sure we're using fresh copies of files each time we source map
    emptyCacheBetweenOperations: true,
    // Allow retriever to be overridden at prepare stack trace time
    retrieveSourceMap(path56) {
      return retrieveSourceMapOverride?.(path56) ?? null;
    }
  });
  sourceMappingPrepareStackTrace = Error.prepareStackTrace;
  (0, import_node_assert6.default)(sourceMappingPrepareStackTrace !== void 0);
  Error.prepareStackTrace = originalPrepareStackTrace;
  return sourceMappingPrepareStackTrace;
}
```

**Comment by GregBrimble** [comment]
Dupe of #4715
