### ISSUE TITLE
🐛 BUG: Error when running with `bun --bun`

### ISSUE THREAD

**Issue by hanssonduck** [cloudflare/workers-sdk#4895]
### Which Cloudflare product(s) does this pertain to?

Wrangler core, Miniflare

### What version(s) of the tool(s) are you using?

Wrangler 3.26.0

### What version of Node are you using?

Bun 1.0.25

### What operating system and version are you using?

MacOS 14.2.1

### Observed behavior
Request fails when running the dev server with `bun --bun`. This might have something to do with `getBindingsProxy` in `src/hooks.server.ts`.

### Expected behavior
The dev server should not error and work as expected.

### Steps to reproduce
Clone the repo and run the dev server using Bun with `bun run dev` and try to load the page.

### Please provide a link to a minimal reproduction

https://github.com/hanssonduck/wrangler-repo

### Please provide any relevant error logs

```console
❯ bun run dev
$ bun --bun vite dev --host

  VITE v5.0.12  ready in 392 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://192.168.1.109:5173/
  ➜  Network: http://100.69.190.28:5173/
  ➜  press h + enter to show help

12834 |       );
12835 |     }
12836 |     __name(finalizeAndReportTiming, "finalizeAndReportTiming");
12837 |     function markResourceTiming(timingInfo, originalURL, initiatorType, globalThis2, cacheState) {
12838 |       if (nodeMajor > 18 || nodeMajor === 18 && nodeMinor >= 2) {
12839 |         performance.markResourceTiming(timingInfo, originalURL.href, initiatorType, globalThis2, cacheState);
                ^
TypeError: performance.markResourceTiming is not a function. (In 'performance.markResourceTiming(timingInfo, originalURL.href, initiatorType, globalThis2, cacheState)', 'performance.markResourceTiming' is undefined)
      at markResourceTiming (/Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:12839:9)
      at finalizeAndReportTiming (/Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:12828:7)
      at /Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:12771:109
      at /Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:13115:44
17028 |         try {
17029 |           return await fetchImpl(...arguments);
17030 |         } catch (err) {
17031 |           if (typeof err === "object") {
17032 |             Error.captureStackTrace(err, this);
17033 |           }
                       ^
TypeError: fetch failed
      at /Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:17033:16
      at asyncFunctionResume (native:1:1)
      at promiseReactionJobWithoutPromiseUnwrapAsyncContext (native:1:1)
      at promiseReactionJob (native:1:1)
      at processTicksAndRejections (native:1:1)

5803 |           socket.on("session", function(session2) {
5804 |             sessionCache.set(sessionKey, session2);
5805 |           });
5806 |         } else {
5807 |           assert23(!httpSocket, "httpSocket can only be sent on TLS update");
5808 |           socket = net3.connect({
                          ^
TypeError: Expected "port" to be a number between 0 and 65535
 code: "ERR_INVALID_ARG_TYPE"

      at connect (node:net:257:19)
      at connect2 (/Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:5808:20)
      at /Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:7322:11
      at new Promise (:1:21)
      at /Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:7321:30
      at connect2 (/Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:7295:29)
      at _resume (/Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:7517:11)
      at resume (/Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:7442:7)
      at /Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:6700:11
      at Intercept (/Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:6373:20)
      at dispatch (/Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:5697:18)
      at /Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:8351:21
      at dispatch (/Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:5697:18)
      at Intercept (/Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:6373:20)
      at dispatch (/Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:5697:18)
      at /Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:13550:11
      at new Promise (:1:21)
      at /Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:13549:16
      at dispatch (/Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:13546:33)
      at /Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:13444:82
      at httpNetworkFetch (/Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:13380:37)
      at /Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:13332:39
      at httpNetworkOrCacheFetch (/Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:13259:44)
      at /Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:13166:43
      at httpFetch (/Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:13155:30)
      at schemeFetch (/Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:13090:18)
      at /Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:12963:26
      at /Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:12953:39
      at /Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:12981:45
      at mainFetch (/Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:12936:30)
      at fetching (/Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:12930:7)
      at fetch14 (/Users/user/code/test/node_modules/wrangler/wrangler-dist/cli.js:12794:20)

error: "vite" exited with code 1
error: script "dev" exited with code 1
```

**Comment by z0rrn** [comment]
For anyone interesting heres a temporary workaround: for me it worked by going into node_modules/wrangler/wrangler-dist/cli.js and replacing line 13015 with the comment `// Do nothing`. It think this needs to be done after every update.

**Comment by madanbazgai** [comment]
Can you please be more specific?

**Comment by qm3ster** [comment]
The problem comes from `undici`.
I wouldn't exactly say that `wrangler` uses that API.
Here is the offending line as of today https://github.com/RafaelGSS/undici/blob/c73e182f0bdfcea474c362d35a9a7176f649a07e/lib/fetch/index.js#L323

**Comment by cursefroge** [comment]
here's a bun patch file that resolves the issue
[wrangler@3.53.1.patch.txt](https://github.com/user-attachments/files/17089952/wrangler%403.53.1.patch.txt)
