### ISSUE TITLE
🐛 BUG: After upgrading nodejs to version 21.7.0 `wrangler dev` fails 

### ISSUE THREAD

**Issue by alpertuna** [cloudflare/workers-sdk#5190]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler core, Miniflare

### What version(s) of the tool(s) are you using?

3.31.0 [Wrangler]

### What version of Node are you using?

21.7.0

### What operating system and version are you using?

Linux

### Observed behavior
After upgrading nodejs to version 21.7.0, `wrangler dev` fails to start.
It works fine with nodejs version 21.6.2

### Expected behavior
`wrangler dev` runs without failing.

### Steps to reproduce
- Create project using `npm create cloudflare@latest` command.
- Start project using `npm start` (using nodejs v21.7.0)

### Please provide any relevant error logs

```sh
> divine-forest-b9bf@0.0.0 start
> wrangler dev

 ⛅️ wrangler 3.31.0
-------------------
⎔ Starting local server...
[wrangler:inf] Ready on http://localhost:8787
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
/home/x/Projects/divine-forest-b9bf/node_modules/wrangler/wrangler-dist/cli.js:29573
            throw a;
            ^

TypeError [ERR_INVALID_ARG_TYPE]: The "strategy" argument must be of type object. Received type number (0)
    at new ReadableStream (node:internal/webstreams/readablestream:254:5)
    at safeReadableStreamFrom (/home/x/Projects/divine-forest-b9bf/node_modules/miniflare/dist/src/index.js:8264:10)
    at #handleLoopback (/home/x/Projects/divine-forest-b9bf/node_modules/miniflare/dist/src/index.js:8425:36)
    at Server.emit (node:events:531:35)
    at Server.emit (node:domain:488:12)
    at parserOnIncoming (node:_http_server:1137:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v21.7.0
```

**Comment by wydengyre** [comment]
Here is the relevant change in Node: https://github.com/nodejs/node/commit/9ab353af00
