### ISSUE TITLE
🐛 BUG: Wrangler + Angular SSR (prerender: false) + Private properties = `TypeError: Class constructor t cannot be invoked without 'new'`

### ISSUE THREAD

**Issue by nunoarruda** [cloudflare/workers-sdk#5263]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

2.14.2 [create-cloudflare]

### What version of Node are you using?

20.11.1

### What operating system and version are you using?

macOS Sonoma 14.4

### Observed behavior
I noticed that:
1. When using the command `npm create cloudflare@latest my-angular-app -- --framework=angular`, an Angular SSR app is created with additional files and changes to make it work with Cloudflare Workers/Pages.
2. Static Site Generation (SSG) is enabled by default (`"prerender": true` on `angular.json`)
3. If you turn off SSG (`"prerender": false`), so everything is Server Side Rendered (SSR), and add a [private property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties), things break.

### Expected behavior
SSR should just work and not break with private properties.

### Steps to reproduce
1. Create a Cloudflare version of an Angular app `npm create cloudflare@latest my-angular-app -- --framework=angular`
2. Turn off Static Site Generation (SSG) by setting `"prerender": false` on `angular.json`
3. Add a private property (like, for example, `#test = 'test'`)
3. Run the app: `npm run start` and press `b`

cc: @petebacondarwin @alan-agius4 @JeanMeche

### Please provide a link to a minimal reproduction

https://github.com/nunoarruda/my-angular-app

### Please provide any relevant error logs

```zsh
[wrangler:err] TypeError: Class constructor t cannot be invoked without 'new'
    at t.handleNavigationRequest (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-3oJJr3/chunk-ZK4POREG.mjs:2:47542)
    at t.scheduleNavigation (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-3oJJr3/chunk-ZK4POREG.mjs:2:63103)
    at t.navigateToSyncWithBrowser (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-3oJJr3/chunk-ZK4POREG.mjs:2:61042)
    at t.initialNavigation (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-3oJJr3/chunk-ZK4POREG.mjs:2:60522)
    at s (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-3oJJr3/chunk-ZK4POREG.mjs:2:64001)
    at null.<anonymous> (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-3oJJr3/chunk-ES3Z552B.mjs:34:29056)
    at [object Object]
    at e._loadComponent (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-3oJJr3/chunk-ES3Z552B.mjs:34:29045)
    at e.bootstrap (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-3oJJr3/chunk-ES3Z552B.mjs:34:28076)
    at null.<anonymous> (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-3oJJr3/chunk-ES3Z552B.mjs:34:35938)
[wrangler:inf] GET / 500 Internal Server Error
```

<img width="1582" alt="Screenshot 2024-03-15 at 16 00 36" src="https://github.com/cloudflare/workers-sdk/assets/1189149/952c2215-bd48-4ce1-bd39-bffe703881f2">

**Comment by nunoarruda** [comment]
UPDATE

If just found out that if I remove the `inject` function...
```TS
#http = inject(HttpClient);

myRequest$ = this.#http.get('https://dummyjson.com/products/1');
```
and use the `constructor` instead...
```TS
myRequest$ = this.http.get('https://dummyjson.com/products/1');

constructor(private http: HttpClient) {}
```
...things start to work again.

So, maybe Wrangler or something else on the Cloudflare side is choking when using [inject](https://angular.io/api/core/inject)?

**Comment by alan-agius4** [comment]
The issue arises when re-running esbuild on an already bundled output, as it appears esbuild is incorrectly updating the references.

Angular CLI code:
```js
var rs = (() => {
  let M = class M {
    get hasRequestedNavigation() {
      return this.navigationId !== 0;
    }
    constructor() {
      //
    }
    complete() {
      this.transitions?.complete();
    }
    handleNavigationRequest(n) {
      let i = ++this.navigationId;
      this.transitions?.next(M(Object.assign(Object.assign({}, this.transitions.value), n), { id: i }));
    }
```

Wrangler Code:
```js
  let t13 = class t {
    get hasRequestedNavigation() {
      return this.navigationId !== 0;
    }
    constructor() {
     //
    }
    complete() {
      this.transitions?.complete();
    }
    handleNavigationRequest(n) {
      let i = ++this.navigationId;
      this.transitions?.next(t(s(s({}, this.transitions.value), n), { id: i }));
    }
```

The problem lies in the `handleNavigationRequest` method, where the first parameter of `this.transitions?.next` is `t()`. However, in this context, `t` refers to the local class, whereas in the original code generated by Angular CLI, it's `M`, referencing a completely different function.

Certainly, resolving this issue would indeed require further investigation to determine the best course of action and probably provide a minimal reproduction to esbuild folks. 

In this case, using a private field causes the problem because the private field is downleveled to a `WeakMap` and set as a variable named `t`. Perhaps, this is somehow causing confusion for esbuild.

```js
var cn = (() => {
  var t;
  let n = class n {
    constructor() {
      Qe(this, t, void 0);
      (this.title = "my-angular-app"), Ze(this, t, "test");
    }
  };
  (t = new WeakMap()),
    (n.ɵfac = function (s) {
      return new (s || n)();
    }),
    (n.ɵcmp = Tt({
      type: n,
      selectors: [["app-root"]],
      standalone: !0,
      features: [xt],
      decls: 1,
      vars: 0,
      template: function (s, o) {
        s & 1 && Ut(0, "router-outlet");
      },
      dependencies: [_e],
    }));
  let e = n;
  return e;
})();
```

**Comment by nunoarruda** [comment]
Decided to test this again using Angular 18 (although we already know this might be an esbuild issue). It still fails, but with different errors/logs now:

<img width="1582" alt="Screenshot 2024-06-19 at 14 54 22" src="https://github.com/cloudflare/workers-sdk/assets/1189149/afbb059f-dae0-4301-82cc-1e409122a821">

```bash
render SSR http://localhost:8788/
✘ [ERROR] ERROR W [Error]: NG05104

      at ms2.selectRootElement
  (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/chunk-YRCGDSRU.mjs:35:26456)
      at nc.selectRootElement
  (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/chunk-YRCGDSRU.mjs:35:91692)
      at fD
  (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/chunk-YRCGDSRU.mjs:8:39107)
      at Qi2.create
  (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/chunk-YRCGDSRU.mjs:34:10840)
      at e.bootstrap
  (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/chunk-YRCGDSRU.mjs:34:31534)
      at null.<anonymous>
  (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/chunk-YRCGDSRU.mjs:34:42335)
      at a.invoke
  (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/polyfills.server.mjs:4:6639)
      at Object.onInvoke
  (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/chunk-YRCGDSRU.mjs:34:7324)
      at a.invoke
  (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/polyfills.server.mjs:4:6579)
      at p4.run
  (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/polyfills.server.mjs:4:1965)
  {
    code: -5104
  }


[wrangler:err] Error: NG05104
    at ms2.selectRootElement (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/chunk-YRCGDSRU.mjs:35:26456)
    at nc.selectRootElement (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/chunk-YRCGDSRU.mjs:35:91692)
    at fD (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/chunk-YRCGDSRU.mjs:8:39107)
    at Qi2.create (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/chunk-YRCGDSRU.mjs:34:10840)
    at e.bootstrap (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/chunk-YRCGDSRU.mjs:34:31534)
    at null.<anonymous> (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/chunk-YRCGDSRU.mjs:34:42335)
    at a.invoke (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/polyfills.server.mjs:4:6639)
    at Object.onInvoke (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/chunk-YRCGDSRU.mjs:34:7324)
    at a.invoke (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/polyfills.server.mjs:4:6579)
    at p4.run (file:///Users/nunoarruda/Desktop/my-angular-app/.wrangler/tmp/pages-gjkZeE/polyfills.server.mjs:4:1965)
[wrangler:inf] GET / 500 Internal Server Error (396ms)
```
<img width="1092" alt="Screenshot 2024-06-19 at 14 57 58" src="https://github.com/cloudflare/workers-sdk/assets/1189149/7fd90c0f-16ba-43c8-b3c0-ad758d7a5103">


Does anyone with influence at [Cloudflare](https://github.com/cloudflare/workers-sdk) or [esbuild](https://github.com/evanw/esbuild) know how to raise this issue with the right people?
This is blocking users from using Angular SSR (`"prerender": false`) on Cloudflare. Thanks in advance 👍

**Comment by petebacondarwin** [comment]
@nunoarruda - is this still an issue? There have been quite a few updates to both Angular and Cloudflare since August.

**Comment by nunoarruda** [comment]
> [@nunoarruda](https://github.com/nunoarruda) - is this still an issue? There have been quite a few updates to both Angular and Cloudflare since August.

@petebacondarwin I gave it a quick try, and it no longer appears to be an issue.
