### ISSUE TITLE
🐛 BUG: JSON.stringify is rewriting my stack traces!

### ISSUE THREAD

**Issue by treeder** [cloudflare/workers-sdk#5293]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

3.34.2

### What version of Node are you using?

20.2.0

### What operating system and version are you using?

Linux

### Observed behavior

I am trying to log an error with a stack trace which has very useful information, only find the lines referencing my code are changed to something totally unusable. Mind boggling...

### Expected behavior

Don't touch my stack trace. 

### Steps to reproduce

```js
let payload = {
                    message: payload.message + ": " + payload.cause.message,
                    stack: payload.cause.stack,
                }
console.log("payload:", payload)
console.log("stringified:", JSON.stringify(payload))
```

Output:

```
payload: {
  message: 'error sending emails: yooo, error, red alert',
  stack: 'Error: yooo, error, red alert\n' +
    '    at sendThingEmails (file:///workspaces/myapp/public/server/email.js:76:15)'
}
stringified: {"message":"error sending emails: yooo, error, red alert","stack":"Error: yooo, error, red alert\n    at sendThingEmails (file:///workspaces/myapp/.wrangler/tmp/dev-jUmTOk/bundledWorker-0.44923439396608034.js:45005:11)"}
```

Note the stack trace change.

**Comment by RamIdeas** [comment]
I think this may actually be the other way round. We have implemented stack trace rewriting to map your stack traces back to the source files rather than their transpiled locations but our rewriting is probably being triggered by the json stringified format

**Comment by treeder** [comment]
Or maybe your rewriting is not be triggered when it's stringified?

**Comment by penalosa** [comment]
As Rahul said, this is in fact the other way around. We rewrite stack traces using source maps, but are unable to do so when the error is JSON-stringified. I'm going to close this as "by design", since I don't think we should be trying to modify the contents of log messages when they're arbitrary JSON—I'd recommend logging the error as-is if you'd like automatic stack trace rewriting to work.

Alternatively, if you'd like this to work in production, Cloudflare Workers have native support for Source Maps that may fit your use case: https://developers.cloudflare.com/workers/observability/source-maps/
