### ISSUE TITLE
🐛 BUG: wrangler versions list (and possibly other commands) don't work with pipes on linux

### ISSUE THREAD

**Issue by aplunk** [cloudflare/workers-sdk#5447]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.41.0

### What version of Node are you using?

v20.12.0

### What operating system and version are you using?

Linux Ubuntu 22.04.4 LTS

### Observed behavior
Piping the results of `wrangler versions list` to other commands results in an exception.

### Expected behavior
Piping the results of `wrangler versions list` writes to stdout and works with pipes on linux.

### Steps to reproduce
Please provide the following:
- `wrangler --experimental-gradual-rollouts versions list | head`

Example stacktrace:

```
/home/aplunk/example-project/node_modules/wrangler/wrangler-dist/cli.js:29573
            throw a;
            ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:952:11)
    at Socket._write (node:net:964:8)
    at writeOrBuffer (node:internal/streams/writable:564:12)
    at _write (node:internal/streams/writable:493:10)
    at Writable.write (node:internal/streams/writable:502:10)
    at logRaw (/home/aplunk/example-project/node_modules/wrangler/wrangler-dist/cli.js:133178:10)
    at Object.versionsListHandler [as handler] (/home/aplunk/example-project/node_modules/wrangler/wrangler-dist/cli.js:164546:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on Socket instance at:
    at Socket.onerror (node:internal/streams/readable:1026:14)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

**Comment by RamIdeas** [comment]
I am unable to reproduce this on macOS. This may be a linux-only issue so I will try in an ubuntu docker container and report back.

There is a chance this only happens for you when piping to `head`. Can you try adding the `--json` flag and piping to `jq`:

```sh
$ npx wrangler versions list --json --x-versions | jq '.[0].id'
```

Note: `--experimental-gradual-rollouts` was renamed `--experimental-versions` and has a shorthand `--x-versions`

**Comment by aplunk** [comment]
```
wrangler --x-versions versions list -c deploy/admin/staging/wrangler.toml | jq .

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:952:11)
    at Socket._write (node:net:964:8)
    at writeOrBuffer (node:internal/streams/writable:564:12)
    at _write (node:internal/streams/writable:493:10)
    at Writable.write (node:internal/streams/writable:502:10)
    at logRaw (/home/aplunk/cf-repos/example/node_modules/wrangler/wrangler-dist/cli.js:133178:10)
    at Object.versionsListHandler [as handler] (/home/aplunk/cf-repos/example/node_modules/wrangler/wrangler-dist/cli.js:164546:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on Socket instance at:
    at Socket.onerror (node:internal/streams/readable:1026:14)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

```

**Comment by RamIdeas** [comment]
I added [an e2e test](https://github.com/cloudflare/workers-sdk/pull/5476/files#diff-cc5e568bb91eb2bb3e13da2d7f125509200cbf3a650e18450a024d73af2eab60R75-R99) to see this fail on ubuntu

The test passed on macOS (expected) and failed on Windows (expected, pipe syntax is different)

But it passed on ubuntu (unexpected, given you're reporting this issue): https://github.com/cloudflare/workers-sdk/actions/runs/8525633472/job/23353038627?pr=5476#step:12:112

**Comment by aplunk** [comment]
@RamIdeas I know that this is affecting other Ubuntu users too. I'm not sure if this is related to the tty (or lack thereof) in github actions or something else. Attaching my project's npm-shrinkwrap.json in case it helps triage the issue.
[npm-shrinkwrap.json](https://github.com/cloudflare/workers-sdk/files/14841880/npm-shrinkwrap.json)

**Comment by RamIdeas** [comment]
Sorry for the delay. We tried this on an ubuntu machine and still didn't experience the issue. I'm not saying you're not experiencing it, just that I haven't seen the issue and so can't think what conditions it presents itself.

I'm thinking it maybe something to do with how wrangler is installed on your machine? I notice you're not running it with `npx` which is the recommendation since v3 – as a workaround, can you try running with `npx wrangler` instead? If you've installed it in your project or globally via `npm`/`yarn`/`pnpm`, it will use the already installed version just the same but maybe the wrapper process will behave differently when piped?

**Comment by penalosa** [comment]
@aplunk Can you reproduce this if running with `npx`?

**Comment by petebacondarwin** [comment]
Closing due to no response.
