### ISSUE TITLE
🐛 BUG: [wrangler:err] TypeError: Unexpected MODIFIER at 35, expected END

### ISSUE THREAD

**Issue by nneil** [cloudflare/workers-sdk#5540]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.48.0

### What version of Node are you using?

v20.12.1

### What operating system and version are you using?

Win 10

### Describe the Bug

One of my functions throws this error. Similar to this #4753

I'm running `npx wrangler pages dev dist --local-protocol https`

I've generated _worker.bundle, but don't know what I am supposed to see in the routes array.

```
[wrangler:err] TypeError: Unexpected MODIFIER at 35, expected END
    at mustConsume (file:///C://Projects/cloudflare/node_modules/.pnpm/path-to-regexp@6.2.1/node_modules/path-to-regexp/src/index.ts:157:11)
    at parse (file:///C://Projects/cloudflare/node_modules/.pnpm/path-to-regexp@6.2.1/node_modules/path-to-regexp/src/index.ts:227:5)
    at stringToRegexp (file:///C://Projects/cloudflare/node_modules/.pnpm/path-to-regexp@6.2.1/node_modules/path-to-regexp/src/index.ts:493:25)
    at pathToRegexp (file:///C://Projects/cloudflare/node_modules/.pnpm/path-to-regexp@6.2.1/node_modules/path-to-regexp/src/index.ts:620:10)
    at match (file:///C://Projects/cloudflare/node_modules/.pnpm/path-to-regexp@6.2.1/node_modules/path-to-regexp/src/index.ts:379:14)
    at executeRequest (file:///C://Projects/cloudflare/node_modules/.pnpm/wrangler@3.48.0_@cloudflare+workers-types@4.20240405.0/node_modules/wrangler/templates/pages-template-worker.ts:70:24)
    at [object Object]
    at next (file:///C://Projects/cloudflare/node_modules/.pnpm/wrangler@3.48.0_@cloudflare+workers-types@4.20240405.0/node_modules/wrangler/templates/pages-template-worker.ts:135:35)
    at Object.fetch (file:///C://Projects/cloudflare/node_modules/.pnpm/wrangler@3.48.0_@cloudflare+workers-types@4.20240405.0/node_modules/wrangler/templates/pages-template-worker.ts:180:17)
    at fetchDispatcher (file:///C://Projects/cloudflare/.wrangler/tmp/bundle-w4Ehvj/middleware-loader.entry.ts:56:17)
[wrangler:inf] PUT /api/set-connection/2003/238/0 500 Internal Server Error (67ms)
```

**Comment by penalosa** [comment]
Could you follow the debug steps @mrbbot outlined in https://github.com/cloudflare/workers-sdk/issues/4753#issuecomment-1893525572, and post your output here?

**Comment by nneil** [comment]
I did some testing and found that you can reproduce the problem by having a function with a pathname like
```
functions/p-q/[[x-y]].ts
```

**Comment by petebacondarwin** [comment]
> I did some testing and found that you can reproduce the problem by having a function with a pathname like
> 
> ```
> functions/p-q/[[x-y]].ts
> ```

This is working as expected.  The `[[x-y]]` segment is converted to a `path-to-regexp` library's parameter of the form `x-y*`. As you can see from [that library](See https://github.com/pillarjs/path-to-regexp#:~:text=Please%20note%3A%20Parameter%20names%20must%20use%20%22word%20characters%22%20(%5BA%2DZa%2Dz0%2D9_%5D).) this is not a valid parameter name.

We should probably provide a better error message than this.

**Comment by nneil** [comment]
Thanks for the better error message.

But naming the parameters at all seems a bit pointless. I'd much rather create `[[my-endpoint]].ts` without a directory and have the parameters appear as the list `context.params`. 

As it is I'm having to create `my-endpoint/[[my-endpoint]].ts` and then name `my-endpoint` in the code (though of course I now know I can't).

This seems unnecessarily tedious: what am I missing?

**Comment by petebacondarwin** [comment]
The point is that you can have multiple parameters, e.g. `foo/[param1]/bar/[[extra]]` and then you get `context.params.param1` and `context.params.extra` in your code.

**Comment by nneil** [comment]
The trouble is that all my TS files end up called `extra.ts`. I wish there were a better way. Do people really need that `bar` possibility?

**Comment by petebacondarwin** [comment]
Multiple segment params like this are common in REST APIs. For example in our own Pages product we have a route that looks like: `/api/projects/{project_name}/deployments/{deployment_id}/retry` (different framework so different syntax).
