### ISSUE TITLE
🐛 BUG: wrangler pages dev address in use windows handling

### ISSUE THREAD

**Issue by Cherry** [cloudflare/workers-sdk#5544]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.48.0

### What version of Node are you using?

20.12.1

### What operating system and version are you using?

Windows 11

### Observed behavior

When running `npx wrangler@3.48.0 pages dev public` once, and then again on Windows, rather than erroring with a nice error like this:
```
✘ [ERROR] Address already in use (127.0.0.1:8787). Please check that you are not already running a server on this address or specify a different port with --port.
```

it errors with a hard to understand stack trace like this:
```
C:\Users\james\AppData\Local\npm-cache\_npx\d77349f55c2be1c0\node_modules\wrangler\wrangler-dist\cli.js:29573
            throw a;
            ^

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, import_assert8.default)(!isClientError(syncRes.status))

    at #parseSyncResponse (C:\Users\james\AppData\Local\npm-cache\_npx\d77349f55c2be1c0\node_modules\miniflare\dist\src\index.js:6157:32)
    at ProxyStubHandler.get (C:\Users\james\AppData\Local\npm-cache\_npx\d77349f55c2be1c0\node_modules\miniflare\dist\src\index.js:6194:39)
    at Miniflare2.getWorker (C:\Users\james\AppData\Local\npm-cache\_npx\d77349f55c2be1c0\node_modules\miniflare\dist\src\index.js:9200:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ProxyController.reconnectInspectorProxyWorker (C:\Users\james\AppData\Local\npm-cache\_npx\d77349f55c2be1c0\node_modules\wrangler\wrangler-dist\cli.js:172635:36)
    at async Promise.all (index 1) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

### Expected behavior

As on macOS, it should error more gracefully with something like:
```
✘ [ERROR] Address already in use (127.0.0.1:8787). Please check that you are not already running a server on this address or specify a different port with --port.
```

### Steps to reproduce

- Empty directory
- Add `hello` to a `public/index.html` file
- Run `npx wrangler@3.48.0 pages dev public`
- Without closing the previous terminal, open another one and run the same command again

**Comment by Luzefiru** [comment]
Try updating your `wrangler` package to the latest version `3.50.0`. It fixed it for me.

We may not have the same underlying issue, but here are my logs:
<details>
<summary>Logs using wrangler v3.32.0</summary>
<PATH_TO_YOUR_PROJECT>\node_modules\wrangler\wrangler-dist\cli.js:29573
            throw a;
            ^

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, import_assert8.default)(!isClientError(syncRes.status))

    at #parseSyncResponse (<PATH_TO_YOUR_PROJECT>\node_modules\miniflare\dist\src\index.js:6157:32)
    at ProxyStubHandler.get (<PATH_TO_YOUR_PROJECT>\node_modules\miniflare\dist\src\index.js:6194:39)        
    at Miniflare2.getWorker (<PATH_TO_YOUR_PROJECT>\node_modules\miniflare\dist\src\index.js:9200:36)        
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ProxyController.reconnectInspectorProxyWorker (<PATH_TO_YOUR_PROJECT>\node_modules\wrangler\wrangler-dist\cli.js:172635:36)
    at async Promise.all (index 1) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

Node.js v21.6.1
</details>

**Comment by Cherry** [comment]
The error message hasn't changed in 3.50.0. If I run two instances as described, I don't get a nice "address in use" error like I do in MacOS, but instead the error pasted in my first comment.

**Comment by rtrigoso** [comment]
this issue can be duplicated by simply using the nextjs cloudflare template as well
