### ISSUE TITLE
🐛 BUG: local Cloudflare Queues died and did not revive.

### ISSUE THREAD

**Issue by natsumesou** [cloudflare/workers-sdk#5636]
### Which Cloudflare product(s) does this pertain to?

Queues

### What version(s) of the tool(s) are you using?

v3.20240404.0

### What version of Node are you using?

20.10.0

### What operating system and version are you using?

Mac Sonoma 14.2.1

### Observed behavior

When I left the local environment running with `npx wrangler dev` for about 2 hours, Cloudflare Queues died and did not revive.
I ran `env.QUEUE.send()` in the local environment, the following error occurred:

```
[wrangler-UserWorker:err] TypeError: Can't read from request stream because client disconnected.
    at async QueueBrokerObject.message (file:///Users/n/Development/test/node_modules/miniflare/src/workers/queues/broker.worker.ts:338:28)
    at async QueueBrokerObject.fetch (file:///Users/n/Development/test/node_modules/miniflare/src/workers/shared/router.worker.ts:45:32)
    at async QueueBrokerObject.fetch (file:///Users/n/Development/test/node_modules/miniflare/src/workers/shared/object.worker.ts:148:11)
```

Since I couldn't connect to the local Cloudflare Queues, I stopped `npx wrangler dev`, restarted it, but the same error occurred, and Cloudflare Queues did not restart properly.

### Expected behavior

re-run `npx wrangler dev`, then respawn Cloudflare Queues process.

### Steps to reproduce

The steps to reproduce the phenomenon are unknown.

### Please provide a link to a minimal reproduction

I created [minimal reproduction repo](https://github.com/natsumesou/minimal-reproduction-for-cloudflare-queues-died-process).

**Comment by natsumesou** [comment]
This error continues to occur even after restarting the Mac. Currently, running `env.QUEUE.send()` in the local environment always results in same error (previously it was working fine).

**Comment by mattdeboard** [comment]
For what it's worth, I've tried @natsumesou 's sample case. I cloned it, then ran `npx wrangler dev`. Then I opened up a browser window by hitting the `b` shortcut.

On node v18.18.2, the error I see when I do that is:

```
⎔ Reloading local server...
[wrangler:inf] Ready on http://localhost:8787
[wrangler:inf] GET / 200 OK (4ms)
[wrangler-UserWorker:err] TypeError: Can't read from request stream because client disconnected.
    at async QueueBrokerObject.message (file:///Users/mdeboard/.nvm/versions/node/v18.18.2/lib/node_modules/wrangler/node_modules/miniflare/src/workers/queues/broker.worker.ts:336:28)
    at async QueueBrokerObject.fetch (file:///Users/mdeboard/.nvm/versions/node/v18.18.2/lib/node_modules/wrangler/node_modules/miniflare/src/workers/shared/router.worker.ts:45:32)
    at async QueueBrokerObject.fetch (file:///Users/mdeboard/.nvm/versions/node/v18.18.2/lib/node_modules/wrangler/node_modules/miniflare/src/workers/shared/object.worker.ts:148:11)
[wrangler:inf] GET /favicon.ico 200 OK (1ms)
[wrangler-UserWorker:err] TypeError: Can't read from request stream because client disconnected.
    at async QueueBrokerObject.message (file:///Users/mdeboard/.nvm/versions/node/v18.18.2/lib/node_modules/wrangler/node_modules/miniflare/src/workers/queues/broker.worker.ts:336:28)
    at async QueueBrokerObject.fetch (<path>/.nvm/versions/node/v18.18.2/lib/node_modules/wrangler/node_modules/miniflare/src/workers/shared/router.worker.ts:45:32)
    at async QueueBrokerObject.fetch (<path>/.nvm/versions/node/v18.18.2/lib/node_modules/wrangler/node_modules/miniflare/src/workers/shared/object.worker.ts:148:11)
```

However, on node v16.20.2 (the latest release supported officially by `workers-sdk`, if I understand correctly), I get a different, more detailed error:

```
[wrangler:inf] Ready on http://localhost:8787
[wrangler:inf] GET / 200 OK (4ms)
[wrangler-UserWorker:err] TypeError: Can't read from request stream because client disconnected.
    at async QueueBrokerObject.message (file:///Users/mdeboard/.npm/_npx/32026684e21afda6/node_modules/miniflare/src/workers/queues/broker.worker.ts:338:28)
    at async QueueBrokerObject.fetch (file:///Users/mdeboard/.npm/_npx/32026684e21afda6/node_modules/miniflare/src/workers/shared/router.worker.ts:45:32)
    at async QueueBrokerObject.fetch (file:///Users/mdeboard/.npm/_npx/32026684e21afda6/node_modules/miniflare/src/workers/shared/object.worker.ts:148:11)
[wrangler:inf] GET /favicon.ico 200 OK (2ms)
✘ [ERROR] Received a QueueEvent but we lack a handler for QueueEvents. Did you remember to export a queue() function?

✘ [ERROR] Uncaught (async) Error: Handler does not export a queue() function.

✘ [ERROR] Uncaught (async) Error: Handler does not export a queue() function.

[wrangler-UserWorker:wrn] Dropped message "3914c9c602a3bfc352d5baef835029ad" on queue "test-webhook" after 3 failed attempts!
✘ [ERROR] Uncaught (async) Error: Handler does not export a queue() function.
```

**Comment by mattdeboard** [comment]
FWIW I tried out @natsumesou 's minimal recreation by:
1. cloning it locally 
2. running `npx wrangler dev`
3. hitting `b` to open browser
4. observe CLI output

Notably, using node v18.18.2 and node v16.20.2 yield different results.

v18.18.2 (wrangler v3.41.0):

```
⎔ Starting local server...
[wrangler-UserWorker:wrn] The latest compatibility date supported by the installed Cloudflare Workers Runtime is "2024-03-20",
but you've requested "2024-04-03". Falling back to "2024-03-20"...
Features enabled by your requested compatibility date may not be available.
Upgrade to `wrangler@3.51.0` to remove this warning.
[wrangler:inf] Ready on http://localhost:8787
[wrangler:inf] GET / 200 OK (3ms)
[wrangler-UserWorker:err] TypeError: Can't read from request stream because client disconnected.
    at async QueueBrokerObject.message (file:///Users/mdeboard/.nvm/versions/node/v18.18.2/lib/node_modules/wrangler/node_modules/miniflare/src/workers/queues/broker.worker.ts:336:28)
    at async QueueBrokerObject.fetch (file:///Users/mdeboard/.nvm/versions/node/v18.18.2/lib/node_modules/wrangler/node_modules/miniflare/src/workers/shared/router.worker.ts:45:32)
    at async QueueBrokerObject.fetch (file:///Users/mdeboard/.nvm/versions/node/v18.18.2/lib/node_modules/wrangler/node_modules/miniflare/src/workers/shared/object.worker.ts:148:11)
[wrangler:inf] GET /favicon.ico 200 OK (1ms)
[wrangler-UserWorker:err] TypeError: Can't read from request stream because client disconnected.
    at async QueueBrokerObject.message (file:///Users/mdeboard/.nvm/versions/node/v18.18.2/lib/node_modules/wrangler/node_modules/miniflare/src/workers/queues/broker.worker.ts:336:28)
    at async QueueBrokerObject.fetch (file:///Users/mdeboard/.nvm/versions/node/v18.18.2/lib/node_modules/wrangler/node_modules/miniflare/src/workers/shared/router.worker.ts:45:32)
    at async QueueBrokerObject.fetch (file:///Users/mdeboard/.nvm/versions/node/v18.18.2/lib/node_modules/wrangler/node_modules/miniflare/src/workers/shared/object.worker.ts:148:11)
```

v16.20.2 (wrangler v3.51.0):

```
⎔ Starting local server...
[wrangler:inf] Ready on http://localhost:8787
[wrangler:inf] GET / 200 OK (4ms)
[wrangler-UserWorker:err] TypeError: Can't read from request stream because client disconnected.
    at async QueueBrokerObject.message (file:///Users/mdeboard/.npm/_npx/32026684e21afda6/node_modules/miniflare/src/workers/queues/broker.worker.ts:338:28)
    at async QueueBrokerObject.fetch (file:///Users/mdeboard/.npm/_npx/32026684e21afda6/node_modules/miniflare/src/workers/shared/router.worker.ts:45:32)
    at async QueueBrokerObject.fetch (file:///Users/mdeboard/.npm/_npx/32026684e21afda6/node_modules/miniflare/src/workers/shared/object.worker.ts:148:11)
[wrangler:inf] GET /favicon.ico 200 OK (2ms)
```

**Comment by mattdeboard** [comment]
Also, I've found that:

1. as long as wrangler is `3.51.0`, I get the latter error regardless of node version.
2. while the first page load results in the "because client disconnected" error, subsequent refreshes do not, so seems like maybe an issue while communicating with browser APIs?

**Comment by natsumesou** [comment]
I have identified the cause. It seems that the server was closing because I forgot to add `await` to `env.QUEUE.send()`. After changing it to `await env.QUEUE.send()`, it worked correctly.
Sorry for the trouble.
