### ISSUE TITLE
🐛 BUG: `wrangler tail` fails when using warp

### ISSUE THREAD

**Issue by jspspike** [cloudflare/workers-sdk#5693]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.51.2

### What version of Node are you using?

20.11.0

### What operating system and version are you using?

Linux

### Describe the Bug

When calling `wrangler tail` with warp on I get the following error:
```
/home/jjohnson/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:29573
            throw a;
            ^

Error: self-signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket.emit (node:domain:488:12)
    at TLSSocket._finishInit (node:_tls_wrap:1085:8)
    at ssl.onhandshakedone (node:_tls_wrap:871:12)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/home/jjohnson/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:114979:17)
    at ClientRequest.<anonymous> (/home/jjohnson/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:114879:9)
    at ClientRequest.emit (node:events:518:28)
    at ClientRequest.emit (node:domain:488:12)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket.emit (node:domain:488:12)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}

Node.js v20.11.0
```

Without warp on I don't see this error

**Comment by penalosa** [comment]
Long time no see 👋! I suspect this is an issue with the new WARP root certificate conflicting with the one Wrangler packages, or something along those lines. Do you have anything set in `NODE_EXTRA_CA_CERTS`?

**Comment by jspspike** [comment]
:wave:! @penalosa 
I don't have anything set there and nothing in my `.npmrc`
