### ISSUE TITLE
🐛 BUG: Error with wrangler dev and HTTPS localhost sub-requests

### ISSUE THREAD

**Issue by daniel-revell** [cloudflare/workers-sdk#5774]
### Which Cloudflare product(s) does this pertain to?

Miniflare

### What version(s) of the tool(s) are you using?

wrangler 3.53.1

### What version of Node are you using?

v21.1.0

### What operating system and version are you using?

Mac Somona 14.4.1

### Observed behavior
Sub-request to **https**://localhost result in error. 

### Expected behavior
HTTP requests work, would expect HTTPS requests to also work. Or a documented way to turn off HTTPS validation. 

### Steps to reproduce
- npx wrangler dev
- fetch('https://localhost:5000')

### Please provide any relevant error logs

[wrangler:inf] Ready on http://localhost:8787
✘ [ERROR] WARNING: known issue with `fetch()` requests to custom HTTPS ports in published Workers:

   - https://localhost:5000/api/impersonate - the custom port will be ignored when the Worker is
  published using the `wrangler deploy` command.

✘ [ERROR] Uncaught (async) Error: internal error

[wrangler:err] Error: internal error
    at async passThroughHandler (file:///Users/daniel/Projects/api-worker/src/handlers/pass-through.handler.ts:13:10)
    at async Object.handle (file:///Users/daniel/Projects/api-worker/node_modules/itty-router/Router.js:1:614)
    at async Object.fetch (file:///Users/daniel/Projects/api-worker/src/index.ts:241:12)
    at async jsonError (file:///Users/daniel/Projects/api-worker/node_modules/wrangler/templates/middleware/middleware-miniflare3-json-error.ts:22:10)
    at async drainBody (file:///Users/daniel/Projects/api-worker/node_modules/wrangler/templates/middleware/middleware-ensure-req-body-drained.ts:5:10)
[wrangler:inf] POST /users/v1/tokens 500 Internal Server Error (99ms)

**Comment by penalosa** [comment]
To clarify, does your server running on `localhost:5000` work with `https://`? (i.e. what happens when you open https://localhost:5000/ in a browser?)

**Comment by vivaladan** [comment]
Yes, I have a local ASP.NET web server running. The IDE installs a local development certificate to the machine upon first run so the browser is then fine with the self-signed certificate on any port. https://localhost:5000 displays the index page and all the JSON endpoints at /api/... work fine. Miniflare doesn't like it though, whether it's the port or certificate I don't know.

**Comment by michaellzc** [comment]
We ran into the same problem, and here's a minimal example to reproduce the problem locally. https://github.com/michaellzc/cf-workers-broken-local-https

**Comment by Shotster** [comment]
I might be encountering the same or similar issue. I can access `https://localhost:8888/my/resource` using curl as well as a browser without issue; but a `fetch()` call from a locally running worker via `wrangler dev` fails with an internal error: `internal error; reference = har4kqjkcr6cjcn114b05c21`. (I also [posted about it on the forum](https://community.cloudflare.com/t/fetch-call-to-localhost-from-locally-running-worker-fails/784400).)

My current workaround is to use `ngrok` (Cloudflare Zero Trust doesn't work because of [this issue](https://github.com/cloudflare/workers-sdk/issues/7835)), which works but should be unnecessary to access a resource on my local machine.

**Comment by jvhellemond** [comment]
Same here, but for pages dev.

Running `npx wrangler pages dev --ip=0.0.0.0 --port=8000 --https-cert-path=./localhost-cert.pem --https-key-path=./localhost-key.pem` using a self-signed certificate. The dev server starts fine and reports `[wrangler:info] Ready on https://0.0.0.0:8000`. But when any of the pages functions runs a fetch to a https://* URL, I get the same error:

```
[wrangler:error] Error: internal error; reference = rhnmdveim35a4328380n5i8b
    at async onRequestGet (file:///Users/jvhellemond/Projects/eventstack.shop/cssday-2026/functions/api/categories.js:21:19)
    at async next (file:///Users/jvhellemond/.npm/_npx/32026684e21afda6/node_modules/wrangler/templates/pages-template-worker.ts:161:22)
    at async Object.fetch (file:///Users/jvhellemond/.npm/_npx/32026684e21afda6/node_modules/wrangler/templates/pages-template-worker.ts:180:11)
    at async jsonError (file:///Users/jvhellemond/.npm/_npx/32026684e21afda6/node_modules/wrangler/templates/middleware/middleware-miniflare3-json-error.ts:22:10)
    at async drainBody (file:///Users/jvhellemond/.npm/_npx/32026684e21afda6/node_modules/wrangler/templates/middleware/middleware-ensure-req-body-drained.ts:5:10)
    at async jsonError (file:///Users/jvhellemond/.npm/_npx/32026684e21afda6/node_modules/wrangler/templates/middleware/middleware-miniflare3-json-error.ts:22:10)
    at async drainBody (file:///Users/jvhellemond/.npm/_npx/32026684e21afda6/node_modules/wrangler/templates/middleware/middleware-ensure-req-body-drained.ts:5:10)
[wrangler:info] GET /api/categories 500 Internal Server Error (7ms)
```
