### ISSUE TITLE
🐛 BUG: Wrangler login fails

### ISSUE THREAD

**Issue by PacifiK2460** [cloudflare/workers-sdk#5877]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.57.0 [wrangler]

### What version of Node are you using?

21.3.0

### What operating system and version are you using?

Windows 11

### Observed behavior
Can't login, neither from browser nor with curl

### Expected behavior
Log in

### Steps to reproduce
Directly run `npx wrangler login` (If not installed, npx will install it).

Output:
```
PS G:\...> npx wrangler login
 ⛅️ wrangler 3.57.0
-------------------
Attempting to login via OAuth...
Opening a link in your default browser: https://dash.cloudflare.com/oauth2/auth?response_type=code&client_id=...
C:\Users\dev\AppData\Local\npm-cache\_npx\32026684e21afda6\node_modules\wrangler\wrangler-dist\cli.js:29749
            throw a;
            ^

Error: ENOENT: no such file or directory, open 'C:\Users\dev\AppData\Roaming\xdg.config\.wrangler\config\default.toml'
    at writeFileSync (node:fs:2352:20)
    at writeAuthConfigFile (C:\Users\dev\AppData\Local\npm-cache\_npx\32026684e21afda6\node_modules\wrangler\wrangler-dist\cli.js:155005:37)
    at Server.<anonymous> (C:\Users\dev\AppData\Local\npm-cache\_npx\32026684e21afda6\node_modules\wrangler\wrangler-dist\cli.js:155098:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\dev\\AppData\\Roaming\\xdg.config\\.wrangler\\config\\default.toml'
}
```

And the browser gives: **ERR_CONNECTION_REFUSED**

### Please provide any relevant error logs

```
Failed to load .env file ".env": Error: ENOENT: no such file or directory, open 'G:\...\.env'
    at Object.openSync (node:fs:581:18)
    at Object.readFileSync (node:fs:457:35)
    at tryLoadDotEnv (G:\...\node_modules\wrangler\wrangler-dist\cli.js:158790:72)
    at loadDotEnv (G:\...\node_modules\wrangler\wrangler-dist\cli.js:158799:12)
    at G:\...\node_modules\wrangler\wrangler-dist\cli.js:200143:20
    at G:\...\node_modules\wrangler\wrangler-dist\cli.js:165196:16
    at maybeAsyncResult (G:\...\node_modules\wrangler\wrangler-dist\cli.js:163417:44)
    at G:\...\node_modules\wrangler\wrangler-dist\cli.js:165195:14
    at G:\...\node_modules\wrangler\wrangler-dist\cli.js:163404:22
    at Array.reduce (<anonymous>) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'G:\\...\\.env'
}
```

**Comment by PacifiK2460** [comment]
Logged in with another machine, copied the content of default.toml to `C:\Users\dev\AppData\Roaming\xdg.config\.wrangler\config\default.toml`
