### ISSUE TITLE
🐛 BUG: Runtime API: cloudflare:sockets TypeError: Invalid URL: 1.1.1.1:1234

### ISSUE THREAD

**Issue by Ehco1996** [cloudflare/workers-sdk#5986]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

3.59.0 [wrangler]

### What version of Node are you using?

v16.20.2

### What operating system and version are you using?

Mac

### Observed behavior

can not connet to ip:port

### Expected behavior

connect success

### Steps to reproduce
Please provide the following:
- A minimal working subset of your worker code
```
import { connect } from 'cloudflare:sockets';
async function handleRequest(request) {
	const tcpSocket = connect({ hostname: '1.1.1.1', port: 1234 });
	console.log(tcpSocket);
	return new Response("");
}

export default {
	async fetch(request, env, ctx) {
		return handleRequest(request);
	},
};

```
- A minimal working subset of your `wrangler.toml`
default one
- Commands used to start your local dev server, including custom env and cli args
defualt one

- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)
N/A

A git repo we can clone and run a test suit on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.

### Please provide any relevant error logs

.internal-fc0b03f8-5785-4f7b-a1f6-f7be1cb3bd5f-facade-1.js:14 TypeError: Invalid URL: 1.1.1.1:1234
    at connect (cloudflare:sockets:7:20)
    at handleRequest (index.js:4:21)
    at Object.fetch (index.js:13:12)
    at __facade_modules_fetch__ (.internal-fc0b03f8-5785-4f7b-a1f6-f7be1cb3bd5f-loader.js:24:17)
    at __facade_invokeChain__ (.internal-fc0b03f8-5785-4f7b-a1f6-f7be1cb3bd5f-common.js:16:10)
    at Object.next (.internal-fc0b03f8-5785-4f7b-a1f6-f7be1cb3bd5f-common.js:13:14)
    at jsonError (.internal-fc0b03f8-5785-4f7b-a1f6-f7be1cb3bd5f-facade-1.js:12:32)
    at __facade_invokeChain__ (.internal-fc0b03f8-5785-4f7b-a1f6-f7be1cb3bd5f-common.js:16:10)
    at Object.next (.internal-fc0b03f8-5785-4f7b-a1f6-f7be1cb3bd5f-common.js:13:14)
    at scheduled (.internal-fc0b03f8-5785-4f7b-a1f6-f7be1cb3bd5f-facade-0.js:9:24)

**Comment by Ehco1996** [comment]
fun fact , this issue only hanpen when deploy to cf workers online , but when is use `npm run dev` everything works well

so maybe this is a know bug and already fixed, just not cherry-pick in cf production env ?
