### ISSUE TITLE
🐛 BUG: Miniflare R2 writeHttpMetadata - DevalueError: Cannot stringify arbitrary non-POJOs

### ISSUE THREAD

**Issue by devinpitcher** [cloudflare/workers-sdk#6047]
### Which Cloudflare product(s) does this pertain to?

R2, Miniflare

### What version(s) of the tool(s) are you using?

3.60.3 [wrangler], 3.20240610.0 [miniflare]

### What version of Node are you using?

18.18.2

### What operating system and version are you using?

macOS Sonoma 14.4.1 (23E224)

### Observed behavior

On a basic Next.js route handler, when attempting to `writeHttpMetadata` from an R2 Object to `new Headers()`, I get a `DevalueError: Cannot stringify arbitrary non-POJOs` error.

```
 ⨯ Error [DevalueError]: Cannot stringify arbitrary non-POJOs
    at flatten (file:///Users/devin/Code/xxxxxxx/node_modules/miniflare/dist/src/index.js:3035:19)
    at flatten (file:///Users/devin/Code/xxxxxxx/node_modules/miniflare/dist/src/index.js:3008:22)
    at stringify (file:///Users/devin/Code/xxxxxxx/node_modules/miniflare/dist/src/index.js:3072:17)
    at stringifyWithStreams (file:///Users/devin/Code/xxxxxxx/node_modules/miniflare/dist/src/index.js:3265:28)
    at #call (file:///Users/devin/Code/xxxxxxx/node_modules/miniflare/dist/src/index.js:6338:25)
    at Proxy.writeHttpMetadata (file:///Users/devin/Code/xxxxxxx/node_modules/miniflare/dist/src/index.js:6325:34)
    at GET (webpack-internal:///(rsc)/./src/app/api/image/[...key]/route.ts:19:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:228:37)
    at async AppRouteRouteModule.execute (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:157:26)
    at async AppRouteRouteModule.handle (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:290:30)
    at async EdgeRouteModuleWrapper.handler (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/web/edge-route-module-wrapper.js:92:21)
    at async adapter (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/web/adapter.js:179:16)
    at async (file:///Users/devin/Code/xxxxxxx/node_modules/next/dist/server/web/sandbox/sandbox.js:110:22)
    at async runWithTaggedErrors (file:///Users/devin/Code/xxxxxxx/node_modules/next/dist/server/web/sandbox/sandbox.js:107:9)
    at async DevServer.runEdgeFunction (file:///Users/devin/Code/xxxxxxx/node_modules/next/dist/server/next-server.js:1201:24)
    at async NextNodeServer.handleCatchallRenderRequest (file:///Users/devin/Code/xxxxxxx/node_modules/next/dist/server/next-server.js:248:37)
    at async DevServer.handleRequestImpl (file:///Users/devin/Code/xxxxxxx/node_modules/next/dist/server/base-server.js:816:17)
    at async (file:///Users/devin/Code/xxxxxxx/node_modules/next/dist/server/dev/next-dev-server.js:339:20)
    at async Span.traceAsyncFn (file:///Users/devin/Code/xxxxxxx/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (file:///Users/devin/Code/xxxxxxx/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (file:///Users/devin/Code/xxxxxxx/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (file:///Users/devin/Code/xxxxxxx/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (file:///Users/devin/Code/xxxxxxx/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (file:///Users/devin/Code/xxxxxxx/node_modules/next/dist/server/lib/start-server.js:141:13)
```

### Expected behavior

The headers from the R2 object would be appended to the headers instance.

### Steps to reproduce

```typescript
import { type NextRequest } from "next/server";
import { getRequestContext } from "@cloudflare/next-on-pages";

export const runtime = "edge";

export async function GET(
  request: NextRequest,
  { params: { key } }: { params: { key: string[] } },
) {
  const {
    env: { UPLOADS },
  } = getRequestContext();

  const object = await UPLOADS.get(key.join("/"));

  if (object === null) {
    return new Response("Object Not Found", { status: 404 });
  }

  const headers = new Headers();

  object.writeHttpMetadata(headers);

  headers.set("etag", object.httpEtag);

  return new Response(object.body, {
    headers,
  });
}
```

`wrangler.toml`

```toml
name = "xxxxxxxxx"

compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "database"
database_id = "xxxxxxxxx"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "xxxxxxxxx"
```

**Comment by Ken-UCD** [comment]
Same error here, when uploading to a bucket. Only happens in local environment in a Next.js full-stack project.

## Which Cloudflare product(s) does this pertain to?
R2, Miniflare

## What version(s) of the tool(s) are you using?
3.60.3 [wrangler], 3.20240610.0 [miniflare], 1.11.3 [@cloudflare/next-on-pages]

## What version of Node are you using?
20.12.2

## What operating system and version are you using?
Ubuntu 22.04.3 LTS

## Describe the Bug
### Observed behavior
When attempting to upload through `env.BUCKET.put`, get `[DevalueError]: Cannot stringify arbitrary non-POJOs` error.
```
⨯ Error [DevalueError]: Cannot stringify arbitrary non-POJOs
    at flatten (file:///home/ken/dev/ai-seller/node_modules/miniflare/dist/src/index.js:3035:19)
    at flatten (file:///home/ken/dev/ai-seller/node_modules/miniflare/dist/src/index.js:3062:50)
    at flatten (file:///home/ken/dev/ai-seller/node_modules/miniflare/dist/src/index.js:3008:22)
    at stringify (file:///home/ken/dev/ai-seller/node_modules/miniflare/dist/src/index.js:3072:17)
    at stringifyWithStreams (file:///home/ken/dev/ai-seller/node_modules/miniflare/dist/src/index.js:3265:28)
    at #call (file:///home/ken/dev/ai-seller/node_modules/miniflare/dist/src/index.js:6338:25)
    at Proxy.put (file:///home/ken/dev/ai-seller/node_modules/miniflare/dist/src/index.js:6325:34)
    at POST (webpack-internal:///(rsc)/./app/api/cos/route.ts:49:116)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:218:43)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/lib/trace/tracer.js:108:36)
    at NoopContextManager.with (webpack-internal:///(rsc)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:361:30)
    at ContextAPI.with (webpack-internal:///(rsc)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:31:58)
    at NoopTracer.startActiveSpan (webpack-internal:///(rsc)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:954:34)
    at ProxyTracer.startActiveSpan (webpack-internal:///(rsc)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:994:36)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/lib/trace/tracer.js:97:103)
    at NoopContextManager.with (webpack-internal:///(rsc)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:361:30)
    at ContextAPI.with (webpack-internal:///(rsc)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:31:58)
    at NextTracerImpl.trace (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/lib/trace/tracer.js:97:28)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:206:91)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/async-storage/static-generation-async-storage-wrapper.js:44:24)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:160:288)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/async-storage/request-async-storage-wrapper.js:81:24)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:160:117)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at AppRouteRouteModule.execute (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:157:56)
    at AppRouteRouteModule.handle (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:280:41)
    at EdgeRouteModuleWrapper.handler (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/web/edge-route-module-wrapper.js:92:44)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/web/adapter.js:195:23)
    at NoopContextManager.with (webpack-internal:///(rsc)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:361:30)
    at ContextAPI.with (webpack-internal:///(rsc)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:31:58)
    at NextTracerImpl.withPropagatedContext (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/lib/trace/tracer.js:63:28)
    at propagator (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/web/adapter.js:63:19)
    at adapter (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/web/adapter.js:176:22)
```
### Example code
```
import type { NextRequest } from 'next/server'
import { getRequestContext } from '@cloudflare/next-on-pages';
export const runtime = 'edge'
export async function POST(req: NextRequest) {
  const object = await getRequestContext().env.BUCKET.put('test-key', req.body, {
    httpMetadata: req.headers,
  })
  return new Response(null, {headers: {'etag': object.httpEtag,}})
}
```
## Notes
This code works fine in production.
Btw, how do I access a real remote R2 in local development in a full-stack Pages project, when I am supposed to use `npm run dev` directly?

**Comment by devinpitcher** [comment]
> Looks like we need to make the stringification of Headers in the context of this call more robust in Miniflare. Does this code work in production?

This is a pretty fresh project I'm working on, have not pushed to production for testing yet. I would assume it would work in production since it's just pulling a simple JPEG from R2. Must be some sort of issue with the miniflare simulator.

**Comment by raffpaquin** [comment]
I have the same problem with a full-stack Next.js app running locally with service binding. If my service call returns a string or number, it works as expected. But if the service call returns an object, it doesn't work, and I get the `DevalueError: Cannot stringify POJOs with symbolic keys`

**Comment by raffpaquin** [comment]
> I have the same problem with a full-stack Next.js app running locally with service binding. If my service call returns a string or number, it works as expected. But if the service call returns an object, it doesn't work, and I get the `DevalueError: Cannot stringify POJOs with symbolic keys`

I roll-backed to `wrangler@3.51` and it's now working (from `wrangler@3.62`).

**Comment by mlafeldt** [comment]
I'm running into this as well.

Interestingly, if I import `Headers` from miniflare ([like here](https://github.com/cloudflare/workers-sdk/blob/3ae16ac5d5a70892c48a5e3d53f3aa275345d048/packages/miniflare/test/plugins/r2/index.spec.ts#L10)), `writeHttpMetadata` works fine. Without the import, the default `Headers` interface from TypeScript's libdom will cause the mentioned `Cannot stringify arbitrary non-POJOs` error.

So this seems to be a type issue.

**Comment by macinjoke** [comment]
I use Rimix Vite Plugin. and same error.

Thanks to @mlafeldt , This is my workaround. 

```
  const Headers_ =
    process.env.NODE_ENV === 'development' ? (await import('miniflare')).Headers : Headers

  const headers = new Headers_() as any
  object.writeHttpMetadata(headers)
```

In local development, 'miniflare'.Headers works.
In Cloudflare Workers, normal Headers works

**Comment by ncnlinh** [comment]
Same error when using Astro https://developers.cloudflare.com/workers/frameworks/framework-guides/astro/

**Comment by svaraborut** [comment]
This fixed it for me (it also fixes another unrelated bug in development). To fix it I rewrap the ArrayBuffer into a `Blob` which is correctly recognized by the dev server.

```ts
// (!) In dev mode materialize the body in ram as miniflare fails due to `body`
// not being a "fixed size stream". Then transform it to a Blob as it will fail
// again not recognizing the ArrayBuffer instanceof
const toUpload: any = isDev
    ? new Blob([await request.arrayBuffer()], { type: reqMime })
    : request.body
```

## Debugging

In `miniflare@3.103.0` it all boils down to the custom serializer having a broken import. The serializer located in `miniflare/dist/src/index.js` has an import of `ArrayBuffer` that fails the `instanceof` check:

```js
var structuredSerializableReducers = {
  ArrayBuffer(value) {
    if (value instanceof ArrayBuffer) {
      return [import_node_buffer.Buffer.from(value).toString("base64")];
    }
  }
}
```

**Comment by k-wakamatsu-tms** [comment]
This resolved the error.

```javascript
const headers = new Headers();
Object.entries(object.httpMetadata || {}).forEach(([key, value]) => {
  headers.set(key, value);
});
```

As shown [here](https://developers.cloudflare.com/r2/api/workers/workers-api-reference/#r2object-definition)
It states that object.writeHttpMetadata(headers) references httpMetadata, so I believe it's the same thing.

**Comment by dacaga** [comment]
FYI, I'm hitting the same bug on miniflare 4.20250617.4, when sending headers to the `onlyIf` property like so:
```ts
const object = await bucket.put(key, image, {
  onlyIf: new Headers([['if-none-match', '*']]),
});
```

**Comment by Zollerboy1** [comment]
Any news on this?
