### ISSUE TITLE
🐛 BUG: `ERR_RUNTIME_FAILURE` error when using `wrangler dev`

### ISSUE THREAD

**Issue by Helloyunho** [cloudflare/workers-sdk#6260]
FYI, I already made [a post in discord](https://discord.com/channels/595317990191398933/1261365846165688412/1261365846165688412) but no one was answering

### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.64.0 [Wrangler]

### What version of Node are you using?

22.0.0(now 22.4.1 since i upgraded it, but not fixed), but prefer bun 1.1.20

### What operating system and version are you using?

macOS Sequoia 15 dev beta 3

### Observed behavior
I get `ERR_RUNTIME_FAILURE` error when using `wrangler dev`
![CleanShot 2024-07-14 at 21 26 58@2x](https://github.com/user-attachments/assets/10053449-1bea-4a95-8272-1c631fb513b7)

### Expected behavior
Works without any error, ex) apply db, open dev server, etc.

### Steps to reproduce
- A minimal working subset of your worker code
```ts
import { Hono, type Context } from 'hono'
import { authHandler, initAuthConfig, type AuthConfig } from '@hono/auth-js'
import { PrismaAdapter } from '@auth/prisma-adapter'
import { PrismaClient } from '@prisma/client'
import { PrismaD1 } from '@prisma/adapter-d1'
import type { D1Database } from '@cloudflare/workers-types'
import users from './routes/users'

declare let env: {
  DB: D1Database
}

const app = new Hono()

const adapter = new PrismaD1(env.DB)
const prisma = new PrismaClient({ adapter })

function getAuthConfig(c: Context): AuthConfig {
  return {
    // auth config...
  }
}

app.use('*', initAuthConfig(getAuthConfig))
app.use('/api/auth/*', authHandler())
app.route('/api/users', users)

export default app

```
- A minimal working subset of your `wrangler.toml`
```toml
name = "[REDACTED]"
main = "api/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "[REDACTED]"
database_id = "[REDACTED]"
preview_database_id = "DB"
```
- Commands used to start your local dev server, including custom env and cli args
```sh
bunx wrangler dev # or npx wrangler dev, results are same
```
- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)
  - use the command `wrangler dev`, that's it

A git repo we can clone and run a test suite on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.

### Please provide any relevant error logs

```
# when using wrangler dev


 ⛅️ wrangler 3.64.0
-------------------

Using vars defined in .dev.vars
Your worker has access to the following bindings:
- D1 Databases:
  - DB: [REDACTED] (DB), Preview: (DB)
- Vars:
  - GOOGLE_ID: "(hidden)"
  - GOOGLE_SECRET: "(hidden)"
  - AUTH_SECRET: "(hidden)"
  - TEBI_ACCESS_ID: "(hidden)"
  - TEBI_ACCESS_SECRET: "(hidden)"
⎔ Starting local server...
╭────────────────────────────────────────────╮
│ [ open a[d open D[ turn off [ clear  [ to  │
│ ]browser, vtools,]local mode]console,]exit │
│                                            │
╰────────────────────────────────────────────╯
/Users/helloyunho/Projects/[REDACTED]/node_modules/wrangler/wrangler-dist/cli.js:29765
            throw a;
            ^

MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (/Users/helloyunho/Projects/[REDACTED]/node_modules/miniflare/dist/src/index.js:9178:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Mutex.runWith (/Users/helloyunho/Projects/[REDACTED]/node_modules/miniflare/dist/src/index.js:3521:16) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}

Node.js v22.4.1
```

**Comment by Helloyunho** [comment]
side note: I don't really have any other devices to test this so if you have problem replicating the issue let me know

**Comment by Helloyunho** [comment]
Fixed `EPIPE` error by manually(or more like forcibly) updating workerd but now new error...
`wrangler d1` works fine now though

**Comment by petebacondarwin** [comment]
We'll try to reproduce this. It is possible that Windows + Node 22 is not working right now.
Can you try using Node 18 and see if you still see the problem?

**Comment by Helloyunho** [comment]
> We'll try to reproduce this. It is possible that Windows + Node 22 is not working right now. Can you try using Node 18 and see if you still see the problem?

still getting the same error with Node 18.20.4

**Comment by stevezhu** [comment]
Fairly certain issue is caused by the update to workerd. The last version without the error is `workerd@1.20240614.0`.

**Comment by Helloyunho** [comment]
> From my testing, this issue seems to be caused by an update to workerd. The last version without the error is `workerd@1.20240614.0`, so the first version with the error seems to be `workerd@1.20240620.1`.
> 
> I'm getting the same error on Windows 11, Node v21.0.0
> 
> References: https://github.com/cloudflare/workerd/releases/tag/v1.20240620.0 https://github.com/cloudflare/workers-sdk/releases/tag/miniflare%403.20240620.0 https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.62.0

didn't work for me, even the old version has the same problem

**Comment by stevezhu** [comment]
> > From my testing, this issue seems to be caused by an update to workerd. The last version without the error is `workerd@1.20240614.0`, so the first version with the error seems to be `workerd@1.20240620.1`.
> > I'm getting the same error on Windows 11, Node v21.0.0
> > References: https://github.com/cloudflare/workerd/releases/tag/v1.20240620.0 https://github.com/cloudflare/workers-sdk/releases/tag/miniflare%403.20240620.0 https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.62.0
> 
> didn't work for me, even the old version has the same problem

Which version did you install? This config in package.json temporarily fixes it for me
```json
{
  "pnpm": {
    "overrides": {
      "workerd": "1.20240614.0"
    }
  }
}
```

**Comment by Helloyunho** [comment]
> > > From my testing, this issue seems to be caused by an update to workerd. The last version without the error is `workerd@1.20240614.0`, so the first version with the error seems to be `workerd@1.20240620.1`.
> > > I'm getting the same error on Windows 11, Node v21.0.0
> > > References: https://github.com/cloudflare/workerd/releases/tag/v1.20240620.0 https://github.com/cloudflare/workers-sdk/releases/tag/miniflare%403.20240620.0 https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.62.0
> > 
> > 
> > didn't work for me, even the old version has the same problem
> 
> Which version did you install? This config in package.json temporarily fixes it for me
> 
> ```json
> {
>   "pnpm": {
>     "overrides": {
>       "workerd": "1.20240614.0"
>     }
>   }
> }
> ```

still the exact same... nothing really changes

**Comment by stevezhu** [comment]
> > > > From my testing, this issue seems to be caused by an update to workerd. The last version without the error is `workerd@1.20240614.0`, so the first version with the error seems to be `workerd@1.20240620.1`.
> > > > I'm getting the same error on Windows 11, Node v21.0.0
> > > > References: https://github.com/cloudflare/workerd/releases/tag/v1.20240620.0 https://github.com/cloudflare/workers-sdk/releases/tag/miniflare%403.20240620.0 https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.62.0
> > > 
> > > 
> > > didn't work for me, even the old version has the same problem
> > 
> > 
> > Which version did you install? This config in package.json temporarily fixes it for me
> > ```json
> > {
> >   "pnpm": {
> >     "overrides": {
> >       "workerd": "1.20240614.0"
> >     }
> >   }
> > }
> > ```
> 
> still the exact same... nothing really changes

Ah not too sure then maybe your issue is caused by a different version. I'm running on Windows 11 so it might be different.

**Comment by Helloyunho** [comment]
so the same setup works on Ubuntu 24.04, I can use `bunx wrangler dev` without any issues

**Comment by GeKorm** [comment]
Had the same issue with `wrangler dev` and also `unstable_dev` in tests, but `"workerd": "1.20240614.0"` works. Windows 10, Node 20.15.1

**Comment by Helloyunho** [comment]
still having the same error on macOS...

**Comment by JustJoostNL** [comment]
Can confirm that it's an issue with workers, after adding the override it works for me.

**Comment by stevezhu** [comment]
For anyone who is having this issue on windows, this fixed it for me: https://github.com/cloudflare/workers-sdk/issues/6170#issuecomment-2239513454

**Comment by RamIdeas** [comment]
Thanks for confirming @stevezhu!

For others running into the same issue, please update Visual Studio C++ Redistributable 2015-2022 to version `14.40.33810`

**Comment by Helloyunho** [comment]
@RamIdeas This issue shouldn't be closed since it persists on macOS 15(now dev beta 4). Maybe you misread the issue and thought only Windows users got this error.

**Comment by Helloyunho** [comment]
Still persists on macOS 15 dev beta 6...

**Comment by petebacondarwin** [comment]
I'm moving this to the workerd repository because that is where we are likely to see a fix, assuming the problem is not a regression in the MacOS that needs to be resolved there.
