### ISSUE TITLE
🐛 BUG: 'ZedError: Input not instance of Response' from serviceBindings

### ISSUE THREAD

**Issue by luiz00martins** [cloudflare/workers-sdk#6323]
### Which Cloudflare product(s) does this pertain to?

Workers Vitest Integration

### What version(s) of the tool(s) are you using?

3.56.0 [Wrangler], 1.1.20 [Bun], 0.4.14 [vitest-pool-workers]

### What operating system and version are you using?

Windows 10

### Observed behavior
Returning a `Response` from `serviceBindings` biding generate a ZodError, failing to recognize the `Response`.

```ts
import {
  defineWorkersProject,
} from "@cloudflare/vitest-pool-workers/config"
import { Response } from "miniflare"

export default defineWorkersProject(async () => {
  return {
    test: {
      dir: "./test",
      poolOptions: {
        workers: {
          singleWorker: true,
          main: "./src/index.ts",
          wrangler: {
            configPath: "./wrangler.toml",
          },
          miniflare: {
            serviceBindings: {
              AUTH: async (_req, mf) => {
                await mf.ready
                return Response.json({ message: "Authentication done" }, { status: 200 })
              },
            },
          },
        },
      },
    },
  }
})
```

```ts
app.get('/', async (c) => {
  const res = await c.env.AUTH.fetch('http://localhost')

  if (res.status !== 200) {  // This fails with a 500 code
    console.error(await res.text()) // ZodError here
    return c.json({ message: 'Authentication failed' }, 401)
  }

  const json: { message: string } = await res.json()
  return c.json(json)
})
```

### Expected behavior
Correctly return the `Response`.

### To Reproduce
1. Clone repo below
2. Install packages with Bun 1.1.20 `bun install`
3. Run `bun run test`

### Please provide a link to a minimal reproduction

https://github.com/luiz00martins/vitest-pool-workers-error-project

### Please provide any relevant error logs

```
stderr | test/index.test.ts > Get user without Auth
ZodError: [
  {
    "code": "custom",
    "message": "Input not instance of Response",
    "fatal": true,
    "path": []
  }
]
    at get error [as error] (\vitest-pool-workers-error-project\node_modules\zod\lib\types.js:55:31)
    at ZodEffects.parse (\vitest-pool-workers-error-project\node_modules\zod\lib\types.js:160:22)
    at #handleLoopbackCustomService (\vitest-pool-workers-error-project\node_modules\@cloudflare\vitest-pool-workers\node_modules\miniflare\dist\src\index.js:8783:50)  
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async #handleLoopback (\vitest-pool-workers-error-project\node_modules\@cloudflare\vitest-pool-workers\node_modules\miniflare\dist\src\index.js:8824:20)
```

**Comment by penalosa** [comment]
`vitest-pool-workers` does not support bun test, and likely won't anytime soon. It relies on Vitest pools, which as far as I know aren't implemented by bun test, as well as Miniflare, which doesn't support Bun.

**Comment by luiz00martins** [comment]
@penalosa Does my MWE use `bun test`?

As far as I can see I'm using `bun run test`, which is running `vitest --run`
