### ISSUE TITLE
🐛 BUG: Applying the same migration with --local works but with remote doesn't  [ERR SQLITE_TOOBIG]

### ISSUE THREAD

**Issue by matrs** [cloudflare/workers-sdk#6347]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

3.67.1

### What version of Node are you using?

18.19.0

### What operating system and version are you using?

Linux Manjaro (arch)

### Describe the Bug
Applying a migration file with `--local` works, but with `--remote` fails. Also, when using:

### Observed behavior
```
#this works
npx wrangler d1 migrations apply prods --local
#this fails
npx wrangler d1 migrations apply prods --remote
✘ [ERROR] statement too long: SQLITE_TOOBIG [code: 7500]
```
Also, when exporting the local db created with the previous command, and exporting its result to
`remote` does work:
```
npx wrangler d1 export prods --output local_prods.sql --local
# This works 
npx wrangler d1 execute prods --file local_prods.sql --remote
```

### Expected behavior
Both migrations should work.

### Please provide any relevant error logs

```
--- 2024-07-26T15:54:18.020Z debug
🪵  Writing logs to "project_path/.config/.wrangler/logs/wrangler-2024-07-26_15-54-17_834.log"
---

--- 2024-07-26T15:54:18.020Z debug
Failed to load .env file ".env": Error: ENOENT: no such file or directory, open '.env'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at tryLoadDotEnv (/project_path/Workers/products/node_modules/wrangler/wrangler-dist/cli.js:157689:72)
    at loadDotEnv (/project_path/Workers/products/node_modules/wrangler/wrangler-dist/cli.js:157698:12)
    at /project_path/Workers/products/node_modules/wrangler/wrangler-dist/cli.js:202047:20
    at /project_path/Workers/products/node_modules/wrangler/wrangler-dist/cli.js:165855:16
    at maybeAsyncResult (/project_path/Workers/products/node_modules/wrangler/wrangler-dist/cli.js:164076:44)
    at /project_path/Workers/products/node_modules/wrangler/wrangler-dist/cli.js:165854:14
    at /project_path/Workers/products/node_modules/wrangler/wrangler-dist/cli.js:164063:22
    at Array.reduce (<anonymous>) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '.env'
}
---

--- 2024-07-26T15:54:18.035Z log

 ⛅️ wrangler 3.67.1
[38;2;255;136;0m-------------------[39m

---

--- 2024-07-26T15:54:18.036Z debug
No experimental flag store instantiated
---

--- 2024-07-26T15:54:18.036Z debug
Attempted to use flag "JSON_CONFIG_FILE" which has not been instantiated
---

--- 2024-07-26T15:54:20.446Z debug
Retrieving cached values for account from node_modules/.cache/wrangler
---

--- 2024-07-26T15:54:20.446Z log
🌀 Executing on remote database prods (33ed14de-2b06-4144-950a-8e41774c336a):
---

--- 2024-07-26T15:54:20.446Z log
🌀 To execute on your local development database, remove the --remote flag from your wrangler command.
---

--- 2024-07-26T15:54:20.477Z log
[90mNote: if the execution fails to complete, your DB will return to its original state and you can safely retry.[39m
---

--- 2024-07-26T15:54:20.479Z debug
-- START CF API REQUEST: POST https://api.cloudflare.com/client/v4/accounts/157d1f9b1a418fd25460607832819cfe/d1/database/33ed14de-2b06-4144-950a-8e41774c336a/import
---

--- 2024-07-26T15:54:20.479Z debug
HEADERS: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2024-07-26T15:54:20.479Z debug
INIT: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2024-07-26T15:54:20.479Z debug
-- END CF API REQUEST
---

--- 2024-07-26T15:54:21.610Z debug
-- START CF API RESPONSE: OK 200
---

--- 2024-07-26T15:54:21.611Z debug
HEADERS: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2024-07-26T15:54:21.611Z debug
RESPONSE: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2024-07-26T15:54:21.611Z debug
-- END CF API RESPONSE
---

--- 2024-07-26T15:54:23.460Z debug
-- START CF API REQUEST: POST https://api.cloudflare.com/client/v4/accounts/157d1f9b1a418fd25460607832819cfe/d1/database/33ed14de-2b06-4144-950a-8e41774c336a/import
---

--- 2024-07-26T15:54:23.461Z debug
HEADERS: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2024-07-26T15:54:23.461Z debug
INIT: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2024-07-26T15:54:23.461Z debug
-- END CF API REQUEST
---

--- 2024-07-26T15:54:24.343Z debug
-- START CF API RESPONSE: OK 200
---

--- 2024-07-26T15:54:24.343Z debug
HEADERS: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2024-07-26T15:54:24.343Z debug
RESPONSE: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2024-07-26T15:54:24.343Z debug
-- END CF API RESPONSE
---

--- 2024-07-26T15:54:24.345Z log

---

--- 2024-07-26T15:54:24.431Z error
[31m✘ [41;31m[[41;97mERROR[41;31m][0m [1mtable d1_migrations already exists at offset 14: SQLITE_ERROR[0m


---

--- 2024-07-26T15:54:24.432Z log
[32mIf you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose[0m
---

--- 2024-07-26T15:54:38.601Z debug
Sentry: Capturing exception Error: table d1_migrations already exists at offset 14: SQLITE_ERROR
---
```

**Comment by joshthoward** [comment]
You are likely running into this issue due to exceeding the maximum SQL statement length documented [here](https://developers.cloudflare.com/d1/platform/limits/). If you think that this is incorrect please reopen the issue. There are multiple reasons for this error to be thrown as mentioned [here](https://www.sqlite.org/rescode.html#toobig). You can break up your exported SQL statement into multiple files to work around.
