### ISSUE TITLE
🐛 BUG: Python without external libraries: python modules not supported [code: 10021]

### ISSUE THREAD

**Issue by PeterZhizhin** [cloudflare/workers-sdk#6613]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

wrangler 3.73.0

### What version of Node are you using?

10.8.3

### What operating system and version are you using?

Arch Linux

### Observed behavior
I'm trying to upload a python worker with source code here: https://github.com/PeterZhizhin/msk_deg_2024/tree/main/check_sid_bot_offline

I run the following command:
```
npx wrangler@latest deploy
```

See the log error I got below.

### Expected behavior
Worker gets deployed normally.

Moreover, I have been able to deploy this worker as-is on 2024.04.02 (April 2nd 2024). Now exactly the same command fails.

### Steps to reproduce
Please provide the following:
- Clone this repository: https://github.com/PeterZhizhin/msk_deg_2024/
- Navigate to https://github.com/PeterZhizhin/msk_deg_2024/tree/main/check_sid_bot_offline
- Create a Telegram Bot Token with @BotFather. Add the token as `TELEGRAM_BOT_TOKEN` environment variable.

### Please provide a link to a minimal reproduction

https://github.com/PeterZhizhin/msk_deg_2024/tree/main/check_sid_bot_offline

### Please provide any relevant error logs

```

$ npx wrangler@latest deploy                                                                                                                                                            

 ⛅️ wrangler 3.73.0
-------------------

▲ [WARNING] The entrypoint src/entry.py defines a Python worker, support for Python workers is currently experimental. Python workers with a requirements.txt file can only be run locally and cannot be deployed.


Attaching additional modules:
┌───────────────────┬────────┬──────────┐
│ Name              │ Type   │ Size     │
├───────────────────┼────────┼──────────┤
│ messages.py       │ python │ 0.70 KiB │
├───────────────────┼────────┼──────────┤
│ telegram.py       │ python │ 4.42 KiB │
├───────────────────┼────────┼──────────┤
│ Total (2 modules) │        │ 5.12 KiB │
└───────────────────┴────────┴──────────┘
Total Upload: 7.88 KiB / gzip: 2.38 KiB
Your worker has access to the following bindings:
- KV Namespaces:
  - TELEGRAM_USERS: <Redacted ID of KV storage>

✘ [ERROR] A request to the Cloudflare API (/accounts/<Redacted ID>/workers/scripts/check-sid-bot-offline/versions) failed.

  python modules not supported [code: 10021]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

**Comment by scrazzz** [comment]
Looks like others are facing the same issue, see #5608

**Comment by MilosNikolic** [comment]
I am facing this issue as well. I was also able to reproduce it with [hello world example](https://github.com/cloudflare/python-workers-examples/tree/main/01-hello). When i deploy the worker first time it works, but with when I try to re-deploy with any change it doesn't work. 

Same error message and i also have wrangler 3.76.0.

**Comment by kflansburg** [comment]
Hello, @MilosNikolic I'm not able to reproduce issues when deploying the hello world example multiple times. What error are you getting. 

@PeterZhizhin I believe that there may be a bug in our permissions for uploading modules, which should be permitted, we will investigate next week.

**Comment by kflansburg** [comment]
@PeterZhizhin I believe we released some changes last week which should have resolved this, can you try again?

**Comment by rhjensen79** [comment]
Any status on this ?
I'm getting the same error, when I do a basic test with a requirements file, with fastapi.

I'm following your example in https://blog.cloudflare.com/python-workers/

And I'm getting 
` ⛅️ wrangler 3.81.0
-------------------

▲ [WARNING] The entrypoint src/entry.py defines a Python worker, support for Python workers is currently experimental. Python workers with a requirements.txt file can only be run locally and cannot be deployed.`

Which is not what the blog post describes.

**Comment by rhjensen79** [comment]
> Any status on this ? I'm getting the same error, when I do a basic test with a requirements file, with fastapi.
> 
> I'm following your example in https://blog.cloudflare.com/python-workers/
> 
> ## And I'm getting
> ` ⛅️ wrangler 3.81.0
> ▲ [WARNING] The entrypoint src/entry.py defines a Python worker, support for Python workers is currently experimental. Python workers with a requirements.txt file can only be run locally and cannot be deployed.`
> 
> Which is not what the blog post describes.

Just updated Wrangler to 3.82.0
Same error. 

`✘ [ERROR] A request to the Cloudflare API (/accounts/1abcaa7d00a09e7d208cc58af0fe43d1/workers/scripts/hello-world-python-worker) failed.

  You cannot yet deploy Python Workers that depend on packages defined in requirements.txt. Support
  for Python packages is coming soon. [code: 10021]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose`

**Comment by thecapacity** [comment]
Hi, I'm seeing this same issue with a project I built last night - i.e. it should have an up to date Wrangler cloudflare@latest, etc.

The only thing in my requirements.txt is `fastapi`

here's the more detailed message 👇 

>   ▲ [WARNING] The entrypoint src/entry.py defines a Python worker, support for Python workers is currently experimental. Python workers with a requirements.txt file can only be run locally and cannot be deployed.
  
  Attaching additional modules:
  ┌──────────────────┬────────────────────┬──────────┐
   │ Name             │ Type               │ Size     │
  ├──────────────────┼────────────────────┼──────────┤
   │ fastapi          │ python-requirement │          │
  ├──────────────────┼────────────────────┼──────────┤
   │ Total (1 module) │                    │ 0.00 KiB │
  └──────────────────┴────────────────────┴──────────┘
  Total Upload: 1.20 KiB / gzip: 0.49 KiB
  Your worker has access to the following bindings:
  - KV Namespaces:
    - KV_ID: xxxxxxxxxxxxxxxxxxxxxxxx
  - Vars:
    - MESSAGE: "This is an environment variable"
  
  ✘ [ERROR] A request to the Cloudflare API (/accounts/A..C/workers/scripts/helloworld) failed.
  
    You cannot yet deploy Python Workers that depend on packages defined in requirements.txt. Support for Python packages is coming soon. [code: 10021]
    
    If you think this is a bug, please open an issue at: https://github.com/cloudflare/workers-sdk/issues/new/choose
  
Error: The process '/usr/local/bin/npx' failed with exit code 1
Error: 🚨 Action failed

**Comment by thecapacity** [comment]
Note, removing `fastapi` from the `requirements.txt` file isn't a solution

I thought perhaps it might be included in the basic library/models by default and not have to be specified: https://developers.cloudflare.com/workers/languages/python/packages/fastapi/

-------------------------
  ✘ [ERROR] A request to the Cloudflare API (/accounts/A.C/workers/scripts/helloworld) failed.
    Uncaught Error: PythonError: Traceback (most recent call last):
      File "/lib/python312.zip/_pyodide/_base.py", line 629, in pyimport_impl
        res = __import__(stem, fromlist=fromlist)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/session/metadata/entry.py", line 1, in <module>
        from fastapi import FastAPI, Request
    ModuleNotFoundError: No module named 'fastapi'
    
      at null.<anonymous> (pyodide-internal:generated/emscriptenSetup:453:14) in new_error
      at [object Object] in $wrap_exception
      at [object Object] in $pythonexc2js
      at null.<anonymous> (pyodide-internal:generated/emscriptenSetup:19389:128) in Module._pythonexc2js
      at null.<anonymous> (pyodide-internal:generated/emscriptenSetup:2860:29) in Module.callPyObjectKwargs
      at null.<anonymous> (pyodide-internal:generated/emscriptenSetup:2892:25) in Module.callPyObject
      at null.<anonymous> (pyodide-internal:generated/emscriptenSetup:3586:60) in apply
      at null.<anonymous> (pyodide-internal:generated/emscriptenSetup:3503:20) in apply
      at null.<anonymous> (pyodide-internal:generated/emscriptenSetup:4384:37) in pyimport
      at null.<anonymous> (pyodide:python-entrypoint-helper:17:20) in pyimportMainModule
     [code: 10021]
    
    If you think this is a bug, please open an issue at: https://github.com/cloudflare/workers-sdk/issues/new/choose
Error: The process '/usr/local/bin/npx' failed with exit code 1
Error: 🚨 Action failed

**Comment by dom96** [comment]
You cannot deploy Python workers that depend on packages yet. This is expected and isn't a bug, this support is forthcoming and just hasn't been released yet.

**Comment by rhjensen79** [comment]
> You cannot deploy Python workers that depend on packages yet. This is expected and isn't a bug, this support is forthcoming and just hasn't been released yet.

Thanks. But honestly, that is not obvious from the blot post  you are part of : https://blog.cloudflare.com/python-workers/

Any eta, on when me might start to see some support ? 

Thanks.

**Comment by SooditK** [comment]
hii @dom96 any idea on release of this? from when can we start deploying workers instead of just running them locally

**Comment by dom96** [comment]
@SooditK you can already deploy Python Workers, they just cannot use packages yet. We have a closed beta for the package support, if you want to join it you can reach out to us on our Discord https://discord.com/channels/595317990191398933/1224715939581530112.

**Comment by edmundhung** [comment]
Closing this as stale. Python Workers are now supported through `pywrangler`: https://developers.cloudflare.com/workers/languages/python/packages/

If you are still running into problems, please open a new issue.
