### ISSUE TITLE
🐛 BUG:TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute

### ISSUE THREAD

**Issue by kingwrcy** [cloudflare/workers-sdk#6617]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.73.0

### What version of Node are you using?

v20.12.0

### What operating system and version are you using?

Windows 10

### Describe the Bug

Nuxt3 with Cloudflare Pages ,when i dev in local envirment,will show error below.
```
npx wrangler pages dev dist/ --compatibility-flags="nodejs_compat"
```

```
✨ Compiled Worker successfully
Your worker has access to the following bindings:
- D1 Databases:
  - DB: huyanluanyu (b79db097-5795-4921-992f-22ef92857efb)
[wrangler:inf] Ready on http://127.0.0.1:8788
⎔ Starting local server...
✨ Parsed 0 valid redirect rules.
✨ Parsed 3 valid header rules.
F:\WebstormProjects\jabber\node_modules\.pnpm\wrangler@3.73.0\node_modules\wrangler\wrangler-dist\cli.js:29768
            throw a;
            ^

TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
    at getPathFromURLWin32 (node:internal/url:1432:11)
    at fileURLToPath (node:internal/url:1462:22)
    at tryFileURLToPath (F:\WebstormProjects\jabber\node_modules\.pnpm\@cspotcode+source-map-support@0.8.1\node_modules\@cspotcode\source-map-support\source-map-support.js:133:12)
    at retrieveSourceMapURL (F:\WebstormProjects\jabber\node_modules\.pnpm\@cspotcode+source-map-support@0.8.1\node_modules\@cspotcode\source-map-support\source-map-support.js:335:27)
    at Array.<anonymous> (F:\WebstormProjects\jabber\node_modules\.pnpm\@cspotcode+source-map-support@0.8.1\node_modules\@cspotcode\source-map-support\source-map-support.js:353:26)
    at F:\WebstormProjects\jabber\node_modules\.pnpm\@cspotcode+source-map-support@0.8.1\node_modules\@cspotcode\source-map-support\source-map-support.js:199:32
    at mapSourcePosition (F:\WebstormProjects\jabber\node_modules\.pnpm\@cspotcode+source-map-support@0.8.1\node_modules\@cspotcode\source-map-support\source-map-support.js:383:21)
    at wrapCallSite (F:\WebstormProjects\jabber\node_modules\.pnpm\@cspotcode+source-map-support@0.8.1\node_modules\@cspotcode\source-map-support\source-map-support.js:592:20)
    at prepareStackTrace (F:\WebstormProjects\jabber\node_modules\.pnpm\@cspotcode+source-map-support@0.8.1\node_modules\@cspotcode\source-map-support\source-map-support.js:671:41)
    at getSourceMappedString (F:\WebstormProjects\jabber\node_modules\.pnpm\wrangler@3.73.0\node_modules\wrangler\wrangler-dist\cli.js:161884:34) {
  code: 'ERR_INVALID_FILE_URL_PATH'
}

```

But use this command to start development `nuxt dev`,everything is ok.

**Comment by edmundhung** [comment]
Hi @kingwrcy , thanks for reporting this issue! Could you please provide more detailed steps to reproduce the error? If possible, could you also share a minimal repository that replicates the problem? This will help us investigate the issue further

Thanks in advance!

**Comment by lrapoport-cf** [comment]
hi @kingwrcy :) we haven't heard from you in a while, so we’re going to close this issue for now. if this is still a problem, please feel free to open a new issue referencing this one and please be sure to include a repro and we will revisit and investigate further. thanks!

**Comment by ultravires** [comment]
I meet it too. 
repo: [https://github.com/ultravires/requests.ultravires.me](https://github.com/ultravires/requests.ultravires.me)

## Which Cloudflare product(s) does this pertain to?
Wrangler

## What version(s) of the tool(s) are you using?
"wrangler": "^3.80.4"

What version of Node are you using?
node v20.18.0
pnpm 9.12.1

What operating system and version are you using?
Windows 11

**Comment by paulius1230** [comment]
@ultravires did you solve your issue? I'm experiencing this
