### ISSUE TITLE
🐛 BUG: Dynamic require of "node:stream" is not supported

### ISSUE THREAD

**Issue by jainkunal** [cloudflare/workers-sdk#6648]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.75.0 [Wrangler]

### What version of Node are you using?

20.14.0

### What operating system and version are you using?

Mac Sonoma 14.6.1

### Observed behavior
When try to run `wrangler deploy` or `wrangler dev` I get

✘ [ERROR] A request to the Cloudflare API (/accounts/44f10c0dd2f1a5b798f0c93766d4dc4c/workers/scripts/api) failed.

  Uncaught Error: Dynamic require of "node:stream" is not supported

### Expected behavior
It should deploy or run the code

### Steps to reproduce
Please provide the following:
- A minimal working subset of your `wrangler.toml`
```
name = "api"
main = "src/index.ts"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat_v2"]
```

The error seems to step from `unenv` package which is used as part of `wrangler` which nowhere in the code we use `unenv` or `streams`

### Please provide any relevant error logs

Uncaught Error: Dynamic require of "node:stream" is not supported
    at null.<anonymous> (worker.js:15:11)
    at null.<anonymous>
  (file:///Users/k/api/node_modules/unenv/runtime/node/console/index.mjs:1:26)
  in node_modules/unenv/runtime/node/console/index.mjs
    at null.<anonymous> (worker.js:18:61) in __init
    at null.<anonymous>
  (file:///Users/k/api/node_modules/unenv/runtime/node/console/$cloudflare.mjs:10:1)
  in node_modules/unenv/runtime/node/console/$cloudflare.mjs
    at null.<anonymous> (worker.js:18:61) in __init
    at null.<anonymous>
  (file:///Users/k/api/node_modules/wrangler/_virtual_unenv_global_polyfill-console.js:1:1)
  in node_modules/wrangler/_virtual_unenv_global_polyfill-console.js
    at null.<anonymous> (worker.js:18:61) in __init
    at null.<anonymous>
  (file:///Users/k/api/node_modules/unenv/runtime/polyfill/performance.mjs:1:1)
  in node_modules/unenv/runtime/polyfill/performance.mjs
    at init_performance (worker.js:18:61) in __init
    at null.<anonymous>
  (file:///Users/k/api/node_modules/wrangler/_virtual_unenv_global_polyfill-performance.js:1:1)
  in node_modules/wrangler/_virtual_unenv_global_polyfill-performance.js
   [code: 10021]

**Comment by andyjessop** [comment]
Hi @jainkunal, thanks very much for the issue! I'm unable to reproduce this locally - can you please provide a minimal reproduction in a repo for us to clone?

**Comment by Phara0h** [comment]
I am also getting this issue

```

 ⛅️ wrangler 3.78.4
-------------------

⎔ Starting local server...
[wrangler:inf] Ready on http://127.0.0.1:8787
X [ERROR] service core:user:my-app: Uncaught Error: Dynamic require of "node:stream" is not supported

    at null.<anonymous> (core:user:my-app:9:11)
    at null.<anonymous> (core:user:my-app:42:28)
    at null.<anonymous> (core:user:my-app:2701:3)


X [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.

```
|



Simple way to reproduce is `npm install hono`, and `wrangler dev` start this simple project 


```js
import { Hono } from 'hono'

const app = new Hono()

app.get('/', (c) => {
  return c.text('Hello Hono!')
})
```

**Comment by hetdagli234** [comment]
I'm getting the same error in my Next js app.

```
✘ [ERROR] A request to the Cloudflare API (/accounts/63bbbc30f7033782a1625c580bba7a2b/workers/scripts/solana-action-template) failed.

  Uncaught Error: Dynamic require of "node:stream" is not supported
    at null.<anonymous> (worker.js:1:492)
    at null.<anonymous>
```

Wrangler version: 3.78.5

The error originates from the unenv package. There was a version bump for unenv in the 3.78.5 release. However, that was not the issue as I deprecated Wrangler to 3.78.4, and the same issue was there.

**Comment by petebacondarwin** [comment]
The fix here is to identify when we are in Service Worker syntax mode and error early on code that contains external imports.

**Comment by tuliocaixeta** [comment]
same error here running the npm run deploy on .js code on index.mjs 
`"import { Writable } from "node:stream";"`


  Uncaught Error: Dynamic require of "node:stream" is not supported
    at null.<anonymous> (worker.js:9:11)
    at null.<anonymous>
  (file:///G:/projects/project/node_modules/unenv/runtime/node/console/index.mjs:1:26)
    at null.<anonymous> (worker.js:1004:3)
   [code: 10021]

**Comment by threepointone** [comment]
I believe requires should work otherwise in the runtime. We use 'iife' format when compiling a service worker, maybe that can be esm anyway, that might fix this issue.

**Comment by petebacondarwin** [comment]
> I believe requires should work otherwise in the runtime. We use 'iife' format when compiling a service worker, maybe that can be esm anyway, that might fix this issue.

I checked internally with the runtime team and they confirmed that even at runtime SW format Workers cannot have imports.

**Comment by threepointone** [comment]
Yeah but I think it can have requires?

**Comment by threepointone** [comment]
For posterity, I was wrong, can't do imports/requires in a Service Worker

**Comment by ikehoff** [comment]
Also having this issue. After running `npx wrangler deploy` the following error appears.

```
  Uncaught Error: Dynamic require of "node:stream" is not supported
    at null.<anonymous> (worker.js:9:11)
    at null.<anonymous>
  (file:///C:/Users/AdamEickhoff/OneDrive%20-%20Hard%20Rock%20Cafe%20International/Git/Wrangler/adam-wrangler-test/node_modules/unenv/runtime/node/console/index.mjs:1:26)
    at null.<anonymous> (worker.js:938:3)
   [code: 10021]
```

**Comment by petebacondarwin** [comment]
@ikehoff - Please try `wrangler@beta` since we just landed a fix that should make the error more clear.
