### ISSUE TITLE
🐛 BUG: Can't assign requested address; toString() = 192.168.1.146:8788

### ISSUE THREAD

**Issue by joseflekardal** [cloudflare/workers-sdk#6899]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.80.0 [wrangler]

### What version of Node are you using?

20.17.0

### What operating system and version are you using?

macOS Sequoia 15.0

### Observed behavior
I am not able to run my pages functions locally using Wrangler CLI.

I am running on macOS Sequoia 15.0 but I've seen the same error on Ventura, I've also tried multiple earlier versions of wrangler but they all seem to behave the same way.

Wrangler tries to bind to `192.168.1.146:8788` which is a weird default (I dont use a wrangler.toml file in this example). If i force it to use --ip '127.0.0.1' the command starts just fine but no requests come through, the logs are completely empty.

### Expected behavior
At this point I just want to see my hello world working.

#### Command
`wrangler pages dev . --log-level debug`

#### Folder structure
```shell
.
└── functions
    └── hello.js
```

hello.js is the standard hello world:

```js
export function onRequest(context) {
  return new Response("Hello, world!")
}
```

### Please provide any relevant error logs

```bash
 ⛅️ wrangler 3.80.0
-------------------

No experimental flag store instantiated
Attempted to use flag "JSON_CONFIG_FILE" which has not been instantiated
▲ [WARNING] No compatibility_date was specified. Using today's date: 2024-10-05.

  ❯❯ Add one to your wrangler.toml file: compatibility_date = "2024-10-05", or
  ❯❯ Pass it in your terminal: wrangler pages dev [<DIRECTORY>]
  --compatibility-date=2024-10-05
  
  See https://developers.cloudflare.com/workers/platform/compatibility-dates/ for more
  information.


Compiling worker to "/Users/username/project-name/.wrangler/tmp/pages-HFK0hz/functionsWorker-0.3034340515603402.mjs"...
✨ Compiled Worker successfully
Retrieving cached values for userId from node_modules/.cache/wrangler
Metrics dispatcher: Posting data {"type":"event","name":"build pages functions","properties":{}}
Using vars defined in .dev.vars
Metrics dispatcher: Posting data {"type":"event","name":"run dev","properties":{"local":true,"usesTypeScript":false}}
⎔ Starting local server...
workerd/util/symbolizer.c++:101: warning: Not symbolizing stack traces because $LLVM_SYMBOLIZER is not set. To symbolize stack traces, set $LLVM_SYMBOLIZER to the location of the llvm-symbolizer binary. When running tests under bazel, use `--test_env=LLVM_SYMBOLIZER=<path>`.
*** Fatal uncaught kj::Exception: kj/async-io-unix.c++:945: failed: ::bind(sockfd, &addr.generic, addrlen): Can't assign requested address; toString() = 192.168.1.146:8788
stack: 1100630bb 110062e59 11006120d 10d439185 10d439a0e 10d43a25a 10d43a96f 10d3db70f 110090e8d 11009109d 11008f688 11008f3a5 10d3c81e0 /usr/lib/dyld@62cc
Error in ProxyController: Could not connect to InspectorProxyWorker
 MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (/Users/username/.nvm/versions/node/v20.17.0/lib/node_modules/wrangler/node_modules/miniflare/dist/src/index.js:9828:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (/Users/username/.nvm/versions/node/v20.17.0/lib/node_modules/wrangler/node_modules/miniflare/dist/src/index.js:3627:16) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
=> Error contextual data: {
  config: {
    name: 'worker',
    compatibilityDate: '2024-10-05',
    compatibilityFlags: [],
    entrypoint: '/Users/username/project-name/.wrangler/tmp/pages-HFK0hz/functionsWorker-0.3034340515603402.mjs',
    directory: '/Users/username/project-name',
    bindings: {},
    migrations: [],
    triggers: [],
    env: undefined,
    build: {
      additionalModules: [],
      processEntrypoint: true,
      bundle: true,
      findAdditionalModules: undefined,
      minify: undefined,
      moduleRules: [],
      define: {},
      custom: [Object],
      jsxFactory: 'React.createElement',
      jsxFragment: 'React.Fragment',
      tsconfig: undefined,
      nodejsCompatMode: null,
      format: 'modules',
      moduleRoot: '/Users/username/project-name/.wrangler/tmp/pages-HFK0hz'
    },
    dev: {
      auth: [AsyncFunction: auth],
      remote: false,
      server: [Object],
      inspector: [Object],
      origin: [Object],
      liveReload: false,
      testScheduled: false,
      persist: ''
    },
    legacy: {
      site: undefined,
      legacyAssets: undefined,
      enableServiceEnvironments: false
    },
    unsafe: { capnp: undefined, metadata: undefined }
  },
  bundle: undefined
}
ProxyWorker miniflare options changed, reinstantiating...
Error in ProxyController: Failed to send message to InspectorProxyWorker: {"type":"reloadStart"}
 MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (/Users/username/.nvm/versions/node/v20.17.0/lib/node_modules/wrangler/node_modules/miniflare/dist/src/index.js:9828:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (/Users/username/.nvm/versions/node/v20.17.0/lib/node_modules/wrangler/node_modules/miniflare/dist/src/index.js:3627:16) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
=> Error contextual data: {
  config: {
    name: 'worker',
    compatibilityDate: '2024-10-05',
    compatibilityFlags: [],
    entrypoint: '/Users/username/project-name/.wrangler/tmp/pages-HFK0hz/functionsWorker-0.3034340515603402.mjs',
    directory: '/Users/username/project-name',
    bindings: {},
    migrations: [],
    triggers: [],
    env: undefined,
    build: {
      additionalModules: [],
      processEntrypoint: true,
      bundle: true,
      findAdditionalModules: undefined,
      minify: undefined,
      moduleRules: [],
      define: {},
      custom: [Object],
      jsxFactory: 'React.createElement',
      jsxFragment: 'React.Fragment',
      tsconfig: undefined,
      nodejsCompatMode: null,
      format: 'modules',
      moduleRoot: '/Users/username/project-name/.wrangler/tmp/pages-HFK0hz'
    },
    dev: {
      auth: [AsyncFunction: auth],
      remote: false,
      server: [Object],
      inspector: [Object],
      origin: [Object],
      liveReload: false,
      testScheduled: false,
      persist: ''
    },
    legacy: {
      site: undefined,
      legacyAssets: undefined,
      enableServiceEnvironments: false
    },
    unsafe: { capnp: undefined, metadata: undefined }
  },
  bundle: undefined
}
╭────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [c] clear console, [x] to exit                      │
╰────────────────────────────────────────────────────────────────────────────────────────────╯
/Users/username/.nvm/versions/node/v20.17.0/lib/node_modules/wrangler/wrangler-dist/cli.js:29768
            throw a;
            ^

MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (/Users/username/.nvm/versions/node/v20.17.0/lib/node_modules/wrangler/node_modules/miniflare/dist/src/index.js:9828:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (/Users/username/.nvm/versions/node/v20.17.0/lib/node_modules/wrangler/node_modules/miniflare/dist/src/index.js:3627:16) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}

**Comment by emily-shen** [comment]
Hey sorry for the delay getting back! This is really odd. I suspect this might have something to do your with your setup locally unfortunately. Does this also happen with a regular workers project, (e.g. if you create a basic hello-world project using `npx create-cloudflare@latest`), or if you use a different dev tool like vite?

**Comment by joseflekardal** [comment]
I get the same error when I create a new hello world app with `npx create-cloudflare@latest` and run it with `npm run dev`.

I tried running it with vite as you suggested, not sure I did it right though:
1. `npm install vite`
2. updated the dev script in package.json to `vite dev`
3. ran it with `npm run dev`

This is the output I got and the endpoint http://localhost:5173 gave 404:
```shell
➜  black-flower-39ce git:(main) ✗ npm run dev

> black-flower-39ce@0.0.0 dev
> vite dev


  VITE v5.4.11  ready in 148 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.

**Comment by emily-shen** [comment]
Thanks for trying that, helpful to know that it's not Pages-specific. Can you create a starter remix project following this (https://developers.cloudflare.com/workers/frameworks/framework-guides/remix/) and run `npm run dev` - that'll use vite not wrangler, so we can figure out if it's a wrangler issue or more general.

**Comment by joseflekardal** [comment]
Sure!

Not sure what to look for but the dev server starts and the remix landing page is working great.

**Comment by emily-shen** [comment]
Hm this is very odd. Have you got anything special set up in your hosts file? If you run `ping localhost` does that resolve to 127.0.0.1?

**Comment by joseflekardal** [comment]
localhost is answering when i ping it. i have a few aliases going on but nothing to fancy:

`127.0.0.1	localhost kubernetes.docker.internal pubapi career.local pubapi.local app.local`

**Comment by emily-shen** [comment]
Slightly grasping at straws here as we can't reproduce this on our end, got a couple of suggestions:
1. Can you send us the output of `npx wrangler dev --ip '127.0.0.1' --log-level=debug` with the hello world worker example?
2. Does it work for you on another computer? I appreciate this is very much not an ideal solution 😅

**Comment by andyjessop** [comment]
> Slightly grasping at straws here as we can't reproduce this on our end, got a couple of suggestions:
> 
> 1. Can you send us the output of `npx wrangler dev --ip '127.0.0.1' --log-level=debug` with the hello world worker example?
> 2. Does it work for you on another computer? I appreciate this is very much not an ideal solution 😅

The only other suggestion I have here is:

3. Are you working behind a firewall, or any other non-standard networking conditions?

**Comment by lrapoport-cf** [comment]
hi @joseflekardal :) we haven't heard from you in a while, so we’re going to close this issue for now. if this is still a problem, please feel free to open a new issue referencing this one. please be sure to include any updated info including details in response to @emily-shen and @andyjessop 's questions above, and we will revisit and investigate further. thanks!

**Comment by rohrig** [comment]
Hey, I had a similar issue and found the culprit. If in your /etc/hosts file, there is a domain between 127.0.0.1 and localhost it leads to this issue. 

**Faulty example:** ❌

/etc/hosts 
```
127.0.0.1 something.com localhost
```

<img width="1712" height="663" alt="Image" src="https://github.com/user-attachments/assets/7510eadc-26ad-487a-9a3c-14257c76a0a2" />

**Working example:** ✅
```
127.0.0.1  localhost something.com
```

Not every domain between 127.0.0.1 and localhost will cause this issue, but I can reliably cause the issue on an M1 Mac with the above.

**Comment by tak2hu** [comment]
> Hey, I had a similar issue and found the culprit. If in your /etc/hosts file, there is a domain between 127.0.0.1 and localhost it leads to this issue.

can confirms this works even though my hosts file was just plain ol `127.0.0.1	localhost` and `::1		localhost`

my error was:
```
*** Fatal uncaught kj::Exception: kj/async-io-unix.c++:945: failed: ::bind(sockfd, &addr.generic, addrlen): Cannot assign requested address; toString() = [::1]:8787
```

just commenting out the localhost lines worked fine then

Update:
Today for whatever reason it just always `listen EADDRNOTAVAIL: address not available 52.230.1.186:8787` and it didn't want to use the `--ip` flag at all. Even after restarting my laptop or creating a new project, still the same. I tried to put `127.0.0.1 localhost` in my /etc/hosts again but still made `::1 localhost` into a comment, it works again now. If I put `::1 localhost` wrangler just won't serve to :8787.
