### ISSUE TITLE
🐛 BUG: Cloudflare Worker Remix + Durable Object : MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start

### ISSUE THREAD

**Issue by hawkup** [cloudflare/workers-sdk#6988]
### Which Cloudflare product(s) does this pertain to?

Wrangler, Miniflare, Other

### What version(s) of the tool(s) are you using?

3.80.4

### What version of Node are you using?

22.2.0

### What operating system and version are you using?

macOS Sonoma 14.6.1

### Observed behavior
When starting the development server or building the Cloudflare Worker Remix project with DO bindings, the following error occurs
```
service core:user:__WRANGLER_EXTERNAL_DURABLE_OBJECTS_WORKER: Worker "core:user:__WRANGLER_EXTERNAL_DURABLE_OBJECTS_WORKER"'s binding "Counter" refers to a service "core:user:worker", but no such service is defined.
```

### Expected behavior
The project should start and build successfully with DO bindings, without any errors.

### Steps to reproduce
1. Clone the repository below or open this [Codesandbox](https://codesandbox.io/p/github/hawkup/my-remix-app/main?import=true)
2. Run pnpm dev or pnpm build to reproduce the error.

This setup follows the [Cloudflare Workers Remix Framework Guide](https://developers.cloudflare.com/workers/frameworks/framework-guides/remix/), with additional DO binding configurations added to wrangler.toml.
```
[[durable_objects.bindings]]
name = "COUNTERS"
class_name = "Counter"

[[migrations]]
tag = "v1"
new_classes = ["Counter"]
```

### Please provide a link to a minimal reproduction

https://github.com/hawkup/my-remix-app

### Please provide any relevant error logs

```
service core:user:__WRANGLER_EXTERNAL_DURABLE_OBJECTS_WORKER: Worker "core:user:__WRANGLER_EXTERNAL_DURABLE_OBJECTS_WORKER"'s binding "Counter" refers to a service "core:user:worker", but no such service is defined.
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (/project/workspace/node_modules/.pnpm/miniflare@3.20241004.0/node_modules/miniflare/dist/src/index.js:9842:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Mutex.runWith (/project/workspace/node_modules/.pnpm/miniflare@3.20241004.0/node_modules/miniflare/dist/src/index.js:3627:16)
    at async #waitForReady (/project/workspace/node_modules/.pnpm/miniflare@3.20241004.0/node_modules/miniflare/dist/src/index.js:9899:5)
    at async Miniflare2._getProxyClient (/project/workspace/node_modules/.pnpm/miniflare@3.20241004.0/node_modules/miniflare/dist/src/index.js:10023:5)
    at async Miniflare2.getBindings (/project/workspace/node_modules/.pnpm/miniflare@3.20241004.0/node_modules/miniflare/dist/src/index.js:10042:25)
    at async getPlatformProxy (/project/workspace/node_modules/.pnpm/wrangler@3.80.4_@cloudflare+workers-types@4.20241011.0/node_modules/wrangler/wrangler-dist/cli.js:217375:20)
    at async configureServer (/project/workspace/node_modules/.pnpm/@remix-run+dev@2.13.1_@remix-run+react@2.13.1_typescript@5.6.3_vite@5.4.9_wrangler@3.80.4/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:55:11)
    at async _createServer (file:///project/workspace/node_modules/.pnpm/vite@5.4.9/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:63069:20)
    at async configResolved (/project/workspace/node_modules/.pnpm/@remix-run+dev@2.13.1_@remix-run+react@2.13.1_typescript@5.6.3_vite@5.4.9_wrangler@3.80.4/node_modules/@remix-run/dev/dist/vite/plugin.js:748:27) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by emily-shen** [comment]
cc @edmundhung I think this is the durable object issue you were running into?

**Comment by edmundhung** [comment]
Hi @hawkup,

Sorry for the unclear error message. The Remix vite dev environment uses a [proxy](https://remix.run/docs/en/main/guides/vite#cloudflare-proxy) via the [getPlatformProxy](https://developers.cloudflare.com/workers/wrangler/api/#getplatformproxy) API, which supports bindings in Node.js with limitations. [Durable Objects](https://developers.cloudflare.com/workers/wrangler/api/#supported-bindings) are supported, but they must be defined in a separate Worker, with your Remix Worker pointing to it using the [script_name configuration](https://developers.cloudflare.com/workers/wrangler/configuration/#durable-objects), and run in a different terminal via [wrangler dev](https://developers.cloudflare.com/workers/wrangler/commands/#dev).

We understand the current limitations and are actively working to improve this experience. I hope this clarifies the issue—let me know if you still run into any problems.
