### ISSUE TITLE
🐛 BUG: Error with Rust 1.82.0 in Wrangler

### ISSUE THREAD

**Issue by agustfricke** [cloudflare/workers-sdk#7028]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

wrangler 3.81.0, rustc 1.82.0

### What version of Node are you using?

20.10.0

### What operating system and version are you using?

Ubuntu 22.04

### Observed behavior
When using Rust version 1.82.0, running npx wrangler dev or npx wrangler deploy can result in an error related to WebAssembly imports. The error message may vary slightly but typically includes.
✘ [ERROR] service core:user:rs-worker: Uncaught LinkError: WebAssembly.Instance(): Import #2 "./index_bg.js" "__wbg_fetch_bc7c8e27076a5c84": function import requires a callable at null.<anonymous> (shim.js:41:9)
✘ [ERROR] The Workers runtime failed to start. There is likely additional logging output above.

When downgrading to Rust version 1.81.0, the problem disappears and everything works as expected.

### Expected behavior
The runtime should start successfully when using npx wrangler dev or npx wrangler deploy without producing errors in the console.

### Steps to reproduce
Please provide the following:
- [A minimal working subset of your worker code](https://github.com/cloudflare/workers-rs/tree/main/examples/router)
- Run your project with different versions of Rust (e.g., Rust 1.81.0 and Rust 1.82.0) to observe the differences in behavior.

### Please provide any relevant error logs

✘ [ERROR] service core:user:rs-worker: Uncaught LinkError: WebAssembly.Instance(): Import #2 "./index_bg.js" "__wbg_fetch_bc7c8e27076a5c84": function import requires a callable at null.<anonymous> (shim.js:41:9)
✘ [ERROR] The Workers runtime failed to start. There is likely additional logging output above.

**Comment by LimesKey** [comment]
I have the same bug

**Comment by o-az** [comment]
same here. Tried running all the templates no success
