### ISSUE TITLE
🐛 BUG: `ReferenceError: __name is not defined` in `await page.evaluate(async () => {...}`

### ISSUE THREAD

**Issue by L480** [cloudflare/workers-sdk#7107]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler

### What version(s) of the tool(s) are you using?

3.83.0

### What version of Node are you using?

20.18.0

### What operating system and version are you using?

Ubuntu 22.04.5 LTS

### Observed behavior
[ReferenceError: __name is not defined](https://github.com/evanw/esbuild/issues/1031#top) worker exception after `wrangler deploy`.
I'm having this error inside of `await page.evaluate(async () => {...}` code for puppeteer. It adds `__name` to my arrow function for some reason. I think this is likely due to `minifyIdentifiers` in esbuild. This behavior appeared in wrangler 3.83.0. However, it is working in wrangler 3.78.12.

### Expected behavior
No minified function names in `await page.evaluate(async () => {...}`.

### Steps to reproduce
Please provide the following:
- A minimal working subset of your worker code
```typescript
import { Page } from '@cloudflare/puppeteer'

export async function scrapeDetails(page: Page) {
    await page.goto('https://example.com')
    const data = await page.evaluate(() => {
        function toNumber(str: string | undefined): number | undefined {
            const num = typeof str === 'string' ? str.replaceAll('.', '').replaceAll(',', '.').match(/[+-]?([0-9]*[.])?[0-9]+/) : false
            if (num) {
                return Number(num[0])
            } else {
                return undefined
            }
        }

        const table = document.getElementById('test')
        let metadata = {} as { test: number | undefined }
        if (table) {
            for (let item of table.getElementsByTagName('li')) {
                const data = item.innerText.split('\n')
                switch (data[0]) {
                    case 'test':
                        metadata.test = toNumber(data[1])
                        break
                }
            }
        }
        return metadata
    })
    return data
}
```

Get's bundled into:

```javascript
async function scrapeDetails(page) {
  await page.goto("https://example.com");
  const data = await page.evaluate(() => {
    function toNumber(str) {
      const num = typeof str === "string" ? str.replaceAll(".", "").replaceAll(",", ".").match(/[+-]?([0-9]*[.])?[0-9]+/) : false;
      if (num) {
        return Number(num[0]);
      } else {
        return void 0;
      }
    }
    __name(toNumber, "toNumber"); // <== This is the issue
    const table = document.getElementById("test");
    let metadata = {};
    if (table) {
      for (let item of table.getElementsByTagName("li")) {
        const data2 = item.innerText.split("\n");
        switch (data2[0]) {
          case "test":
            metadata.test = toNumber(data2[1]);
            break;
        }
      }
    }
    return metadata;
  });
  return data;
}
```
- A minimal working subset of your `wrangler.toml`
```toml
name = "my-app"
main = "src/index.ts"
compatibility_date = "2024-09-02"
logpush = false
tail_consumers = [{service = "law-ingestion"}]
compatibility_flags = [ "nodejs_compat" ]

[triggers]
crons = ["*/15 * * * *"]
```

**Comment by pchason** [comment]
I'm experiencing the same bug, although it occurs when page.waitForSelector() is called using wrangler 3.83.

**Comment by penalosa** [comment]
This looks like it was caused by https://github.com/cloudflare/workers-sdk/pull/6902, which was released in Wrangler 3.80.1. Reverting to 3.80.0 should work as a workaround for now, but this is definitely a bug we should fix. esbuild injects both the `__name()` fn definition and usage, and so it seems like Wrangler might be messing that up somehow?

**Comment by akngs** [comment]
A function passed to page.evaluate() as an argument runs in a separate in-browser context (Puppeteer). In this context, there is no __name() function, which results in the error __name is not defined. Since Puppeteer's page.evaluate() is essentially a hack, esbuild cannot detect this through static analysis alone. 😢

**Comment by udfordria** [comment]
I was able to solve the issue by using a string instead : https://github.com/puppeteer/puppeteer/issues/1665#issuecomment-354241717

**Comment by Zisan-uzum** [comment]
Im having same issue while trying to trigger recapctha callback function.

**Comment by pchason** [comment]
@ruifigueira is there a fix scheduled for cloudflare puppeteer similar to what you applied to cloudflare playwright?

I've tried these solutions to resolve but none work:

- [Stringify function](https://github.com/cloudflare/workers-sdk/issues/7107#issuecomment-2708644100)
- [`page.evaluateOnNewDocument(() => (window.__name = (func) => func))`](https://github.com/evanw/esbuild/issues/2605#issuecomment-2050808084)

As far as I can tell, esbuild is applying __name to functions non-user supplied page.evaluate() functions like these that are part of the puppeteer API __name(pollRaf, "pollRaf"). When puppeteer executes __name(pollRaf, "pollRaf") in the browser page, this error occurs:

Error: Evaluation failed: ReferenceError: __name is not defined
    at pollRaf (pptr://__puppeteer_evaluation_script__:51:35)
    at waitForPredicatePageFunction (pptr://__puppeteer_evaluation_script__:12:20)
    at pollRaf (pptr://__puppeteer_evaluation_script__:51:35)
    at waitForPredicatePageFunction (pptr://__puppeteer_evaluation_script__:12:20)
    at ExecutionContext._ExecutionContext_evaluate (file:///.wrangler/tmp/dev-9q0MIE/index.js:42513:11)
    at async WaitTask.rerun (file:///.wrangler/tmp/dev-9q0MIE/index.js:45408:17)

**Comment by ruifigueira** [comment]
@pchason here's a working example:

```ts
import puppeteer from "@cloudflare/puppeteer";

export default {
  async fetch(request, env): Promise<Response> {
		const browser = await puppeteer.launch(env.MYBROWSER);
		const page = await browser.newPage();
		function pageEvaluate(fn: Function) {
			return page.evaluate(`(() => { const __name = (target) => target; return (${fn.toString()})(); })()`);
		}

		const meaningOfLife = await pageEvaluate(() => {
			function meaningOfLife() {
				return 42;
			}
			return meaningOfLife();
		});
		return new Response(`The meaning of life is ${meaningOfLife}`);
},
} satisfies ExportedHandler<Env>;
```

**Comment by pchason** [comment]
Thanks for the quick response! Dropping your code into my app and reporting back.

**Comment by pchason** [comment]
@ruifigueira implementing the working example didn't solve for my use because pollRaf is being called by the puppeteer API before any pageEvaluate() functions I supply in my custom code. Inspecting it further, my guess is the **bolded** line this snippet of code,  produced after running $ wrangler deploy --dry-run, is the what's causing the ReferenceError:

```
async function pollRaf() {
    **let fulfill = /* @__PURE__ */ __name((_2) => {
    }, "fulfill");**
    const result = new Promise((x2) => {
      return fulfill = x2;
    });
    await onRaf();
    return result;
    async function onRaf() {
      if (timedOut) {
        fulfill();
        return;
      }
      const success = predicateAcceptsContextElement ? await predicate(root, ...args) : await predicate(...args);
      if (success) {
        fulfill(success);
      } else {
        requestAnimationFrame(onRaf);
      }
    }
    __name(onRaf, "onRaf");
  }
```

**Comment by ruifigueira** [comment]
Can you provide your original code, without `__name` calls?

**Comment by ruifigueira** [comment]
This should be fixed by now since `@cloudflare/puppeteer@1.0.2`: https://github.com/cloudflare/puppeteer/pull/114/commits/f4f87996d1662969bbd161f12267ceb4836b4f26

**Comment by L480** [comment]
Same issue with @cloudflare/puppeteer@1.0.2.

**Comment by ruifigueira** [comment]
@L480 can you provide a code snippet reproducting the issue?

**Comment by penalosa** [comment]
We've since added a `config.keep_names` option. If you set it to `false`, that should resolve this issue: https://github.com/cloudflare/workers-sdk/pull/8771
