### ISSUE TITLE
🐛 BUG: svelte c3 quickstart with lucia fails

### ISSUE THREAD

**Issue by rawwerks** [cloudflare/workers-sdk#7213]
### Which Cloudflare product(s) does this pertain to?

C3 (npm create cloudflare)

### What version(s) of the tool(s) are you using?

2.32.0 (@latest)

### What version of Node are you using?

v18.13.0

### What operating system and version are you using?

Sonoma 14.2

### Describe the Bug

I'm 99% sure the problem is related to lucia and/or drizzle (because apparently lucia requires drizzle).

### Observed behavior
See error below missing `@node-rs/argon2-wasm-32-wasi`

### Expected behavior
A working demo. 

### Steps to reproduce
┌  Welcome to the Svelte CLI! (v0.6.1)
│
◇  Which template would you like?
│  SvelteKit minimal
│
◇  Add type checking with Typescript?
│  Yes, using Typescript syntax
│
◆  Project created
│
◇  What would you like to add to your project? (use arrow keys / space bar)
│  tailwindcss, lucia
│
◇  The lucia add-on requires drizzle to also be setup. Include it?
│  Yes
│
◇  tailwindcss: Which plugins would you like to add?
│  typography
│
◇  lucia: Do you want to include a demo? (includes a login/register page)
│  Yes
│
◇  drizzle: Which database would you like to use?
│  SQLite
│
◇  drizzle: Which SQLite client would you like to use?
│  libSQL
│
◇  Which package manager do you want to install dependencies with?
│  yarn

### Please provide any relevant error logs

```
(base) user@computer ~ % bun create cloudflare@latest svelte-cf-scratch-3 --framework=svelte

──────────────────────────────────────────────────────────────────────────────────────────────────────────
👋 Welcome to create-cloudflare v2.32.0!
🧡 Let's get started.
📊 Cloudflare collects telemetry about your usage of Create-Cloudflare.

Learn more at: https://github.com/cloudflare/workers-sdk/blob/main/packages/create-cloudflare/telemetry.md
──────────────────────────────────────────────────────────────────────────────────────────────────────────

╭ Create an application with Cloudflare Step 1 of 3
│ 
├ In which directory do you want to create your application?
│ dir ./svelte-cf-scratch-3
│
├ What would you like to start with?
│ category Framework Starter
│
├ Which development framework do you want to use?
│ framework SvelteKit
│
├ Continue with SvelteKit via `bunx sv@0.6.1 create svelte-cf-scratch-3`
│

┌  Welcome to the Svelte CLI! (v0.6.1)
│
◇  Which template would you like?
│  SvelteKit minimal
│
◇  Add type checking with Typescript?
│  Yes, using Typescript syntax
│
◆  Project created
│
◇  What would you like to add to your project? (use arrow keys / space bar)
│  tailwindcss, lucia
│
◇  The lucia add-on requires drizzle to also be setup. Include it?
│  Yes
│
◇  tailwindcss: Which plugins would you like to add?
│  typography
│
◇  lucia: Do you want to include a demo? (includes a login/register page)
│  Yes
│
◇  drizzle: Which database would you like to use?
│  SQLite
│
◇  drizzle: Which SQLite client would you like to use?
│  libSQL
│
◇  Which package manager do you want to install dependencies with?
│  yarn
│
◆  Successfully setup add-ons
│
◇  Successfully installed dependencies
│
◇  Project next steps ─────────────────────────────────────────────────────╮
│                                                                          │
│  1: cd svelte-cf-scratch-3                                               │
│  2: git init && git add -A && git commit -m "Initial commit" (optional)  │
│  3: yarn dev --open                                                      │
│                                                                          │
│  To close the dev server, hit Ctrl-C                                     │
│                                                                          │
│  Stuck? Visit us at https://svelte.dev/chat                              │
│                                                                          │
├──────────────────────────────────────────────────────────────────────────╯
│
◇  Add-on next steps ──────────────────────────────────────────────────╮
│                                                                      │
│  lucia:                                                              │
│  - Run yarn run db:push to update your database schema               │
│  - Visit /demo/lucia route to view the demo                          │
│                                                                      │
│  drizzle:                                                            │
│  - You will need to set DATABASE_URL in your production environment  │
│  - Run yarn run db:push to update your database schema               │
│                                                                      │
├──────────────────────────────────────────────────────────────────────╯
│
└  You're all set!


├ Copying template files 
│ files copied to project directory
│ 
├ Installing dependencies 
│ installed via `bun install`
│ 
╰ Application created 

╭ Configuring your application for Cloudflare Step 2 of 3
│ 
├ Installing wrangler A command line tool for building Cloudflare Workers 
│ installed via `bun install wrangler --save-dev`
│ 
├ Installing @cloudflare/workers-types 
│ installed via bun
│ 
├ Adding latest types to `tsconfig.json` 
│ added @cloudflare/workers-types/2023-07-01
│ 
├ Retrieving current workerd compatibility date 
│ compatibility date 2024-11-06
│ 
├ Adding the Cloudflare Pages adapter 
│ installed @sveltejs/adapter-cloudflare
│ 
├ Changing adapter in svelte.config.js
│
├ Updating global type definitions in app.d.ts
│
├ Adding Wrangler files to the .gitignore file 
│ updated .gitignore file
│ 
├ Updating `package.json` scripts 
│ updated `package.json`
│ 
├ Do you want to use git for version control?
│ yes git
│
├ Initializing git repo 
│ initialized git
│ 
├ Committing new files 
│ git commit
│ 
╰ Application configured 

╭ Deploy with Cloudflare Step 3 of 3
│ 
├ Do you want to deploy your application?
│ yes deploy via `bun run deploy`
│
├ Logging into Cloudflare checking authentication status 
│ logged in
│ 
├ Selecting Cloudflare account retrieving accounts 
│ account [REDACTED]'s Account
│ 
├ Creating Pages project 
│ created via `bunx wrangler pages project create svelte-cf-scratch-3 --production-branch master`
│ 
├ Verifying Pages project 
│ verified project is ready for deployment
│ 
.svelte-kit/output/server/entries/pages/_layout.svelte.js                     0.24 kB
.svelte-kit/output/server/internal.js                                         0.35 kB
.svelte-kit/output/server/chunks/shared-server.js                             0.44 kB
.svelte-kit/output/server/entries/pages/demo/lucia/_page.svelte.js            0.44 kB
.svelte-kit/output/server/entries/pages/demo/lucia/login/_page.svelte.js      0.59 kB
.svelte-kit/output/server/entries/pages/demo/lucia/_page.server.ts.js         0.61 kB
.svelte-kit/output/server/chunks/hooks.server.js                              0.71 kB
.svelte-kit/output/server/chunks/client.js                                    0.74 kB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js                   0.98 kB
.svelte-kit/output/server/chunks/index2.js                                    2.34 kB
.svelte-kit/output/server/entries/pages/demo/lucia/login/_page.server.ts.js   3.09 kB
.svelte-kit/output/server/chunks/auth.js                                      3.12 kB
.svelte-kit/output/server/chunks/exports.js                                   6.09 kB
.svelte-kit/output/server/chunks/internal.js                                 18.06 kB
.svelte-kit/output/server/chunks/index.js                                    24.74 kB
.svelte-kit/output/server/index.js                                           93.23 kB
✓ built in 5.83s

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-cloudflare
✘ [ERROR] Could not resolve "@node-rs/argon2-wasm32-wasi"

    node_modules/@node-rs/argon2/browser.js:1:14:
      1 │ export * from '@node-rs/argon2-wasm32-wasi'
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@node-rs/argon2-wasm32-wasi" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.


error during build:
Error: Bundling with esbuild failed with 1 error
    at adapt (file:///Users/user/svelte-cf-scratch-3/node_modules/@sveltejs/adapter-cloudflare/index.js:140:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async adapt (file:///Users/user/svelte-cf-scratch-3/node_modules/@sveltejs/kit/src/core/adapt/index.js:38:2)
    at async finalise (file:///Users/user/svelte-cf-scratch-3/node_modules/@sveltejs/kit/src/exports/vite/index.js:924:7)
    at async Object.handler (file:///Users/user/svelte-cf-scratch-3/node_modules/@sveltejs/kit/src/exports/vite/index.js:954:5)
    at async PluginDriver.hookParallel (file:///Users/user/svelte-cf-scratch-3/node_modules/rollup/dist/es/shared/node-entry.js:20729:17)
    at async Object.close (file:///Users/user/svelte-cf-scratch-3/node_modules/rollup/dist/es/shared/node-entry.js:21705:13)
    at async build (file:///Users/user/svelte-cf-scratch-3/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:65466:17)
    at async CAC.<anonymous> (file:///Users/user/svelte-cf-scratch-3/node_modules/vite/dist/node/cli.js:828:5)
error: script "build" exited with code 1
error: script "deploy" exited with code 1
```

**Comment by edmundhung** [comment]
Closing as Lucia is now deprecated and is no longer an add-on offered from the `sv` cli.
