### ISSUE TITLE
🐛 BUG: npm create cloudflare with NixOS fails following normal instructions

### ISSUE THREAD

**Issue by BridgerB** [cloudflare/workers-sdk#7329]
### Which Cloudflare product(s) does this pertain to?

C3 (npm create cloudflare)

### What version(s) of the tool(s) are you using?

3.90.0 [wrangler], 2.33.0 [c3]

### What version of Node are you using?

v20.17.0

### What operating system and version are you using?

NixOS Unstable

### Observed behavior
following this guide:
https://developers.cloudflare.com/pages/framework-guides/deploy-a-svelte-site/
I ran:
```
npm create cloudflare@latest -- my-svelte-app --framework=svelte
```
I selected the SvelteKit demo template (as the guide said to do)
with Typescript
npm
Do you want to deploy your application? yes

then it builds and then throws this error:
```
✓ built in 732ms

node:internal/event_target:1094
  process.nextTick(() => { throw err; });
                           ^
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:161:15)
    at writeGeneric (node:internal/stream_base_commons:152:3)
    at Socket._writeGeneric (node:net:954:11)
    at Socket._write (node:net:966:8)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Writable.write (node:internal/streams/writable:508:10)
    at Runtime.updateConfig (/home/bridger/github/sandbox/node_modules/miniflare/dist/src/index.js:4953:26)
    at async #assembleAndUpdateConfig (/home/bridger/github/sandbox/node_modules/miniflare/dist/src/index.js:9976:30)
    at async Mutex.runWith (/home/bridger/github/sandbox/node_modules/miniflare/dist/src/index.js:3632:16)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v20.17.0
╰  ERROR  Error
bridger@nixos:~/github/ > 
```

### Expected behavior
The command to build and deploy without failing when following default instructions.

### Steps to reproduce
Follow https://developers.cloudflare.com/pages/framework-guides/deploy-a-svelte-site/ 
and run
```
npm create cloudflare@latest -- sandbox --framework=svelte
```

**Comment by emily-shen** [comment]
Hi, I'm unable to reproduce this unfortunately, although admittedly I'm not running a nix setup. Would be great to get a few more details from you to narrow down the cause though - does this happen as well if you run `create-cloudflare` with another framework, say remix? With svelte, if you _don't_ deploy, when prompted, are you able to run the demo app locally with `npm run dev`? Thanks :))

**Comment by liperium** [comment]
I have the same problem here. NixOs Unstable. 
Running `npm create cloudflare@latest -- my-svelte-app --framework=svelte`
Selecting all defaults 

If I try to deploy `npm run deploy` or run dev `npm run dev` :

```
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:159:15)
    at writeGeneric (node:internal/stream_base_commons:150:3)
    at Socket._writeGeneric (node:net:957:11)
    at Socket._write (node:net:969:8)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Writable.write (node:internal/streams/writable:508:10)
    at Runtime.updateConfig (/home/liperium/Programming/Personnal/my-svelte-app/node_modules/miniflare/dist/src/index.js:4953:26)
    at async #assembleAndUpdateConfig (/home/liperium/Programming/Personnal/my-svelte-app/node_modules/miniflare/dist/src/index.js:9976:30)
    at async Mutex.runWith (/home/liperium/Programming/Personnal/my-svelte-app/node_modules/miniflare/dist/src/index.js:3632:16) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

**Comment by BridgerB** [comment]
I tried the command in an archlinux vm on my NixOS machine and it worked there. This must be a NixOS problem not being able to call something inside of miniflare.

**Comment by BridgerB** [comment]
I was able to get 
```
npm create cloudflare@latest -- my-svelte-app --framework=svelte
```
running my adding 
```
programs.nix-ld.enable = true;
```
to my configuration.nix. This a nix way of slapping a bandaid on things but it works for now.

**Comment by liperium** [comment]
That is not a fix, means there's an external dependency to the project than node, that you have installed on your system.

**Comment by BridgerB** [comment]
It is A fix. Let me know if you get the other fix working.

**Comment by nektro** [comment]
i also needed to create this `shell.nix`

```nix
with import <nixpkgs> {};

pkgs.mkShell {
  nativeBuildInputs = with pkgs; [
    nodejs_22
  ];

  hardeningDisable = [ "all" ];

  NIX_LD = lib.fileContents "${stdenv.cc}/nix-support/dynamic-linker";
}
```
