### ISSUE TITLE
🐛 BUG: Cloudflare Workflows: MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start

### ISSUE THREAD

**Issue by cah4a** [cloudflare/workers-sdk#7414]
### Which Cloudflare product(s) does this pertain to?

Miniflare, Other

### What version(s) of the tool(s) are you using?

0.5.32 [@cloudflare/vitest-pool-workers], 3.91.0 [wrangler]

### What version of Node are you using?

22.9.0

### What operating system and version are you using?

MacOs Ventura

### Observed behavior
Vitests doesn't run if wrangler toml contains workflows and following error occurs:
```
Worker "workflows:webhook-workflow"'s binding "USER_WORKFLOW" refers to service "core:user:vitest-pool-workers-runner-" with a named entrypoint "WebhookWorkflow", but "core:user:vitest-pool-workers-runner-" has no such named entrypoint.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
 ❯ #assembleAndUpdateConfig node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js:9983:13
 ❯ process.processTicksAndRejections node:internal/process/task_queues:105:5
 ❯ Mutex.runWith node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js:3632:16
 ❯ #waitForReady node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js:10040:5
 ❯ getProjectMiniflare node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.32_@cloudflare+workers-types@4.20241127.0_@vitest+runner@_hwo7pvv77thpfn5lwl6xtnhhae/node_modules/@cloudflare/vitest-pool-workers/dist/pool/index.mjs:1430:5
 ❯ Object.runTests node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.32_@cloudflare+workers-types@4.20241127.0_@vitest+runner@_hwo7pvv77thpfn5lwl6xtnhhae/node_modules/@cloudflare/vitest-pool-workers/dist/pool/index.mjs:1683:20
 ❯ executeTests node_modules/.pnpm/vitest@2.0.5_@types+node@22.10.1/node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js:9330:5
 ❯ node_modules/.pnpm/vitest@2.0.5_@types+node@22.10.1/node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js:14935:9

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { code: 'ERR_RUNTIME_FAILURE' }
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 Test Files  no tests
      Tests  no tests
     Errors  1 error
   Start at  21:04:10
   Duration  140ms (transform 0ms, setup 0ms, collect 0ms, tests 0ms, environment 0ms, prepare 0ms)


 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
Cancelling test run. Press CTRL+c again to exit forcefully.

[vpw:dbg] Shutting down runtimes...
error during close MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (/Users/cah4a/work/unknown-project/node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js:9983:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (/Users/cah4a/work/unknown-project/node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js:3632:16)
    at async #waitForReady (/Users/cah4a/work/unknown-project/node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js:10040:5)
    at async Promise.all (index 0)
    at async getProjectMiniflare (file:///Users/cah4a/work/unknown-project/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.32_@cloudflare+workers-types@4.20241127.0_@vitest+runner@_hwo7pvv77thpfn5lwl6xtnhhae/node_modules/@cloudflare/vitest-pool-workers/dist/pool/index.mjs:1430:5)
    at async Object.runTests (file:///Users/cah4a/work/unknown-project/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.32_@cloudflare+workers-types@4.20241127.0_@vitest+runner@_hwo7pvv77thpfn5lwl6xtnhhae/node_modules/@cloudflare/vitest-pool-workers/dist/pool/index.mjs:1683:20)
    at async Promise.all (index 5)
    at async executeTests (file:///Users/cah4a/work/unknown-project/node_modules/.pnpm/vitest@2.0.5_@types+node@22.10.1/node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js:9330:5)
    at async file:///Users/cah4a/work/unknown-project/node_modules/.pnpm/vitest@2.0.5_@types+node@22.10.1/node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js:14935:9 {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined,
  type: 'Unhandled Error',
  stacks: [
    {
      method: '#assembleAndUpdateConfig',
      file: '/Users/cah4a/work/unknown-project/node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js',
      line: 9983,
      column: 13
    },
    {
      method: 'process.processTicksAndRejections',
      file: '/Users/cah4a/work/unknown-project/node:internal/process/task_queues',
      line: 105,
      column: 5
    },
    {
      method: 'Mutex.runWith',
      file: '/Users/cah4a/work/unknown-project/node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js',
      line: 3632,
      column: 16
    },
    {
      method: '#waitForReady',
      file: '/Users/cah4a/work/unknown-project/node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js',
      line: 10040,
      column: 5
    },
    {
      method: 'getProjectMiniflare',
      file: '/Users/cah4a/work/unknown-project/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.32_@cloudflare+workers-types@4.20241127.0_@vitest+runner@_hwo7pvv77thpfn5lwl6xtnhhae/node_modules/@cloudflare/vitest-pool-workers/dist/pool/index.mjs',
      line: 1430,
      column: 5
    },
    {
      method: 'Object.runTests',
      file: '/Users/cah4a/work/unknown-project/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.32_@cloudflare+workers-types@4.20241127.0_@vitest+runner@_hwo7pvv77thpfn5lwl6xtnhhae/node_modules/@cloudflare/vitest-pool-workers/dist/pool/index.mjs',
      line: 1683,
      column: 20
    },
    {
      method: 'executeTests',
      file: '/Users/cah4a/work/unknown-project/node_modules/.pnpm/vitest@2.0.5_@types+node@22.10.1/node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js',
      line: 9330,
      column: 5
    },
    {
      method: '',
      file: '/Users/cah4a/work/unknown-project/node_modules/.pnpm/vitest@2.0.5_@types+node@22.10.1/node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js',
      line: 14935,
      column: 9
    }
  ]
}

```

### Expected behavior
Vitests does run if wrangler toml contains workflows.

### Steps to reproduce
1) Generate empty project using `pnpm create cloudflare@latest`
2) Add workflow as described on the [guide](https://developers.cloudflare.com/workflows/get-started/guide/)
3) pnpm vitest
4) Observe error

### Please provide a link to a minimal reproduction

https://github.com/cah4a/cloudflare-workers-workflows-vitest

**Comment by Hebilicious** [comment]
Does anyone have a workaround?

**Comment by skorfmann** [comment]
would be curious as well 👀

**Comment by sam-rusty** [comment]
this is kind of a roadblock for use to use workflow. any update?

**Comment by bruxodasilva** [comment]
This is in the roadmap for Workflows. I cannot commit with any timeframe, but rest assured it is on the top of our priorities.

**Comment by cah4a** [comment]
@sam-rusty @Hebilicious 

Workaround is to configure workflows under envs:
```toml
[[workflows]]
# Don't put anything here or tests will fail

[[env.dev.workflows]]
name = "webhook-workflow-dev"
binding = "WEBHOOK_WORKFLOW"
class_name = "WebhookWorkflow"
```

**Comment by bhanuka-yd** [comment]
blocked by this as well

**Comment by cabralcaio** [comment]
Could you please provide any updates on this? This is a big blocker for us...

**Comment by advany** [comment]
+1

**Comment by penalosa** [comment]
This was addressed in https://github.com/cloudflare/workers-sdk/pull/10494
