### ISSUE TITLE
🐛 BUG:Could not start vitest when using Cloudflare Vectorize, AI, and other wrapped bindings

### ISSUE THREAD

**Issue by Code-Hex** [cloudflare/workers-sdk#7434]
### Which Cloudflare product(s) does this pertain to?

Workers AI, Wrangler, Miniflare

### What version(s) of the tool(s) are you using?

3.91.0

### What version of Node are you using?

v22.9.0

### What operating system and version are you using?

macOS 14.5

### Observed behavior

Could not run test with vitest and @cloudflare/vitest-pool-workers

### Expected behavior

Run test

### Steps to reproduce

Run test with `vitest-pool-workers` (version 0.5.32)

Write vector config in wrangler.toml

```
[[vectorize]]
binding = "VECTORIZE"
index_name = "webapp-dev"
```

Write vitest.config.ts

```ts
import { defineWorkersProject } from "@cloudflare/vitest-pool-workers/config";

export default defineWorkersProject({
  esbuild: {
    // Required for `using` support
    target: "ES2022",
  },
  test: {
    globals: false,
    include: ["**/src/**/(*.)+(spec|test).+(ts|tsx)"],
    poolOptions: {
      workers: {
        singleWorker: true,
        wrangler: {
          configPath: "./wrangler.toml",
        },
      },
    },
  },
});
```

### Please provide any relevant error logs

```
> vitest --run


 RUN  v2.1.6 /Users/codehex/go/src/github.com/codehex/webapp/workers/webapp

Using vars defined in .dev.vars
[vpw:inf] Starting single runtime for vitest.config.ts...
workerd/server/workerd-api.c++:797: error: wrapped binding module can't be resolved (internal modules only); moduleName = miniflare-internal:wrapped:__WRANGLER_EXTERNAL_VECTORIZE_WORKERVECTORIZE
workerd/jsg/util.c++:274: error: e = workerd/server/workerd-api.c++:827: failed: expected !value.IsEmpty(); global did not produce v8::Value
stack: 102b6d2a3 10311f267 103103fbf 102b0fe47 102b16517 102b19ea7 102b185ef 102b094e7 10546c2c7 10546c5cb 10546aeef 10546ac87 102af87c3 1917220df; sentryErrorContext = jsgInternalError
service core:user:vitest-pool-workers-runner-: Uncaught Error: internal error

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
 ❯ #assembleAndUpdateConfig ../../node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js:9983:13
 ❯ process.processTicksAndRejections node:internal/process/task_queues:105:5
 ❯ Mutex.runWith ../../node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js:3632:16
 ❯ #waitForReady ../../node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js:10040:5
 ❯ getProjectMiniflare ../../node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.32_@cloudflare+workers-types@4.20241127.0_@vitest+runner@_rspzct5a3s4gq7qtap7afu3hsu/node_modules/@cloudflare/vitest-pool-workers/dist/pool/index.mjs:1430:5
 ❯ Object.runTests ../../node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.32_@cloudflare+workers-types@4.20241127.0_@vitest+runner@_rspzct5a3s4gq7qtap7afu3hsu/node_modules/@cloudflare/vitest-pool-workers/dist/pool/index.mjs:1683:20
 ❯ executeTests ../../node_modules/.pnpm/vitest@2.1.6_@types+node@22.0.0_jiti@1.21.6_yaml@2.6.1/node_modules/vitest/dist/chunks/resolveConfig.RxKrDli4.js:7680:5
 ❯ ../../node_modules/.pnpm/vitest@2.1.6_@types+node@22.0.0_jiti@1.21.6_yaml@2.6.1/node_modules/vitest/dist/chunks/cli-api.FAAw0S6C.js:10798:9
 ❯ Vitest.runFiles ../../node_modules/.pnpm/vitest@2.1.6_@types+node@22.0.0_jiti@1.21.6_yaml@2.6.1/node_modules/vitest/dist/chunks/cli-api.FAAw0S6C.js:10820:12

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { code: 'ERR_RUNTIME_FAILURE' }
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 Test Files  no tests
      Tests  no tests
     Errors  1 error
   Start at  16:32:23
   Duration  559ms (transform 0ms, setup 0ms, collect 0ms, tests 0ms, environment 0ms, prepare 0ms)

[vpw:dbg] Shutting down runtimes...
error during close MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (/Users/codehex/go/src/github.com/codehex/webapp/node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js:9983:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (/Users/codehex/go/src/github.com/codehex/webapp/node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js:3632:16)
    at async #waitForReady (/Users/codehex/go/src/github.com/codehex/webapp/node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js:10040:5)
    at async getProjectMiniflare (file:///Users/codehex/go/src/github.com/codehex/webapp/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.32_@cloudflare+workers-types@4.20241127.0_@vitest+runner@_rspzct5a3s4gq7qtap7afu3hsu/node_modules/@cloudflare/vitest-pool-workers/dist/pool/index.mjs:1430:5)
    at async Object.runTests (file:///Users/codehex/go/src/github.com/codehex/webapp/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.32_@cloudflare+workers-types@4.20241127.0_@vitest+runner@_rspzct5a3s4gq7qtap7afu3hsu/node_modules/@cloudflare/vitest-pool-workers/dist/pool/index.mjs:1683:20)
    at async Promise.all (index 5)
    at async executeTests (file:///Users/codehex/go/src/github.com/codehex/webapp/node_modules/.pnpm/vitest@2.1.6_@types+node@22.0.0_jiti@1.21.6_yaml@2.6.1/node_modules/vitest/dist/chunks/resolveConfig.RxKrDli4.js:7680:5)
    at async file:///Users/codehex/go/src/github.com/codehex/webapp/node_modules/.pnpm/vitest@2.1.6_@types+node@22.0.0_jiti@1.21.6_yaml@2.6.1/node_modules/vitest/dist/chunks/cli-api.FAAw0S6C.js:10798:9
    at async Vitest.runFiles (file:///Users/codehex/go/src/github.com/codehex/webapp/node_modules/.pnpm/vitest@2.1.6_@types+node@22.0.0_jiti@1.21.6_yaml@2.6.1/node_modules/vitest/dist/chunks/cli-api.FAAw0S6C.js:10820:12) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined,
  type: 'Unhandled Error',
  stacks: [
    {
      method: '#assembleAndUpdateConfig',
      file: '/Users/codehex/go/src/github.com/codehex/webapp/node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js',
      line: 9983,
      column: 13
    },
    {
      method: 'process.processTicksAndRejections',
      file: '/Users/codehex/go/src/github.com/codehex/webapp/workers/webapp/node:internal/process/task_queues',
      line: 105,
      column: 5
    },
    {
      method: 'Mutex.runWith',
      file: '/Users/codehex/go/src/github.com/codehex/webapp/node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js',
      line: 3632,
      column: 16
    },
    {
      method: '#waitForReady',
      file: '/Users/codehex/go/src/github.com/codehex/webapp/node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js',
      line: 10040,
      column: 5
    },
    {
      method: 'getProjectMiniflare',
      file: '/Users/codehex/go/src/github.com/codehex/webapp/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.32_@cloudflare+workers-types@4.20241127.0_@vitest+runner@_rspzct5a3s4gq7qtap7afu3hsu/node_modules/@cloudflare/vitest-pool-workers/dist/pool/index.mjs',
      line: 1430,
      column: 5
    },
    {
      method: 'Object.runTests',
      file: '/Users/codehex/go/src/github.com/codehex/webapp/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.32_@cloudflare+workers-types@4.20241127.0_@vitest+runner@_rspzct5a3s4gq7qtap7afu3hsu/node_modules/@cloudflare/vitest-pool-workers/dist/pool/index.mjs',
      line: 1683,
      column: 20
    },
    {
      method: 'executeTests',
      file: '/Users/codehex/go/src/github.com/codehex/webapp/node_modules/.pnpm/vitest@2.1.6_@types+node@22.0.0_jiti@1.21.6_yaml@2.6.1/node_modules/vitest/dist/chunks/resolveConfig.RxKrDli4.js',
      line: 7680,
      column: 5
    },
    {
      method: '',
      file: '/Users/codehex/go/src/github.com/codehex/webapp/node_modules/.pnpm/vitest@2.1.6_@types+node@22.0.0_jiti@1.21.6_yaml@2.6.1/node_modules/vitest/dist/chunks/cli-api.FAAw0S6C.js',
      line: 10798,
      column: 9
    },
    {
      method: 'Vitest.runFiles',
      file: '/Users/codehex/go/src/github.com/codehex/webapp/node_modules/.pnpm/vitest@2.1.6_@types+node@22.0.0_jiti@1.21.6_yaml@2.6.1/node_modules/vitest/dist/chunks/cli-api.FAAw0S6C.js',
      line: 10820,
      column: 12
    }
  ]
}
/Users/codehex/go/src/github.com/codehex/webapp/workers/webapp:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  webapp@ test: `vitest --run`
Exit status 1
```

**Comment by OultimoCoder** [comment]
This also occurs if you just use workers ai binding ffs.

**Comment by jbasdf** [comment]
Any word on a possible fix for this? As soon as we bring AI into our project our tests no longer work. Seems like kind of a big deal.

**Comment by ryan-mars** [comment]
Everyone I've talked to is pointing the vitest config to a sanitized `wrangler.jsonc` (`wrangler-test.jsonc` for me) with the problematic bindings stripped pre-test. Then mock the bindings in your tests.

We ended up just dropping Cloudflare AI and going with another provider.

**Comment by emily-shen** [comment]
This should be fixed in `vitest-pool-workers@0.8.1` and later. As with local dev, using the AI/vectorize bindings will access your account and hit the api by default, incurring usage fees, so we recommend mocking the bindings still. Please let us know if you have any issues or further questions 🧡
