### ISSUE TITLE
🐛 BUG: `Failed to parse URL from undefined`

### ISSUE THREAD

**Issue by PPRRPRR** [cloudflare/workers-sdk#7491]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.93.0

### What version of Node are you using?

23.3.0

### What operating system and version are you using?

Ubuntu 24.04.1 LTS

### Observed behavior
In cli.js _(node_modules/wrangler/wrangler-dist/cli.js)_, lines 148787, 148793, etc.:
References to <kbd>finalResponse.result.signed_url</kbd> will surely fail because there is no property named `signed_url`.

### Expected behavior
`finalResponse.result` *does* have a property with a similar name `signedUrl`.  Most likely `signed_url` is meant to be replaced by `signedUrl` by now?

### Steps to reproduce
Should be pretty straightforward...
```bash
$ npx wrangler d1 export your-db --remote --output ./your-db.sql --no-data

✘ [ERROR] Failed to parse URL from undefined
```

### Please provide any relevant error logs

```diff
-- 2024-12-09T16:11:07.512Z log
You can also download your export from the following URL manually. This link will be valid for one hour: undefined
---

--- 2024-12-09T16:11:07.517Z log

---

--- 2024-12-09T16:11:07.595Z error
✘ [ERROR] Failed to parse URL from undefined


---

--- 2024-12-09T16:11:07.595Z debug
TypeError: Failed to parse URL from undefined
    at fetch (/home/***/.npm/_npx/beefbabedeadcafe/node_modules/wrangler/wrangler-dist/cli.js:17232:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async promise (/home/***/.npm/_npx/beefbabedeadcafe/node_modules/wrangler/wrangler-dist/cli.js:148793:24)
    at async spinnerWhile (/home/***/.npm/_npx/beefbabedeadcafe/node_modules/wrangler/wrangler-dist/cli.js:118492:20)
    at async exportRemotely (/home/***/.npm/_npx/beefbabedeadcafe/node_modules/wrangler/wrangler-dist/cli.js:148790:3)
    at async Object.Handler [as handler] (/home/***/.npm/_npx/beefbabedeadcafe/node_modules/wrangler/wrangler-dist/cli.js:148723:12)
---

--- 2024-12-09T16:11:07.595Z log
If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
---

--- 2024-12-09T16:11:11.517Z debug
Sentry: Capturing exception TypeError: Failed to parse URL from undefined
---
```

**Comment by andyjessop** [comment]
Thanks for this @PPRRPRR. For whoever picks this up from the backlog, let's [check the signature here](https://github.com/cloudflare/workers-sdk/blob/dbc678218a0ec9c42201da1300c610068c3d7dcb/packages/wrangler/src/d1/types.ts#L143).

**Comment by PPRRPRR** [comment]
You're very welcome @andyjessop.  Thanks for taking the time to review this, too.

**Comment by lrapoport-cf** [comment]
hi @PPRRPRR :) apologies for the delay. we've tested the command with wrangler 4.40.0 and can confirm it's working. we also note that the API docs specify a `signed_url` field here: https://developers.cloudflare.com/api/resources/d1/subresources/database/methods/export/#(params)%20default%20%3E%20(param)%20account_id%20%3E%20(schema). as such, we're going to close this issue for now, but please feel free open a new one referencing this one if this is still an issue for you. thank you!
