### ISSUE TITLE
🐛 BUG: login not working

### ISSUE THREAD

**Issue by realguse** [cloudflare/workers-sdk#7553]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.95.0

### What version of Node are you using?

23.4.0

### What operating system and version are you using?

macOS Sequoia 15.2

### Describe the Bug

When trying to login with wrangler, either via `wrangler login` or any other command that needs it, it throws an error. The browser window opens, but clicking the Authorize button results in an finite loading time. Clicking the button a second time causes a error on the page saying `No redirect uri set!`

### Please provide any relevant error logs

```cmd
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: fetch failed
    at fetch (/opt/homebrew/Cellar/cloudflare-wrangler2/3.95.0/libexec/lib/node_modules/wrangler/wrangler-dist/cli.js:17232:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchAuthToken (/opt/homebrew/Cellar/cloudflare-wrangler2/3.95.0/libexec/lib/node_modules/wrangler/wrangler-dist/cli.js:119915:10)
    at async exchangeAuthCodeForAccessToken (/opt/homebrew/Cellar/cloudflare-wrangler2/3.95.0/libexec/lib/node_modules/wrangler/wrangler-dist/cli.js:119540:20)
    at async Server.<anonymous> (/opt/homebrew/Cellar/cloudflare-wrangler2/3.95.0/libexec/lib/node_modules/wrangler/wrangler-dist/cli.js:119700:30)
```

**Comment by realguse** [comment]
Sorry, but this now just suddenly works
