### ISSUE TITLE
🐛 BUG: Fails to run workers vitest on macOS 15.1.1 but works on Debian 12

### ISSUE THREAD

**Issue by rwv** [cloudflare/workers-sdk#7569]
### Which Cloudflare product(s) does this pertain to?

Workers Vitest Integration

### What version(s) of the tool(s) are you using?

      '@cloudflare/vitest-pool-workers':         specifier: ^0.5.37         version: 0.5.37(@cloudflare/workers-types@4.20241205.0)(@vitest/runner@2.1.8)(@vitest/snapshot@2.1.8)(vitest@2.1.8(@types/node@22.10.2))

### What version of Node are you using?

20.14.0 / 22.12.0

### What operating system and version are you using?

macOS 15.1.1

### Observed behavior
Works on Debian 12 but failed on macOS 15.1.1

``` yaml
      '@cloudflare/vitest-pool-workers':
        specifier: ^0.5.37
        version: 0.5.37(@cloudflare/workers-types@4.20241205.0)(@vitest/runner@2.1.8)(@vitest/snapshot@2.1.8)(vitest@2.1.8(@types/node@22.10.2))
```

### Steps to reproduce
Please provide the following:

vitest.config.ts
```ts
import { defineWorkersConfig } from "@cloudflare/vitest-pool-workers/config";

export default defineWorkersConfig({
  test: {
    setupFiles: ["./test-env-setup.ts"],
    poolOptions: {
      workers: {
        wrangler: { configPath: "./wrangler.toml" },
      },
    },
    coverage: {
      provider: "istanbul", // or 'v8'
      reporter: ["text", "json-summary", "json", "html", "clover"],
      thresholds: {
        100: true,
      },
      include: ["src"],
    },
  },
});
```

### Please provide any relevant error logs

```
stack: 104d9ae4b 104d9b027 104d6b263 104d95614 10292f50c 10321b8fc 104d8ca48 1037fd707 1037fe057 1037ffc3b 1037e5054 1037ea894 102923c87 10292328f; spec = /?specifier=%2FUsers%2Fuser%2FCode%2Ftest-project%2Fnode_modules%2F.pnpm%2Fdrizzle-orm%400.38.2_%40cloudflare%2Bworkers-types%404.20241205.0_%40libsql%2Bclient-wasm%400.14.0%2Fnode_modules%2Fdrizzle-orm%2Fsqlite-core%2Fquery-builders%2Fselect.types.js&referrer=%2FUsers%2Fuser%2FCode%2Ftest-project%2Fnode_modules%2F.pnpm%2Fdrizzle-orm%400.38.2_%40cloudflare%2Bworkers-types%404.20241205.0_%40libsql%2Bclient-wasm%400.14.0%2Fnode_modules%2Fdrizzle-orm%2Fsqlite-core%2Fquery-builders%2Findex.js&rawSpecifier=.%2Fselect.types.js
workerd/jsg/util.c++:274: error: e = kj/async-io-unix.c++:1510: failed: connect(): Can't assign requested address; address = 127.0.0.1:51756
stack: 104d9734f 104d94ffb 104d95614 10292f50c 10293c19b 10321b8fc 104d8ca48 1037fd707 1037fe057 1037ffc3b 1037e5054 1037ea894 1037fade8 1028ebd8c 10300bb40 102f44c98; sentryErrorContext = jsgInternalError
workerd/io/worker.c++:2067: info: uncaught exception; source = Uncaught (in promise); stack = Error: internal error
workerd/io/worker.c++:2067: info: uncaught exception; source = Uncaught (in response); stack = Error: internal error
Error running worker: Error: internal error
    at WorkersTestRunner.updateStackedStorage (Users/user/Code/test-project/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.37_@cloudflare+workers-types@4.20241205.0_@vitest+runner@_ypgotjharrdkzq5qfx6jumfixy/node_modules/@cloudflare/vitest-pool-workers/dist/worker/lib/cloudflare/test-runner.mjs:125:17)
    at WorkersTestRunner.onBeforeRunSuite (Users/user/Code/test-project/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.37_@cloudflare+workers-types@4.20241205.0_@vitest+runner@_ypgotjharrdkzq5qfx6jumfixy/node_modules/@cloudflare/vitest-pool-workers/dist/worker/lib/cloudflare/test-runner.mjs:159:5)
    at runSuite (Users/user/Code/test-project/node_modules/.pnpm/@vitest+runner@2.1.8/node_modules/@vitest/runner/dist/index.js:1155:3)
    at runFiles (Users/user/Code/test-project/node_modules/.pnpm/@vitest+runner@2.1.8/node_modules/@vitest/runner/dist/index.js:1262:5)
    at startTests (Users/user/Code/test-project/node_modules/.pnpm/@vitest+runner@2.1.8/node_modules/@vitest/runner/dist/index.js:1271:3)
    at Users/user/Code/test-project/node_modules/.pnpm/vitest@2.1.8_@types+node@22.10.2/node_modules/vitest/dist/chunks/runBaseTests.3qpJUEJM.js:126:11
    at withEnv (Users/user/Code/test-project/node_modules/.pnpm/vitest@2.1.8_@types+node@22.10.2/node_modules/vitest/dist/chunks/runBaseTests.3qpJUEJM.js:90:5)
    at run (Users/user/Code/test-project/node_modules/.pnpm/vitest@2.1.8_@types+node@22.10.2/node_modules/vitest/dist/chunks/runBaseTests.3qpJUEJM.js:112:3)
    at runBaseTests (Users/user/Code/test-project/node_modules/.pnpm/vitest@2.1.8_@types+node@22.10.2/node_modules/vitest/dist/chunks/base.BZZh4cSm.js:29:3)
    at execute (Users/user/Code/test-project/node_modules/.pnpm/vitest@2.1.8_@types+node@22.10.2/node_modules/vitest/dist/worker.js:127:5)
workerd/server/server.c++:3058: error: Fallback service failed to fetch module; exception = kj/async-io-unix.c++:1525: disconnected: connect(): Connection refused
stack: 1027e2e4b 1027e3027 1027b3263 1027dd614 10037750c 100c638fc 1027d4a48 101245707 101246057 101247c3b 10122d054 101232894 10036bc87 10036b28f; spec = /?specifier=%2FUsers%2Fuser%2FCode%2Ftest-project%2Fnode_modules%2F.pnpm%2Fdrizzle-orm%400.38.2_%40cloudflare%2Bworkers-types%404.20241205.0_%40libsql%2Bclient-wasm%400.14.0%2Fnode_modules%2Fdrizzle-orm%2Fsqlite-core%2Fquery-builders%2Fselect.js&referrer=%2FUsers%2Fuser%2FCode%2Ftest-project%2Fnode_modules%2F.pnpm%2Fdrizzle-orm%400.38.2_%40cloudflare%2Bworkers-types%404.20241205.0_%40libsql%2Bclient-wasm%400.14.0%2Fnode_modules%2Fdrizzle-orm%2Fsqlite-core%2Fquery-builders%2Findex.js&rawSpecifier=.%2Fselect.js
workerd/jsg/util.c++:274: error: e = kj/async-io-unix.c++:1510: failed: connect(): Can't assign requested address; address = 127.0.0.1:51772
stack: 1027df34f 1027dcffb 1027dd614 10037750c 10038419b 100c638fc 1027d4a48 101245707 101246057 101247c3b 10122d054 101232894 101242de8 100333d8c 100a53b40 10098cc98; sentryErrorContext = jsgInternalError
workerd/io/worker.c++:2067: info: uncaught exception; source = Uncaught (in promise); stack = Error: internal error
workerd/io/worker.c++:2067: info: uncaught exception; source = Uncaught (in response); stack = Error: internal error
Error running worker: Error: internal error
    at WorkersTestRunner.updateStackedStorage (Users/user/Code/test-project/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.37_@cloudflare+workers-types@4.20241205.0_@vitest+runner@_ypgotjharrdkzq5qfx6jumfixy/node_modules/@cloudflare/vitest-pool-workers/dist/worker/lib/cloudflare/test-runner.mjs:125:17)
    at WorkersTestRunner.onBeforeRunSuite (Users/user/Code/test-project/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.37_@cloudflare+workers-types@4.20241205.0_@vitest+runner@_ypgotjharrdkzq5qfx6jumfixy/node_modules/@cloudflare/vitest-pool-workers/dist/worker/lib/cloudflare/test-runner.mjs:159:5)
    at runSuite (Users/user/Code/test-project/node_modules/.pnpm/@vitest+runner@2.1.8/node_modules/@vitest/runner/dist/index.js:1155:3)
    at runFiles (Users/user/Code/test-project/node_modules/.pnpm/@vitest+runner@2.1.8/node_modules/@vitest/runner/dist/index.js:1262:5)
    at startTests (Users/user/Code/test-project/node_modules/.pnpm/@vitest+runner@2.1.8/node_modules/@vitest/runner/dist/index.js:1271:3)
    at Users/user/Code/test-project/node_modules/.pnpm/vitest@2.1.8_@types+node@22.10.2/node_modules/vitest/dist/chunks/runBaseTests.3qpJUEJM.js:126:11
    at withEnv (Users/user/Code/test-project/node_modules/.pnpm/vitest@2.1.8_@types+node@22.10.2/node_modules/vitest/dist/chunks/runBaseTests.3qpJUEJM.js:90:5)
    at run (Users/user/Code/test-project/node_modules/.pnpm/vitest@2.1.8_@types+node@22.10.2/node_modules/vitest/dist/chunks/runBaseTests.3qpJUEJM.js:112:3)
    at runBaseTests (Users/user/Code/test-project/node_modules/.pnpm/vitest@2.1.8_@types+node@22.10.2/node_modules/vitest/dist/chunks/base.BZZh4cSm.js:29:3)
    at execute (Users/user/Code/test-project/node_modules/.pnpm/vitest@2.1.8_@types+node@22.10.2/node_modules/vitest/dist/worker.js:127:5)
workerd/server/server.c++:3058: error: Fallback service failed to fetch module; exception = kj/async-io-unix.c++:1525: disconnected: connect(): Connection refused
stack: 10700ee4b 10700f027 106fdf263 107009614 104ba350c 10548f8fc 107000a48 105a71707 105a72057 105a73c3b 105a59054 105a5e894 104b97c87 104b9728f; spec = /?specifier=%2FUsers%2Fuser%2FCode%2Ftest-project%2Fnode_modules%2F.pnpm%2Fdrizzle-orm%400.38.2_%40cloudflare%2Bworkers-types%404.20241205.0_%40libsql%2Bclient-wasm%400.14.0%2Fnode_modules%2Fdrizzle-orm%2Fsqlite-core%2Fquery-builders%2Fselect.js&referrer=%2FUsers%2Fuser%2FCode%2Ftest-project%2Fnode_modules%2F.pnpm%2Fdrizzle-orm%400.38.2_%40cloudflare%2Bworkers-types%404.20241205.0_%40libsql%2Bclient-wasm%400.14.0%2Fnode_modules%2Fdrizzle-orm%2Fsqlite-core%2Fquery-builders%2Findex.js&rawSpecifier=.%2Fselect.js
workerd/jsg/util.c++:274: error: e = kj/async-io-unix.c++:1510: failed: connect(): Can't assign requested address; address = 127.0.0.1:51750
stack: 10700b34f 107008ffb 107009614 104ba350c 104bb019b 10548f8fc 107000a48 105a71707 105a72057 105a73c3b 105a59054 105a5e894 105a6ede8 104b5fd8c 10527fb40 1051b8c98; sentryErrorContext = jsgInternalError
workerd/io/worker.c++:2067: info: uncaught exception; source = Uncaught (in promise); stack = Error: internal error
workerd/io/worker.c++:2067: info: uncaught exception; source = Uncaught (in response); stack = Error: internal error
Error running worker: Error: internal error
    at WorkersTestRunner.updateStackedStorage (Users/user/Code/test-project/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.37_@cloudflare+workers-types@4.20241205.0_@vitest+runner@_ypgotjharrdkzq5qfx6jumfixy/node_modules/@cloudflare/vitest-pool-workers/dist/worker/lib/cloudflare/test-runner.mjs:125:17)
    at WorkersTestRunner.onBeforeRunSuite (Users/user/Code/test-project/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.37_@cloudflare+workers-types@4.20241205.0_@vitest+runner@_ypgotjharrdkzq5qfx6jumfixy/node_modules/@cloudflare/vitest-pool-workers/dist/worker/lib/cloudflare/test-runner.mjs:159:5)
    at runSuite (Users/user/Code/test-project/node_modules/.pnpm/@vitest+runner@2.1.8/node_modules/@vitest/runner/dist/index.js:1155:3)
    at runFiles (Users/user/Code/test-project/node_modules/.pnpm/@vitest+runner@2.1.8/node_modules/@vitest/runner/dist/index.js:1262:5)
    at startTests (Users/user/Code/test-project/node_modules/.pnpm/@vitest+runner@2.1.8/node_modules/@vitest/runner/dist/index.js:1271:3)
    at Users/user/Code/test-project/node_modules/.pnpm/vitest@2.1.8_@types+node@22.10.2/node_modules/vitest/dist/chunks/runBaseTests.3qpJUEJM.js:126:11
    at withEnv (Users/user/Code/test-project/node_modules/.pnpm/vitest@2.1.8_@types+node@22.10.2/node_modules/vitest/dist/chunks/runBaseTests.3qpJUEJM.js:90:5)
    at run (Users/user/Code/test-project/node_modules/.pnpm/vitest@2.1.8_@types+node@22.10.2/node_modules/vitest/dist/chunks/runBaseTests.3qpJUEJM.js:112:3)
    at runBaseTests (Users/user/Code/test-project/node_modules/.pnpm/vitest@2.1.8_@types+node@22.10.2/node_modules/vitest/dist/chunks/base.BZZh4cSm.js:29:3)
    at execute (Users/user/Code/test-project/node_modules/.pnpm/vitest@2.1.8_@types+node@22.10.2/node_modules/vitest/dist/worker.js:127:5)
workerd/server/server.c++:3058: error: Fallback service failed to fetch module; exception = kj/async-io-unix.c++:1525: disconnected: connect(): Connection refused
stack: 104d96e4b 104d97027 104d67263 104d91614 10292b50c 1032178fc 104d88a48 1037f9707 1037fa057 1037fbc3b 1037e1054 1037e6894 10291fc87 10291f28f; spec = /?specifier=%2FUsers%2Fuser%2FCode%2Ftest-project%2Fnode_modules%2F.pnpm%2Fdrizzle-orm%400.38.2_%40cloudflare%2Bworkers-types%404.20241205.0_%40libsql%2Bclient-wasm%400.14.0%2Fnode_modules%2Fdrizzle-orm%2Fsqlite-core%2Fquery-builders%2Fselect.js&referrer=%2FUsers%2Fuser%2FCode%2Ftest-project%2Fnode_modules%2F.pnpm%2Fdrizzle-orm%400.38.2_%40cloudflare%2Bworkers-types%404.20241205.0_%40libsql%2Bclient-wasm%400.14.0%2Fnode_modules%2Fdrizzle-orm%2Fsqlite-core%2Fquery-builders%2Findex.js&rawSpecifier=.%2Fselect.js
workerd/jsg/util.c++:274: error: e = kj/async-io-unix.c++:1510: failed: connect(): Can't assign requested address; address = 127.0.0.1:51776
stack: 104d9334f 104d90ffb 104d91614 10292b50c 10293819b 1032178fc 104d88a48 1037f9707 1037fa057 1037fbc3b 1037e1054 1037e6894 1037f6de8 1028e7d8c 103007b40 102f40c98; sentryErrorContext = jsgInternalError
workerd/io/worker.c++:2067: info: uncaught exception; source = Uncaught (in promise); stack = Error: internal error
workerd/io/worker.c++:2067: info: uncaught exception; source = Uncaught (in response); stack = Error: internal error
Error running worker: Error: internal error
    at WorkersTestRunner.updateStackedStorage (Users/user/Code/test-project/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.37_@cloudflare+workers-types@4.20241205.0_@vitest+runner@_ypgotjharrdkzq5qfx6jumfixy/node_modules/@cloudflare/vitest-pool-workers/dist/worker/lib/cloudflare/test-runner.mjs:125:17)
    at WorkersTestRunner.onBeforeRunSuite (Users/user/Code/test-project/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.37_@cloudflare+workers-types@4.20241205.0_@vitest+runner@_ypgotjharrdkzq5qfx6jumfixy/node_modules/@cloudflare/vitest-pool-workers/dist/worker/lib/cloudflare/test-runner.mjs:159:5)
    at runSuite (Users/user/Code/test-project/node_modules/.pnpm/@vitest+runner@2.1.8/node_modules/@vitest/runner/dist/index.js:1155:3)
    at runFiles (Users/user/Code/test-project/node_modules/.pnpm/@vitest+runner@2.1.8/node_modules/@vitest/runner/dist/index.js:1262:5)
    at startTests (Users/user/Code/test-project/node_modules/.pnpm/@vitest+runner@2.1.8/node_modules/@vitest/runner/dist/index.js:1271:3)
    at Users/user/Code/test-project/node_modules/.pnpm/vitest@2.1.8_@types+node@22.10.2/node_modules/vitest/dist/chunks/runBaseTests.3qpJUEJM.js:126:11
    at withEnv (Users/user/Code/test-project/node_modules/.pnpm/vitest@2.1.8_@types+node@22.10.2/node_modules/vitest/dist/chunks/runBaseTests.3qpJUEJM.js:90:5)
    at run (Users/user/Code/test-project/node_modules/.pnpm/vitest@2.1.8_@types+node@22.10.2/node_modules/vitest/dist/chunks/runBaseTests.3qpJU

 ❯ src/router.test.ts (0)
 ❯ src/logic/users/user/get-user-info.test.ts (0)
 ❯ src/logic/scan-jobs/create-scan-job.test.ts (0)
 ❯ src/logic/users/user/get-user-id.test.ts (0)
 ❯ src/logic/users/token/token.test.ts (0)
 ❯ src/logic/scan-jobs/storage/aws-client.test.ts (0)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: fetch failed
 ❯ fetch node_modules/.pnpm/undici@5.28.4/node_modules/undici/index.js:112:15
 ❯ process.processTicksAndRejections node:internal/process/task_queues:105:5
 ❯ MessagePort.<anonymous> [worker eval]:28:22

Caused by: Error: connect EADDRNOTAVAIL 127.0.0.1:52878 - Local (0.0.0.0:0)
 ❯ internalConnect node:net:1104:16
 ❯ defaultTriggerAsyncIdScope node:internal/async_hooks:464:18
 ❯ node:net:1334:9
 ❯ process.processTicksAndRejections node:internal/process/task_queues:85:11
```

**Comment by andyjessop** [comment]
@rwv thanks very much for reporting this! Would you be able to provide more information regarding the setup and code - ideally a minimal reproduction that we can use to debug. I'm unable to reproduce this locally (I have the same MacOS version)

**Comment by romeupalos** [comment]
I'm also affected by this issue, but running in a much older Mac. `Monterey 12.7.6`
It looks like the error comes from `updateStackedStorage` when trying to fetch from the loopback service.
Hard to provide a minimal reproduction repo since it is very specific to one service in our codebase. I will try to get more information about this issue and post here.

**Comment by romeupalos** [comment]
@petebacondarwin, @lrapoport-cf 
I missed the notifications on this ticket. Can we reopen it?

I'm happy to provide more details or join calls as needed.
What I can see in the logs is that `workerd` seems to not be available since the errors are all about connection refused.

Is there any way to enable additional `workerd` logs?

**Comment by penalosa** [comment]
Wrangler follows workerd's OS support policy, which is [listed in the README](https://github.com/cloudflare/workerd?tab=readme-ov-file#running-workerd). In general, this covers the last two releases of an OS (for ubuntu, we aim for the last two LTS releases, for macOS it's the last two releases).

In this particular case, Wrangler should start to work again if you update to a recent version of macOS. If that's not possible right now, you should be able to continue an older version of Wrangler, although you may not be able to use newer platform features as they're released.

**Comment by cllu** [comment]
I added a reproducing repository in https://github.com/cllu/workers-vitest-eaddrnotavail, which simply duplicate tests from the `basics-unit-integration-self` example and disable the `singleWorker` mode. The issue starts to appear after we have 85 test files on macOS. The test seems to work fine on Linux.

**Comment by cllu** [comment]
Would be great if someone can take a look with the reproducing repository above @penalosa @lrapoport-cf.

**Comment by petebacondarwin** [comment]
@cllu your reproduction does not relate to this issue which is about support for old versions of MacOS. So ideally you should create a new issue. But moreover, I just cloned and followed the instructions in the repo and I cannot reproduce the error that you are reporting in the README.

**Comment by cllu** [comment]
I was having the same issue before macOS 26 was rolled out, similar to the originally reported issue here. It is weird that I can reliably reproduce the issue on my MacBook Pro with M2, but not on other Mac systems (including the macOS on GitHub Runner). I'll take another look and see if there is specific settings on my system.

**Comment by petebacondarwin** [comment]
Closing again as a new issue has been opened for the new issue.
