### ISSUE TITLE
🐛 BUG: `npx wrangler login` does not work with VPNs (Tailscale and such).

### ISSUE THREAD

**Issue by Peru-S** [cloudflare/workers-sdk#7651]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What versions are you using?

3.95.0

### What operating system and version are you using?

WSL/Windows

### Describe the Bug

Please see the error below. It's not just VPN related - for many reasons localhost ping back may not be possible - using that as the sole way to login seems really bad/broken.

Also, the localhost curl thing doesn't work because wrangler errors out (see below). Please help avoid complicated workflow like having to use another machine or use chrome dev tools to track the localhost url to curl. 

Please just allow me to paste a code (you already have `--browser=false`, could you just avoid the localhost reflexoloy?).

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: fetch failed
    at fetch (/mnt/c/sites/cf/node_modules/wrangler/wrangler-dist/cli.js:17232:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchAuthToken (/mnt/c/sites/cf/node_modules/wrangler/wrangler-dist/cli.js:119915:10)
    at async exchangeAuthCodeForAccessToken (/mnt/c/sites/cf/node_modules/wrangler/wrangler-dist/cli.js:119540:20)
    at async Server.<anonymous> (/mnt/c/sites/cf/node_modules/wrangler/wrangler-dist/cli.js:119700:30)

✘ [ERROR] Timed out waiting for authorization code, please try again.
```

Logs:

```
 ⛅️ wrangler 3.95.0
-------------------

--
--- 2024-12-30T15:09:02.590Z log
Attempting to login via OAuth...
---

--- 2024-12-30T15:09:02.593Z log
Visit this link to authenticate: https://dash.cloudflare.com/oauth2/auth?response_type=code&client_id=BLAH&code_challenge_method=S256
---

--- 2024-12-30T15:09:55.899Z debug
Checking if domain has Access enabled: dash.cloudflare.com
---

--- 2024-12-30T15:09:55.900Z debug
Access switch not cached for: dash.cloudflare.com
---

```

**Comment by Peru-S** [comment]
Note this repros on WSL/Windows as well as Mac (as long as there is a VPN on that machine or poor connectivity)

**Comment by petebacondarwin** [comment]
Related to #11081 (VPN breaking OAuth login), but not merging the two — the error signatures differ and this one has a resolution the other does not.

`wrangler login` starts a temporary local callback server and waits for the browser to redirect to it. That server is bound with the hostname *string* `localhost` (`packages/workers-auth/src/callback-server.ts:272`), so Node resolves it through `dns.lookup`. Under a VPN or split-DNS setup that hijacks or reorders `localhost`, the server can end up on a different interface than the browser connects to, and the redirect never lands.

Two things now exist that address the specific request in this issue:

- **`wrangler login --device`** — the device authorization flow. No local callback server at all; you get a code to enter, which is exactly the "just let me paste a code" ask here.
- **`wrangler login --callback-host 127.0.0.1`** — forces a literal loopback bind instead of resolving `localhost`.

Note the two are mutually exclusive: passing `--callback-host`/`--callback-port` together with `--device` is rejected, since the device flow has no callback server.

Could you confirm whether `--device` resolves this for you? If so this can be closed, and #11081 remains as the tracking issue for the underlying `localhost` binding weakness.

**Comment by workers-devprod** [comment]
> [!NOTE]
> This is an automated, advisory triage report generated by workers-devprod. It is not an official maintainer response — a maintainer will follow up.

<details>
<summary>🤖 Automated triage report</summary>

# Issue Triage: cloudflare/workers-sdk#7651

## Summary

`wrangler login` OAuth flow relies on a localhost callback that fails in WSL/VPN/remote environments; the reporter requests a way to complete login by pasting an authorization code manually.

## Classification

- **Type:** Feature Request (filed as a bug report)
- **Component:** `packages/wrangler`
- **Severity:** Medium
- **Has Reproduction:** No
- **Quality:** Partial

## Findings

- **Created:** not available in pre-fetched data
- **Author:** Peru-S
- **Version:** wrangler 3.95.0
- **Labels:** not available in pre-fetched data
- **Comments:** not available in pre-fetched data

### Analysis

- The core request is an enhancement: `wrangler login` uses an OAuth flow that spins up a local HTTP server and requires the browser to redirect back to `localhost`. In WSL/Windows, behind a VPN, or on remote machines, that callback cannot reach Wrangler, so login fails with `Timed out waiting for authorization code`.
- The included stack trace (`fetch failed` in `fetchAuthToken` → `exchangeAuthCodeForAccessToken`) is a secondary symptom: even when the reporter tries to hit the localhost callback URL manually (e.g. via `curl`), the token exchange throws an unhandled rejection rather than surfacing a clean error. This is a real robustness gap worth noting, but the primary ask is the manual-code paste flow.
- Reporter notes `--browser=false` already exists but still depends on the localhost round-trip; they are asking for a device-code / paste-the-code style flow that avoids the localhost reflexology entirely.
- This maps to `packages/wrangler` (OAuth login code lives in wrangler's auth module). It is not a workerd/runtime issue.
- No minimal reproduction link is provided (the flow is environment-dependent: WSL/VPN/remote), but the behavior is well understood and the request is clearly described, so this does not need to be sent back purely for a repro.
- Existing workaround: users can authenticate with an API token via `CLOUDFLARE_API_TOKEN` instead of the interactive OAuth flow. This should be mentioned to the reporter.

## Recommendation

**Status:** KEEP OPEN

**Reasoning:** This is a legitimate, clearly-articulated feature request to make `wrangler login` work in environments where the localhost OAuth callback is unreachable (WSL, VPN, remote/headless). The request is actionable and there is a secondary bug (unhandled rejection during token exchange) worth tracking.

**Action:** Triage as a Wrangler auth enhancement. Confirm whether a device-code / paste-the-code login flow is on the roadmap, and separately consider hardening `exchangeAuthCodeForAccessToken` so a failed token fetch surfaces a clean error instead of an unhandled promise rejection. In the meantime, point the reporter to API-token auth as a workaround.

**Suggested Labels:** none (label set not available in pre-fetched data; apply an appropriate Wrangler/enhancement label per repo conventions)

### Suggested Comment

> Thanks for the detailed write-up. You're right that `wrangler login` currently depends on the OAuth callback being able to reach `localhost`, which doesn't work well in WSL, behind a VPN, or on remote/headless machines — and `--browser=false` still relies on that same localhost round-trip. A paste-the-code / device-code style login flow is a reasonable enhancement, and we'll track it here.
>
> Separately, the `TypeError: fetch failed` unhandled rejection in `exchangeAuthCodeForAccessToken` looks like a robustness bug — a failed token exchange should surface a clean error rather than an unhandled promise rejection. We'll look into that too.
>
> In the meantime, you can avoid the interactive OAuth flow entirely by authenticating with an API token: create a token in the dashboard and set `CLOUDFLARE_API_TOKEN` (see https://developers.cloudflare.com/workers/wrangler/system-environment-variables/). That should unblock you in WSL/VPN environments.

</details>

<details>
<summary>Structured summary (JSON)</summary>

```json
{
  "issueNumber": 7651,
  "title": "wrangler login OAuth flow depends on localhost callback; allow pasting an auth code (WSL/VPN/remote)",
  "githubUrl": "https://github.com/cloudflare/workers-sdk/issues/7651",
  "recommendation": "KEEP OPEN",
  "difficulty": "medium",
  "reasoning": "Legitimate, clearly-described feature request to make wrangler login work where the localhost OAuth callback is unreachable, plus a secondary unhandled-rejection bug in token exchange worth tracking.",
  "suggestedAction": "Triage as a Wrangler auth enhancement (device-code/paste-code flow), harden exchangeAuthCodeForAccessToken to surface clean errors, and point the reporter to CLOUDFLARE_API_TOKEN as a workaround.",
  "hasSuggestedComment": true,
  "suggestedLabels": []
}

```

</details>

**Comment by petebacondarwin** [comment]
Closing due to lack of response and resolutions available.
