### ISSUE TITLE
miniflare Crash when calling undici.fetch to support mutiple connection

### ISSUE THREAD

**Issue by TimKieu** [cloudflare/workers-sdk#8473]
I got this error message:

error: TypeError: fetch failed
      at Object.fetch (.../node_modules/.pnpm/undici@5.28.4/node_modules/undici/index.js:112:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async fetch3 (../node_modules/.pnpm/miniflare@3.20240909.0/node_modules/miniflare/dist/src/index.js:4390:20)
      at async ProxyClientBridge.dispatchFetch (/Users/.../node_modules/.pnpm/miniflare@3.20240909.0/node_modules/miniflare/dist/src/index.js:9870:22)
      at async #parseAsyncResponse (/Users/xxx../node_modules/.pnpm/miniflare@3.20240909.0/node_modules/miniflare/dist/src/index.js:6463:17)
      at async D1PreparedQuery.all (file:///Users/../node_modules/.pnpm/drizzle-orm@0.29.5_@cloudflare+workers-types@4.20240909.0/node_modules/drizzle-orm/d1/session.js:114:18)

 when my local D1 API receives multiple connections.
Can someone help with the same issue? 
Thanks much

**Comment by penalosa** [comment]
We haven't heard from you in while so I'm going to close this issue for now. If you're still running into problems feel free to open a new issue with more details and we can investigate further.
